import { Lesson } from '../../types';

const passageText = `In many Western societies, modern bankruptcy laws have undergone a shift away from a focus on punishment and toward a focus on bankruptcy as a remedy for individuals and corporations in financial trouble—and, perhaps unexpectedly, for their creditors. This shift has coincided with an ever-increasing reliance on declarations of bankruptcy by individuals and corporations with excessive debt, a trend that has drawn widespread criticism. However, any measure seeking to make bankruptcy protection less available would run the risk of preventing continued economic activity of financially troubled individuals and institutions. It is for this reason that the temptation to return to a focus on punishment of individuals or corporations that become insolvent must be resisted. Modern bankruptcy laws, in serving the needs of an interdependent society, serve the varied interests of the greatest number of citizens.

The harsh punishment for insolvency in centuries past included imprisonment of individuals and dissolution of enterprises, and reflected societies’ beliefs that the accumulation of excessive debt resulted either from debtors’ unwillingness to meet obligations or from their negligence. Insolvent debtors were thought to be breaking sacrosanct social contracts; placing debtors in prison was considered necessary in order to remove from society those who would violate such contracts and thereby defraud creditors. But creditors derive little benefit from imprisoned debtors unable to repay even a portion of their debt. And if the entity to be punished is a large enterprise, for example, an auto manufacturer, its dissolution would cause significant unemployment and the disruption of much-needed services.

Modern bankruptcy law has attempted to address the shortcomings of the punitive approach. Two beliefs underlie this shift: that the public good ought to be paramount in considering the financial insolvency of individuals and corporations; and that the public good is better served by allowing debt-heavy corporations to continue to operate, and indebted individuals to continue to earn wages, than by disabling insolvent economic entities. The mechanism for executing these goals is usually a court-directed reorganization of debtors’ obligations to creditors. Such reorganizations typically comprise debt relief and plans for court-directed transfers of certain assets from debtor to creditor. Certain strictures connected to bankruptcy—such as the fact that bankruptcies become matters of public record and are reported to credit bureaus for a number of years—may still serve a punitive function, but not by denying absolution of debts or financial reorganization. Through these mechanisms, today’s bankruptcy laws are designed primarily to assure continued engagement in productive economic activity, with the ultimate goal of restoring businesses and individuals to a degree of economic health and providing creditors with the best hope of collecting.`;

export const Lesson1_PassageAnalysis: Lesson = {
  id: "40-1",
  title: "Passage Analysis",
  content: [
    { type: 'accordion', title: 'Read Passage', content: passageText },
    { type: 'h3', text: "Passage Analysis" },
    { type: 'h4', text: "Paragraph 1: The Thesis and the Central Conflict" },
    { type: 'paragraph', text: "The first paragraph serves as an introduction and thesis statement, laying out the entire debate. The author identifies a major shift in bankruptcy law: from a focus on punishment to a focus on remedy for both debtors and their creditors. The author acknowledges the main counterargument—that this shift has led to an increase in bankruptcies and widespread criticism. However, the author immediately establishes their position, arguing that restricting access to bankruptcy would stifle economic activity. The paragraph concludes with a clear thesis: the temptation to return to a punitive system must be resisted because modern bankruptcy laws serve the needs of an interdependent society and the greatest number of citizens." },
    
    { type: 'h4', text: "Paragraph 2: The Old System and Why It Failed" },
    { type: 'paragraph', text: "This paragraph explains the historical punitive approach to show why it was flawed. Punishments were severe, including imprisonment and the dissolution of companies. This approach was rooted in a moralistic belief that debt was a personal failing or a violation of a \"sacrosanct social contract.\" The author then systematically refutes this logic by highlighting its counterproductive outcomes. For creditors, imprisoned debtors cannot work to repay debts. For society, dissolving a large enterprise leads to mass unemployment and the disruption of essential services. The paragraph concludes that the old system was a practical failure." },

    { type: 'h4', text: "Paragraph 3: The Modern System and Why It Works" },
    { type: 'paragraph', text: "The final paragraph details the logic and mechanics of the modern system. It is based on two core beliefs: that the public good is paramount, and that the public good is best served by keeping individuals and companies economically productive. The primary mechanism is a court-directed reorganization of obligations, which involves debt relief and a structured transfer of assets. The author adds nuance by acknowledging that some punitive elements remain (e.g., public records, credit reports), but these do not prevent a return to economic activity. The paragraph concludes by restating the ultimate goal of modern bankruptcy law: to ensure continued economic engagement, restore financial health, and provide creditors with the best chance of repayment." },
    
    { type: 'callout', title: "Summary", variant: "summary", text: "**The Central Argument:** The passage argues that the modern shift in bankruptcy law from a punitive to a remedial model is a positive development that benefits debtors, creditors, and society, and that a return to the old system should be resisted.\n\n**The Flaws of the Past:** The old, punitive system was based on a moralistic view of debt and failed in practice. Imprisoning debtors and dissolving companies prevented creditors from being repaid and caused widespread economic harm.\n\n**The Strengths of the Present:** The modern, remedy-focused system is based on a pragmatic concern for the \"public good.\" Through court-directed reorganization, it keeps individuals and companies economically active, allowing them to recover and providing creditors with the best possible chance of repayment." }
  ]
};
