import { Lesson } from '../../types';

const passageText = `In many Western societies, modern bankruptcy laws have undergone a shift away from a focus on punishment and toward a focus on bankruptcy as a remedy for individuals and corporations in financial trouble—and, perhaps unexpectedly, for their creditors. This shift has coincided with an ever-increasing reliance on declarations of bankruptcy by individuals and corporations with excessive debt, a trend that has drawn widespread criticism. However, any measure seeking to make bankruptcy protection less available would run the risk of preventing continued economic activity of financially troubled individuals and institutions. It is for this reason that the temptation to return to a focus on punishment of individuals or corporations that become insolvent must be resisted. Modern bankruptcy laws, in serving the needs of an interdependent society, serve the varied interests of the greatest number of citizens.

The harsh punishment for insolvency in centuries past included imprisonment of individuals and dissolution of enterprises, and reflected societies’ beliefs that the accumulation of excessive debt resulted either from debtors’ unwillingness to meet obligations or from their negligence. Insolvent debtors were thought to be breaking sacrosanct social contracts; placing debtors in prison was considered necessary in order to remove from society those who would violate such contracts and thereby defraud creditors. But creditors derive little benefit from imprisoned debtors unable to repay even a portion of their debt. And if the entity to be punished is a large enterprise, for example, an auto manufacturer, its dissolution would cause significant unemployment and the disruption of much-needed services.

Modern bankruptcy law has attempted to address the shortcomings of the punitive approach. Two beliefs underlie this shift: that the public good ought to be paramount in considering the financial insolvency of individuals and corporations; and that the public good is better served by allowing debt-heavy corporations to continue to operate, and indebted individuals to continue to earn wages, than by disabling insolvent economic entities. The mechanism for executing these goals is usually a court-directed reorganization of debtors’ obligations to creditors. Such reorganizations typically comprise debt relief and plans for court-directed transfers of certain assets from debtor to creditor. Certain strictures connected to bankruptcy—such as the fact that bankruptcies become matters of public record and are reported to credit bureaus for a number of years—may still serve a punitive function, but not by denying absolution of debts or financial reorganization. Through these mechanisms, today’s bankruptcy laws are designed primarily to assure continued engagement in productive economic activity, with the ultimate goal of restoring businesses and individuals to a degree of economic health and providing creditors with the best hope of collecting.`;

export const Lesson9_Question13: Lesson = {
  id: "40-9",
  title: "Question 13: Weaken",
  content: [
    { type: 'accordion', title: 'Read Passage (PT-128-S-1-P-2)', content: passageText },
    { type: 'h3', text: "Question 13: Weaken Breakdown (PT-128-S-1-P-2-Q-13)" },
    { type: 'blockquote', text: "**Question:** Which one of the following, if true, would most weaken the author’s argument against harsh punishment for debtors?" },
    { type: 'options', items: [
      "(A) Extensive study of the economic and legal history of many countries has shown that most individuals who served prison time for bankruptcy subsequently exhibited greater economic responsibility.",
      "(B) The bankruptcy of a certain large company has had a significant negative impact on the local economy even though virtually all of the affected employees were able to obtain similar jobs within the community.",
      "(C) Once imprisonment was no longer a consequence of insolvency, bankruptcy filings increased dramatically, then leveled off before increasing again during the 1930s.",
      "(D) The court-ordered liquidation of a large and insolvent company’s assets threw hundreds of people out of work, but the local economy nevertheless demonstrated robust growth in the immediate aftermath.",
      "(E) Countries that continue to imprison debtors enjoy greater economic health than do comparable countries that have ceased to do so. (Correct)"
    ]},
    { type: 'h4', text: "Analysis" },
    { type: 'paragraph', text: "To weaken this argument, the strongest evidence must attack its central practical premise: punitive treatment harms economic outcomes and modern non-punitive law better serves collective welfare. A local anecdote or side observation is weak; a broad cross-country comparison showing better economic health under debtor imprisonment directly undercuts the passage's core justification." },
    { type: 'callout', title: "Text Evidence", variant: "tip", text: "The argument's core claim is economic: modern law should be retained because it preserves \"productive economic activity\" and serves \"the varied interests of the greatest number of citizens.\" A strong weakener must challenge that economy-level premise directly."},
    { 
      type: 'breakdown',
      labels: { title: 'Option', text: 'Analysis' },
      items: [
        { title: "(A) Extensive study of the economic and legal history of many countries has shown that most individuals who served prison time for bankruptcy subsequently exhibited greater economic responsibility.", text: "This is a weak attack. The author's argument is about macroeconomic health (unemployment, disruption of services), not the microeconomic behavior or rehabilitation of individual debtors. The author could concede this point and still maintain that the overall economic damage of imprisoning debtors makes the policy a net negative for society.", badge: "Incorrect", badgeColor: "red" },
        { title: "(B) The bankruptcy of a certain large company has had a significant negative impact on the local economy even though virtually all of the affected employees were able to obtain similar jobs within the community.", text: "This does not weaken the argument. The author argues the modern system is better than the old one, not that it is perfect or without any negative consequences. The author could respond that while this bankruptcy was harmful, the old punitive approach of immediate dissolution would have been even worse.", badge: "Incorrect", badgeColor: "red" },
        { title: "(C) Once imprisonment was no longer a consequence of insolvency, bankruptcy filings increased dramatically, then leveled off before increasing again during the 1930s.", text: "The author already acknowledges this point in the first paragraph, noting that the shift \"has coincided with an ever-increasing reliance on declarations of bankruptcy.\" Presenting evidence for a point the author has already conceded and built into their argument does not weaken the overall conclusion.", badge: "Incorrect", badgeColor: "red" },
        { title: "(D) The court-ordered liquidation of a large and insolvent company’s assets threw hundreds of people out of work, but the local economy nevertheless demonstrated robust growth in the immediate aftermath.", text: "This provides a single, anecdotal counterexample to one of the author's supporting claims. While it might challenge the specific example of a company's dissolution always causing economic harm, a single instance is not enough to undermine the author's broad, principle-based argument about the overall effects on an \"interdependent society.\"", badge: "Incorrect", badgeColor: "red" },
        { title: "(E) Countries that continue to imprison debtors enjoy greater economic health than do comparable countries that have ceased to do so.", text: "This is a powerful weakener. It provides large-scale, comparative evidence that directly contradicts the author's central premise. The author's entire argument rests on the claim that a punitive approach harms economic health. This statement, if true, suggests that a punitive approach is correlated with better economic health. This strikes at the very heart of the author's pragmatic, economic justification for modern bankruptcy law.", badge: "Correct", badgeColor: "green" }
      ]
    }
  ]
};
