import { Lesson } from '../../types';

const passageText = `In many Western societies, modern bankruptcy laws have undergone a shift away from a focus on punishment and toward a focus on bankruptcy as a remedy for individuals and corporations in financial trouble—and, perhaps unexpectedly, for their creditors. This shift has coincided with an ever-increasing reliance on declarations of bankruptcy by individuals and corporations with excessive debt, a trend that has drawn widespread criticism. However, any measure seeking to make bankruptcy protection less available would run the risk of preventing continued economic activity of financially troubled individuals and institutions. It is for this reason that the temptation to return to a focus on punishment of individuals or corporations that become insolvent must be resisted. Modern bankruptcy laws, in serving the needs of an interdependent society, serve the varied interests of the greatest number of citizens.

The harsh punishment for insolvency in centuries past included imprisonment of individuals and dissolution of enterprises, and reflected societies’ beliefs that the accumulation of excessive debt resulted either from debtors’ unwillingness to meet obligations or from their negligence. Insolvent debtors were thought to be breaking sacrosanct social contracts; placing debtors in prison was considered necessary in order to remove from society those who would violate such contracts and thereby defraud creditors. But creditors derive little benefit from imprisoned debtors unable to repay even a portion of their debt. And if the entity to be punished is a large enterprise, for example, an auto manufacturer, its dissolution would cause significant unemployment and the disruption of much-needed services.

Modern bankruptcy law has attempted to address the shortcomings of the punitive approach. Two beliefs underlie this shift: that the public good ought to be paramount in considering the financial insolvency of individuals and corporations; and that the public good is better served by allowing debt-heavy corporations to continue to operate, and indebted individuals to continue to earn wages, than by disabling insolvent economic entities. The mechanism for executing these goals is usually a court-directed reorganization of debtors’ obligations to creditors. Such reorganizations typically comprise debt relief and plans for court-directed transfers of certain assets from debtor to creditor. Certain strictures connected to bankruptcy—such as the fact that bankruptcies become matters of public record and are reported to credit bureaus for a number of years—may still serve a punitive function, but not by denying absolution of debts or financial reorganization. Through these mechanisms, today’s bankruptcy laws are designed primarily to assure continued engagement in productive economic activity, with the ultimate goal of restoring businesses and individuals to a degree of economic health and providing creditors with the best hope of collecting.`;

export const Lesson2_Question6: Lesson = {
  id: "40-2",
  title: "Question 6: Main Point",
  content: [
    { type: 'accordion', title: 'Read Passage', content: passageText },
    { type: 'h3', text: "Question Breakdown: PT-128-S-1-P-2-Q-6" },
    { type: 'blockquote', text: "**Question:** Which one of the following most accurately expresses the main point of the passage?" },
    { type: 'options', items: [
      "(A) The modern trend in bankruptcy law away from punishment and toward the maintenance of economic activity serves the best interests of society and should not be abandoned. [91.0%] (Correct)",
      "(B) Bankruptcy laws have evolved in order to meet the needs of creditors, who depend on the continued productive activity of private citizens and profit-making enterprises. [2.0%]",
      "(C) Modern bankruptcy laws are justified on humanitarian grounds, even though the earlier punitive approach was more economically efficient. [0.0%]",
      "(D) Punishment for debt no longer holds deterrent value for debtors and is therefore a concept that has been largely abandoned as ineffective. [0.0%]",
      "(E) Greater economic interdependence has triggered the formation of bankruptcy laws that reflect a convergence of the interests of debtors and creditors. [6.0%]"
    ]},
    { type: 'paragraph', text: "This is a main point question, asking for the statement that best summarizes the author's entire argument. A correct answer must capture the key components of the passage: the description of the shift in bankruptcy law, the author's reasons for supporting this shift, and the author's conclusion or recommendation." },
    { type: 'paragraph', text: "The author's argument is that the modern trend in bankruptcy law, which moved from a punitive to a remedial focus, is a positive development. This new approach is justified on pragmatic, economic grounds: it keeps individuals and companies productive, which benefits debtors, creditors, and society as a whole. The author concludes by explicitly warning against abandoning this modern approach." },
    { 
      type: 'breakdown',
      labels: { title: 'Option', text: 'Analysis' },
      items: [
        { title: "(A) The modern trend in bankruptcy law away from punishment and toward the maintenance of economic activity serves the best interests of society and should not be abandoned.", text: "This choice accurately captures all parts of the author's argument. It identifies the \"modern trend away from punishment,\" states its purpose (\"maintenance of economic activity\"), notes its benefit (\"serves the best interests of society\"), and includes the author's prescriptive conclusion (\"should not be abandoned\").", badge: "Correct", badgeColor: "green" },
        { title: "(B) Bankruptcy laws have evolved in order to meet the needs of creditors, who depend on the continued productive activity of private citizens and profit-making enterprises.", text: "This is too narrow. While the passage argues that creditors benefit from the modern system, it states that the laws serve the \"varied interests of the greatest number of citizens,\" not just creditors. This choice elevates a supporting detail to the main point.", badge: "Incorrect", badgeColor: "red" },
        { title: "(C) Modern bankruptcy laws are justified on humanitarian grounds, even though the earlier punitive approach was more economically efficient.", text: "This is incorrect on two fronts. First, the author's justification is primarily economic (\"public good,\" \"productive economic activity\"), not humanitarian. Second, it directly contradicts the passage's claim that the earlier punitive approach was economically inefficient and destructive.", badge: "Incorrect", badgeColor: "red" },
        { title: "(D) Punishment for debt no longer holds deterrent value for debtors and is therefore a concept that has been largely abandoned as ineffective.", text: "The passage's argument against the punitive system is based on its negative economic consequences, not on its lack of deterrent value. The author never discusses whether punishment deters debt. This introduces a rationale not present in the text.", badge: "Incorrect", badgeColor: "red" },
        { title: "(E) Greater economic interdependence has triggered the formation of bankruptcy laws that reflect a convergence of the interests of debtors and creditors.", text: "This choice describes a cause (\"greater economic interdependence\") rather than the author's main point. The author's primary purpose is not just to explain the cause of the change but to defend the change itself and argue for its continuation. This answer misses the author's strong prescriptive stance.", badge: "Incorrect", badgeColor: "red" }
      ]
    }
  ]
};
