import { Lesson } from '../../types';

const passageText = `“Cosmic justice,” as Sowell uses the term, refers to the perfect justice that only an omniscient being could render—rewards and punishments that are truly deserved when all relevant things are properly taken into consideration. Inherent human limitations, however, make it impossible to achieve this type of justice through human law, even though many times it seems that people are arguing for such justice and promote policies they think will render it through our human laws. But our human legal systems should not try to dispense cosmic justice since we do not know all the critical relevant facts or understand all the complex causal interrelationships involved or even know definitively what cosmic justice really is.
Whether somebody truly deserves something is a very difficult thing for us to determine. For one thing, we are not knowledgeable enough about the person and situation, or smart enough, even if we knew what all the critical factors were, to perform the complicated calculus necessary to understand how the complex interrelationships among the various variables should affect our ultimate conclusions. Deservedness necessarily focuses on a consideration of inputs. An omniscient being is capable of perfectly considering all these things, but we are not. With all the limitations that we face as mere humans, the best we can reasonably do is judge primarily based upon outputs, or consequences, rather than inputs.

Passage B
Cosmic justice is not simply a higher degree of traditional justice; it is a fundamentally different concept. Traditionally, justice or injustice is characteristic of a process. A defendant in a criminal case would be said to have received justice if the trial were conducted as it should be, under fair rules and with an impartial judge and jury. After such a trial, it could be said that “justice was done”—regardless of the outcome. Conversely, if the trial were conducted in violation of the rules and with a judge or jury showing prejudice against the defendant, this would be considered an unfair or unjust trial—even if the prosecutor failed to convince the jury to convict an innocent person. In short, traditional justice is about impartial processes rather than either results or prospects.
On the other hand, cosmic justice foolishly seeks to correct, not only biased or discriminatory acts by individuals or social institutions, but unmerited disadvantages in general, from whatever source they may arise. In criminal trials, for example, before a murderer is sentenced, the law permits his traumatic childhood to be taken into account. Seldom is there any claim that the person murdered had anything to do with that traumatic childhood. It is only from a cosmic perspective that it could have any bearing on the crime. If punishment is meant to deter crime, then mitigating that punishment in pursuit of cosmic justice presumably reduces that deterrence and allows more crime to take place at the expense of innocent people.`;

export const Lesson5_Question23: Lesson = {
  id: "43-5",
  title: "Question 23: Analogy",
  content: [
    { type: 'accordion', title: 'Read Passage (PT-128-S-4-P-4)', content: passageText },
    { type: 'h3', text: "Question 23: Analogy Breakdown (PT-128-S-4-P-4-Q-23)" },
    { type: 'blockquote', text: "**Question:** Which one of the following is most analogous to the kind of approach both authors criticize?" },
    { type: 'options', items: [
      "(A) A local library charges children lower fines for overdue materials and lost books than it charges adults.",
      "(B) In assigning grades, a teacher takes into account not only written assignments and class performance, but also background factors unique to individual students. (Correct)",
      "(C) In assigning employee parking spaces, management takes into account an employee’s rank within, and years of service to, the company.",
      "(D) An employer with a proven history of age discrimination is forced by a court to hire qualified older employees.",
      "(E) A university admits students based not just on academic achievement, but also on documented extracurricular activities and community service."
    ]},
    { type: 'h4', text: "Analysis" },
    { type: 'paragraph', text: "Concept focus: analogy questions are solved by structure, not topic. Both authors criticize efforts to move beyond process or observable outputs and instead adjust decisions using individualized background factors that are hard to weigh fairly. So the target choice should mirror this pattern: standard criteria are supplemented by personal background considerations in pursuit of deeper fairness." },
    { type: 'callout', title: "Text Evidence", variant: "tip", text: "Map the criticized structure: (1) decision context (law/punishment), (2) normal process or output criteria, (3) extra weighting of background disadvantages (inputs), (4) concern that this introduces unstable or unjustifiable judgment. Pick the option that matches all four steps." },
    { type: 'breakdown', labels: { title: 'Option', text: 'Analysis' }, items: [
      { title: "(A) A local library charges children lower fines...", text: "This is a categorical policy rule, not a case-by-case attempt to compute hidden personal causation. It lacks the individualized background-factor calculus both passages criticize.", badge: "Incorrect", badgeColor: "red" },
      { title: "(B) In assigning grades, a teacher takes into account... background factors unique to individual students.", text: "This best matches the criticized approach. Grades normally rest on performance outputs, but the decision is adjusted by individual background inputs, mirroring the move from process/output judgment to broader compensatory calibration.", badge: "Correct", badgeColor: "green" },
      { title: "(C) In assigning employee parking spaces, management takes into account an employee’s rank...", text: "Rank and seniority are explicit, rule-governed criteria. That resembles traditional process-based allocation, not the criticized attempt to correct broad unmerited disadvantages through individualized balancing.", badge: "Incorrect", badgeColor: "red" },
      { title: "(D) An employer... is forced by a court to hire qualified older employees.", text: "This describes a legal remedy for a specific discriminatory violation, which aligns with correcting biased acts under ordinary justice procedures. It is not the broader cosmic-style reweighting both authors target.", badge: "Incorrect", badgeColor: "red" },
      { title: "(E) A university admits students based not just on academic achievement, but also on documented extracurricular activities...", text: "Extracurriculars and service are still achievement-oriented outputs in most admissions frameworks. The option does not clearly mirror the key criticized move of importing personal disadvantage inputs into a deservedness calculation.", badge: "Incorrect", badgeColor: "red" }
    ]}
  ]
};
