import { Lesson } from '../../types';

const passageText = `“Cosmic justice,” as Sowell uses the term, refers to the perfect justice that only an omniscient being could render—rewards and punishments that are truly deserved when all relevant things are properly taken into consideration. Inherent human limitations, however, make it impossible to achieve this type of justice through human law, even though many times it seems that people are arguing for such justice and promote policies they think will render it through our human laws. But our human legal systems should not try to dispense cosmic justice since we do not know all the critical relevant facts or understand all the complex causal interrelationships involved or even know definitively what cosmic justice really is.
Whether somebody truly deserves something is a very difficult thing for us to determine. For one thing, we are not knowledgeable enough about the person and situation, or smart enough, even if we knew what all the critical factors were, to perform the complicated calculus necessary to understand how the complex interrelationships among the various variables should affect our ultimate conclusions. Deservedness necessarily focuses on a consideration of inputs. An omniscient being is capable of perfectly considering all these things, but we are not. With all the limitations that we face as mere humans, the best we can reasonably do is judge primarily based upon outputs, or consequences, rather than inputs.

Passage B
Cosmic justice is not simply a higher degree of traditional justice; it is a fundamentally different concept. Traditionally, justice or injustice is characteristic of a process. A defendant in a criminal case would be said to have received justice if the trial were conducted as it should be, under fair rules and with an impartial judge and jury. After such a trial, it could be said that “justice was done”—regardless of the outcome. Conversely, if the trial were conducted in violation of the rules and with a judge or jury showing prejudice against the defendant, this would be considered an unfair or unjust trial—even if the prosecutor failed to convince the jury to convict an innocent person. In short, traditional justice is about impartial processes rather than either results or prospects.
On the other hand, cosmic justice foolishly seeks to correct, not only biased or discriminatory acts by individuals or social institutions, but unmerited disadvantages in general, from whatever source they may arise. In criminal trials, for example, before a murderer is sentenced, the law permits his traumatic childhood to be taken into account. Seldom is there any claim that the person murdered had anything to do with that traumatic childhood. It is only from a cosmic perspective that it could have any bearing on the crime. If punishment is meant to deter crime, then mitigating that punishment in pursuit of cosmic justice presumably reduces that deterrence and allows more crime to take place at the expense of innocent people.`;

export const Lesson7_Question25: Lesson = {
  id: "43-7",
  title: "Question 25: Application",
  content: [
    { type: 'accordion', title: 'Read Passage (PT-128-S-4-P-4)', content: passageText },
    { type: 'h3', text: "Question 25: Application Breakdown (PT-128-S-4-P-4-Q-25)" },
    { type: 'blockquote', text: "**Question:** Passage A most strongly supports which one of the following inferences regarding the example of the murderer in passage B?" },
    { type: 'options', items: [
      "(A) From the perspective of cosmic justice, the murderer cannot be considered responsible for his crime.",
      "(B) Once the jury has convicted the murderer, the judge should be permitted substantial discretion in determining his punishment.",
      "(C) Recognition of our common human fallibility should lead us to err in the direction of leniency toward the murderer.",
      "(D) The extent, if any, to which the murderer’s culpability is mitigated by his childhood is beyond the ability of any judge or jury to determine. (Correct)",
      "(E) The murderer’s childhood must be presumed to have been without influence upon his criminal behavior."
    ]},
    { type: 'h4', text: "Analysis" },
    { type: 'paragraph', text: "Concept focus: application questions test whether you can transfer a rule from one context to another without changing its force. Passage A says humans cannot reliably compute deservedness from all causal inputs, so law should not attempt that cosmic-level calculation. When you apply that rule to Passage B's murderer example, the safe inference is about epistemic limits, not about automatic mercy, automatic severity, or certainty about responsibility." },
    { type: 'callout', title: "Text Evidence", variant: "tip", text: "Key transfer chain: A says we lack the knowledge and computational capacity for the \"complicated calculus\" of deservedness; B asks how traumatic childhood should affect sentencing. Applying A means we cannot determine the precise degree of mitigation that background factor should receive." },
    { type: 'breakdown', labels: { title: 'Option', text: 'Analysis' }, items: [
      { title: "(A) From the perspective of cosmic justice, the murderer cannot be considered responsible...", text: "A never gives a substantive cosmic verdict about this defendant. Its claim is that humans cannot know enough to produce that verdict reliably, so this choice overstates what A supports.", badge: "Incorrect", badgeColor: "red" },
      { title: "(B) Once the jury has convicted..., the judge should be permitted substantial discretion...", text: "A pushes away from broad discretionary recalibration based on hidden causal factors. Expanding discretion to weigh those factors is the very move A warns is beyond human capacity.", badge: "Incorrect", badgeColor: "red" },
      { title: "(C) Recognition of our common human fallibility should lead us to err in the direction of leniency...", text: "A does not derive a one-direction sentencing policy like leniency. It argues for limits on cosmic-style input balancing and for greater reliance on outputs/process, which does not logically force lighter punishment.", badge: "Incorrect", badgeColor: "red" },
      { title: "(D) The extent, if any, to which the murderer’s culpability is mitigated by his childhood is beyond the ability of any judge or jury to determine.", text: "This is the clean application of A's core rule. If humans cannot run the full causal calculus needed for deservedness, then no judge or jury can confidently compute the precise mitigation value of traumatic childhood.", badge: "Correct", badgeColor: "green" },
      { title: "(E) The murderer’s childhood must be presumed to have been without influence...", text: "A does not say background factors have no influence. It says humans cannot quantify their rightful weight with cosmic precision, which is a different and narrower claim.", badge: "Incorrect", badgeColor: "red" }
    ]}
  ]
};
