import { Lesson } from '../../types';

const passageText = `“Cosmic justice,” as Sowell uses the term, refers to the perfect justice that only an omniscient being could render—rewards and punishments that are truly deserved when all relevant things are properly taken into consideration. Inherent human limitations, however, make it impossible to achieve this type of justice through human law, even though many times it seems that people are arguing for such justice and promote policies they think will render it through our human laws. But our human legal systems should not try to dispense cosmic justice since we do not know all the critical relevant facts or understand all the complex causal interrelationships involved or even know definitively what cosmic justice really is.
Whether somebody truly deserves something is a very difficult thing for us to determine. For one thing, we are not knowledgeable enough about the person and situation, or smart enough, even if we knew what all the critical factors were, to perform the complicated calculus necessary to understand how the complex interrelationships among the various variables should affect our ultimate conclusions. Deservedness necessarily focuses on a consideration of inputs. An omniscient being is capable of perfectly considering all these things, but we are not. With all the limitations that we face as mere humans, the best we can reasonably do is judge primarily based upon outputs, or consequences, rather than inputs.

Passage B
Cosmic justice is not simply a higher degree of traditional justice; it is a fundamentally different concept. Traditionally, justice or injustice is characteristic of a process. A defendant in a criminal case would be said to have received justice if the trial were conducted as it should be, under fair rules and with an impartial judge and jury. After such a trial, it could be said that “justice was done”—regardless of the outcome. Conversely, if the trial were conducted in violation of the rules and with a judge or jury showing prejudice against the defendant, this would be considered an unfair or unjust trial—even if the prosecutor failed to convince the jury to convict an innocent person. In short, traditional justice is about impartial processes rather than either results or prospects.
On the other hand, cosmic justice foolishly seeks to correct, not only biased or discriminatory acts by individuals or social institutions, but unmerited disadvantages in general, from whatever source they may arise. In criminal trials, for example, before a murderer is sentenced, the law permits his traumatic childhood to be taken into account. Seldom is there any claim that the person murdered had anything to do with that traumatic childhood. It is only from a cosmic perspective that it could have any bearing on the crime. If punishment is meant to deter crime, then mitigating that punishment in pursuit of cosmic justice presumably reduces that deterrence and allows more crime to take place at the expense of innocent people.`;

export const Lesson1_PassageAnalysis: Lesson = {
  id: "43-1",
  title: "Passage Analysis",
  content: [
    { type: 'accordion', title: 'Read Passage', content: passageText },
    { type: 'h3', text: "Passage Analysis" },
    { type: 'h4', text: "Passage A: The Argument from Human Limitation" },
    { type: 'paragraph', text: "Passage A defines 'cosmic justice' as a perfect justice achievable only by an omniscient being, one who could weigh all relevant factors to determine what is truly deserved. The author's central argument is that humans are incapable of dispensing this kind of justice due to 'inherent human limitations.' The passage identifies three specific limitations: we lack complete knowledge of all relevant facts, we cannot comprehend the complex causal relationships, and we do not even have a definitive understanding of what cosmic justice is." },
    { type: 'paragraph', text: "The second paragraph elaborates on this theme by focusing on the concept of 'deservedness.' Calculating what a person truly deserves would require a 'complicated calculus' involving countless 'inputs' (a person's history, intentions, disadvantages, etc.), which is beyond human intellectual capacity. The author concludes that since we are not omniscient, the best a human legal system can do is to shift its focus from these unknowable 'inputs' to judging based on observable 'outputs,' or the consequences of actions." },
    
    { type: 'h4', text: "Passage B: The Argument from Flawed Concepts and Bad Consequences" },
    { type: 'paragraph', text: "Passage B argues against cosmic justice by first defining its opposite, 'traditional justice.' Traditional justice is presented as a concept focused on **process**: if fair and impartial rules are followed during a trial, justice is considered done, regardless of the outcome." },
    { type: 'paragraph', text: "The author then contrasts this with cosmic justice, which is framed as a 'foolishly' different concept. Cosmic justice aims to correct not just specific injustices but all 'unmerited disadvantages,' whatever their source. The passage uses the example of considering a murderer's traumatic childhood during sentencing. From the perspective of traditional justice, this is irrelevant to the crime itself. The author argues that attempting to apply this cosmic perspective has negative real-world **consequences**: mitigating punishment reduces the law's deterrent effect, leading to more crime and harming innocent people." },

    { type: 'h4', text: "The Head-to-Head: Inability vs. Illegitimacy" },
    { type: 'paragraph', text: "Both passages conclude that human legal systems should not attempt to implement cosmic justice, but they arrive at this conclusion for different reasons." },
    { type: 'list', items: [
      "**Passage A's argument is about inability.** It posits that cosmic justice is a theoretically sound concept for a divine being, but one that is practically impossible for humans due to our cognitive and informational limitations. It is an epistemological critique, focused on what we are capable of knowing.",
      "**Passage B's argument is about illegitimacy and negative consequences.** It argues that cosmic justice is a conceptually flawed and 'foolish' goal that is fundamentally incompatible with the principles of traditional, process-based justice. Furthermore, attempting to implement it is actively harmful to society."
    ]},
    
    { type: 'callout', title: "Summary", variant: "summary", text: "• **Passage A's Position:** The author argues against pursuing cosmic justice from a standpoint of **human limitation**. Because cosmic justice requires a complete understanding of all 'inputs' and 'deservedness'—a feat only an omniscient being could achieve—it is impossible for humans. Our legal systems should therefore focus on a more practical justice based on observable 'outputs' or consequences.\n• **Passage B's Position:** The author argues against cosmic justice by contrasting it with **traditional, process-based justice**. The author claims that cosmic justice is a 'foolish' and conceptually flawed endeavor that tries to correct all of life's unfairness. Attempting to do so, for example by mitigating punishment for criminals, has dangerous real-world **consequences**, such as reducing deterrence and leading to more crime.\n• **The Core Difference:** While both passages reject the application of cosmic justice in law, Passage A's critique is based on our **inability** to achieve it, whereas Passage B's critique is based on the concept being **fundamentally flawed** and **harmful** to the proper functioning of a legal system." }
  ]
};
