import { Lesson } from '../../types';

const passageText = `Philosopher Denise Meyerson views the Critical Legal Studies (CLS) movement as seeking to debunk orthodox legal theory by exposing its contradictions. However, Meyerson argues that CLS proponents tend to see contradictions where none exist, and that CLS overrates the threat that conflict poses to orthodox legal theory.
According to Meyerson, CLS proponents hold that the existence of conflicting values in the law implies the absence of any uniquely right solution to legal cases. CLS argues that these conflicting values generate equally plausible but opposing answers to any given legal question, and, consequently, that the choice between the conflicting answers must necessarily be arbitrary or irrational. Meyerson denies that the existence of conflicting values makes a case irresolvable, and asserts that at least some such cases can be resolved by ranking the conflicting values. For example, a lawyer’s obligation to preserve a client’s confidences may entail harming other parties, thus violating moral principle. This conflict can be resolved if it can be shown that in certain cases the professional obligation overrides ordinary moral obligations.
In addition, says Meyerson, even when the two solutions are equally compelling, it does not follow that the choice between them must be irrational. On the contrary, a solution that is not rationally required need not be unreasonable. Meyerson concurs with another critic that instead of concentrating on the choice between two compelling alternatives, we should rather reflect on the difference between both of these answers on the one hand, and some utterly unreasonable answer on the other—such as deciding a property dispute on the basis of which claimant is louder. The acknowledgment that conflicting values can exist, then, does not have the far-reaching implications imputed by CLS; even if some answer to a problem is not the only answer, opting for it can still be reasonable.
Last, Meyerson takes issue with the CLS charge that legal formalism, the belief that there is a quasi-deductive method capable of giving solutions to problems of legal choice, requires objectivism, the belief that the legal process has moral authority. Meyerson claims that showing the law to be unambiguous does not demonstrate its legitimacy: consider a game in which participants compete to steal the item of highest value from a shop; while a person may easily identify the winner in terms of the rules, it does not follow that the person endorses the rules of the game. A CLS scholar might object that legal cases are unlike games, in that one cannot merely apply the rules without appealing to, and therefore endorsing, external considerations of purpose, policy, and value. But Meyerson replies that such considerations may be viewed as part of, not separate from, the rules of the game.`;

export const Lesson1_PassageAnalysis: Lesson = {
  id: "52-1",
  title: "Passage Analysis: Critical Legal Studies",
  content: [
    { type: 'accordion', title: 'Read Passage', content: passageText },
    { type: 'h3', text: "Passage Breakdown" },
    { type: 'paragraph', text: "This passage is a philosophical showdown. It's all about how one thinker, Denise Meyerson, takes on the ideas of a legal movement called Critical Legal Studies (CLS). The author shows us Meyerson's counter-attack, one point at a time." },
    { type: 'hr' },
    { type: 'h4', text: "Paragraph 1: Introducing the Players" },
    { type: 'paragraph', text: "First, we meet the two sides. On one side, you have the Critical Legal Studies (CLS) folks, who love finding contradictions to challenge traditional law. On the other, you have Denise Meyerson, who thinks CLS is overreacting and seeing problems that don't exist." },
    { type: 'h4', text: "Paragraph 2: Disagreement #1 - You *Can* Solve Conflicts" },
    { type: 'paragraph', text: "Here's the first big fight. CLS says that when legal values clash, any choice a judge makes is basically a random guess. Meyerson pushes back, saying, 'Not so fast.' She argues you can solve these clashes by **ranking the values**—figuring out which one is more important in that specific case." },
    { type: 'h4', text: "Paragraph 3: Disagreement #2 - A Choice Can Be Good, Not Perfect" },
    { type: 'paragraph', text: "Meyerson's next point is that even with two equally good choices, picking one isn't irrational. She says there's a world of difference between picking one of two decent options and picking a crazy one (like siding with the louder person in a dispute). A choice doesn't have to be perfect to be reasonable." },
    { type: 'h4', text: "Paragraph 4: Disagreement #3 - Law is Just a Game" },
    { type: 'paragraph', text: "Meyerson's final jab is at the CLS idea that you can't use legal rules without morally agreeing with them. She uses a **game analogy**. You can know who won a 'game of theft' based on the rules, but that doesn't mean you think stealing is okay. Meyerson says law is the same: you can apply the rules without personally endorsing them." },
    { type: 'callout', title: 'Summary of the Argument', variant: 'summary', text: "Meyerson thinks CLS is wrong about the law being hopelessly contradictory. She makes three points: (1) You can resolve conflicting legal values by ranking them. (2) Even with two equal options, a choice isn't irrational just because it's not the only one. (3) Applying a legal rule is like playing a game—you can follow the rules without morally agreeing with them." }
  ]
};