import { Lesson } from '../../types';

const passageText = `From a critical discussion of the work of Victorian photographer Julia Margaret Cameron.
What Cameron called her “fancy-subject” pictures—photographs in which two or more costumed sitters enacted, under Cameron’s direction, scenes from the Bible, mythology, Shakespeare, or Tennyson—bear unmistakable traces of the often comical conditions under which they were taken. In many respects they have more connection to the family album pictures of recalcitrant relatives who have been herded together for the obligatory group picture than they do to the masterpieces of Western painting. In Raphael and Giotto there are no infant Christs whose faces are blurred because they moved, or who are looking at the viewer with frank hatred. These traces, of course, are what give the photographs their life and charm. If Cameron had succeeded in her project of making seamless works of illustrative art, her work would be among the curiosities of Victorian photography—like Oscar Gustave Rejlander’s extravagantly awful The Two Ways of Life—rather than among its most vital images.
It is precisely the camera’s realism—its stubborn obsession with the surface of things—that has given Cameron’s theatricality and artificiality its atmosphere of truth. It is the truth of the sitting, rather than the fiction which all the dressing up was in aid of, that wafts out of these wonderful and strange, not-quite-in-focus photographs. They are what they are: pictures of housemaids and nieces and husbands and village children who are dressed up as Mary Madonnas and infant Jesuses and John the Baptists and Lancelots and Guineveres and trying desperately hard to sit still. The way each sitter endures his or her ordeal is the collective action of the photograph, its “plot” so to speak. When we look at a narrative painting we can suspend our disbelief; when we look at a narrative photograph we cannot. We are always aware of the photograph’s doubleness—of each figure’s imaginary and real personas. Theater can transcend its doubleness, can make us believe (for at least some of the time) that we are seeing only Lear or Medea. Still photographs of theatrical scenes can never escape being pictures of actors.
What gives Cameron’s pictures of actors their special quality—their status as treasures of photography of an unfathomably peculiar sort—is their singular combination of amateurism and artistry. In The Passing of Arthur, for example, the mast and oar of the makeshift boat representing a royal barge are obviously broomsticks and the water is white muslin drapery. But these details are insignificant. For once, the homely truth of the sitting gives right of place to the romantic fantasy of its director. The picture, a night scene, is magical and mysterious. While Cameron’s fancy-subject pictures have been compared to poor amateur theatricals, The Passing of Arthur puts one in mind of good amateur theatricals one has seen, and recalls with shameless delight.`;

export const Lesson6_Question12: Lesson = {
  id: "44-6",
  title: "Question 12: Author Viewpoint",
  content: [
    { type: 'accordion', title: 'Read Passage', content: passageText },
    { type: 'h3', text: "Question Breakdown: PT-141-S-1-P-2-Q-12" },
    { type: 'blockquote', text: "Based on the passage, the author would agree with each of the following statements except:" },
    { type: 'options', items: [
      "(A) A less realistic medium can be more conducive to suspension of disbelief than a more realistic medium. [7.0%]",
      "(B) Amateurishness is a positive quality in some works of art. [2.0%]",
      "(C) What might appear to be an incongruity in a narrative photograph can actually enhance its aesthetic value. [3.0%]",
      "(D) We are sometimes aware of both the real and the imaginary persona of an actor in a drama. [5.0%]",
      "(E) A work of art succeeds only to the extent that it realizes the artist’s intentions. [83.0%] (Correct)"
    ]},
    { type: 'paragraph', text: "This is an \"EXCEPT\" question asking which statement the author would *disagree* with. We must test each statement against the arguments and evidence in the passage. Four will be consistent with the author's views; one will be inconsistent." },
    { type: 'breakdown', labels: { title: 'Option', text: 'Analysis' }, items: [
      { title: "(A) A less realistic medium can be more conducive to suspension of disbelief than a more realistic medium.", text: "The author would **agree**. This is a direct paraphrase of the argument in the second paragraph, which contrasts painting (less realistic, allows suspension of disbelief) with photography (more realistic, does not).", badge: "Incorrect", badgeColor: "red" },
      { title: "(B) Amateurishness is a positive quality in some works of art.", text: "The author would **agree**. The third paragraph praises Cameron's work for its \"singular combination of amateurism and artistry\" and compares it favorably to \"good amateur theatricals.\"", badge: "Incorrect", badgeColor: "red" },
      { title: "(C) What might appear to be an incongruity in a narrative photograph can actually enhance its aesthetic value.", text: "The author would **agree**. This is the central thesis of the passage. The \"incongruities\" (flaws, traces of reality) are what give the photographs their \"life and charm\" and \"aesthetic value.\"", badge: "Incorrect", badgeColor: "red" },
      { title: "(D) We are sometimes aware of both the real and the imaginary persona of an actor in a drama.", text: "The author would **agree**. The careful phrasing in the second paragraph states that theater can make us believe we are seeing only the character \"*for at least some of the time*.\" This implies that at other times, we are indeed aware of both the actor and the role.", badge: "Incorrect", badgeColor: "red" },
      { title: "(E) A work of art succeeds only to the extent that it realizes the artist’s intentions.", text: "The author would **disagree**. This statement is the direct opposite of the passage's entire argument. The author's central claim is that Cameron's work is a \"successful failure.\" Her intention was to create \"seamless works,\" but she failed. The author argues that this failure to realize her intentions is precisely *why* her work is so successful and vital.", badge: "Correct", badgeColor: "green" }
    ]}
  ]
};
