import { Lesson } from '../../types';

const passageText = `From a critical discussion of the work of Victorian photographer Julia Margaret Cameron.
What Cameron called her “fancy-subject” pictures—photographs in which two or more costumed sitters enacted, under Cameron’s direction, scenes from the Bible, mythology, Shakespeare, or Tennyson—bear unmistakable traces of the often comical conditions under which they were taken. In many respects they have more connection to the family album pictures of recalcitrant relatives who have been herded together for the obligatory group picture than they do to the masterpieces of Western painting. In Raphael and Giotto there are no infant Christs whose faces are blurred because they moved, or who are looking at the viewer with frank hatred. These traces, of course, are what give the photographs their life and charm. If Cameron had succeeded in her project of making seamless works of illustrative art, her work would be among the curiosities of Victorian photography—like Oscar Gustave Rejlander’s extravagantly awful The Two Ways of Life—rather than among its most vital images.
It is precisely the camera’s realism—its stubborn obsession with the surface of things—that has given Cameron’s theatricality and artificiality its atmosphere of truth. It is the truth of the sitting, rather than the fiction which all the dressing up was in aid of, that wafts out of these wonderful and strange, not-quite-in-focus photographs. They are what they are: pictures of housemaids and nieces and husbands and village children who are dressed up as Mary Madonnas and infant Jesuses and John the Baptists and Lancelots and Guineveres and trying desperately hard to sit still. The way each sitter endures his or her ordeal is the collective action of the photograph, its “plot” so to speak. When we look at a narrative painting we can suspend our disbelief; when we look at a narrative photograph we cannot. We are always aware of the photograph’s doubleness—of each figure’s imaginary and real personas. Theater can transcend its doubleness, can make us believe (for at least some of the time) that we are seeing only Lear or Medea. Still photographs of theatrical scenes can never escape being pictures of actors.
What gives Cameron’s pictures of actors their special quality—their status as treasures of photography of an unfathomably peculiar sort—is their singular combination of amateurism and artistry. In The Passing of Arthur, for example, the mast and oar of the makeshift boat representing a royal barge are obviously broomsticks and the water is white muslin drapery. But these details are insignificant. For once, the homely truth of the sitting gives right of place to the romantic fantasy of its director. The picture, a night scene, is magical and mysterious. While Cameron’s fancy-subject pictures have been compared to poor amateur theatricals, The Passing of Arthur puts one in mind of good amateur theatricals one has seen, and recalls with shameless delight.`;

export const Lesson1_PassageAnalysis: Lesson = {
  id: "44-1",
  title: "Passage Analysis",
  content: [
    { type: 'accordion', title: 'Read Passage', content: passageText },
    { type: 'h3', text: "Passage Analysis" },
    { type: 'h4', text: "Paragraph 1: The Central Paradox - A Successful Failure" },
    { type: 'paragraph', text: "The first paragraph introduces Julia Margaret Cameron's \"fancy-subject\" pictures—highly staged photographs of costumed sitters enacting scenes from literature, mythology, or the Bible. The author immediately establishes a central paradox: these photographs are great *because* they are flawed. They bear \"unmistakable traces of the often comical conditions under which they were taken,\" such as a blurred face from a moving baby or a child glaring at the camera. The author argues that these imperfections give the photos their \"life and charm.\" If Cameron had succeeded in her goal of making seamless works of art, her photos would be forgotten. Her failure to achieve her stated intention was the key to her artistic success." },
    { type: 'h4', text: "Paragraph 2: The Theory Behind the Paradox - The \"Doubleness\" of Photography" },
    { type: 'paragraph', text: "This paragraph explains the theoretical basis for this paradox, rooting it in the nature of the photographic medium. The camera's inherent realism—its \"stubborn obsession with the surface of things\"—infuses Cameron's artificial scenes with an \"atmosphere of truth.\" This is not the truth of the fiction being portrayed, but the \"truth of the sitting.\" The viewer is always aware that they are looking at real people (\"housemaids and nieces and husbands\") enduring the \"ordeal\" of trying to sit still. The author then draws a crucial distinction: unlike with a painting or a play, a viewer of a narrative photograph can never fully suspend their disbelief. We are always aware of the photograph's \"doubleness\"—we see both the fictional character and the real person portraying them." },
    { type: 'h4', text: "Paragraph 3: The Final Nuance - The Magic of \"Good Amateurism\"" },
    { type: 'paragraph', text: "The final paragraph refines the argument, identifying the \"special quality\" of Cameron's work as a \"singular combination of amateurism and artistry.\" The author uses the photograph *The Passing of Arthur* as a prime example. The props are admittedly amateurish (broomsticks for a mast, muslin for water). However, the author argues that in this case, \"the homely truth of the sitting gives right of place to the romantic fantasy.\" Despite the obvious fakeness of the props, the final image is \"magical and mysterious.\" The author concludes by comparing the experience to watching \"good amateur theatricals,\" where genuine passion and a compelling vision triumph over technical imperfections, creating a feeling of \"shameless delight.\"" },
    { type: 'callout', title: "Summary", variant: "summary", text: "• **The Central Paradox (Successful Failure):** The passage argues that Cameron's photographs are masterpieces not in spite of their flaws, but because of them. The \"traces\" of the real-world photoshoot are what give them their enduring vitality.\n• **The Nature of Photography (The \"Doubleness\"):** This success-through-failure is explained by the inherent realism of photography. A staged photograph always reveals its \"doubleness,\" making the \"truth of the sitting\" the real subject, as the viewer can never fully suspend disbelief.\n• **The Magic of \"Good Amateurism\":** The genius of Cameron's work lies in its unique blend of amateurism and artistry. Even with comically makeshift elements, her photos can achieve a magical quality, much like a heartfelt and delightful amateur play, where the romantic vision overcomes the humble reality." }
  ]
};
