import { Lesson } from '../../types';

const passageText = `From a critical discussion of the work of Victorian photographer Julia Margaret Cameron.
What Cameron called her “fancy-subject” pictures—photographs in which two or more costumed sitters enacted, under Cameron’s direction, scenes from the Bible, mythology, Shakespeare, or Tennyson—bear unmistakable traces of the often comical conditions under which they were taken. In many respects they have more connection to the family album pictures of recalcitrant relatives who have been herded together for the obligatory group picture than they do to the masterpieces of Western painting. In Raphael and Giotto there are no infant Christs whose faces are blurred because they moved, or who are looking at the viewer with frank hatred. These traces, of course, are what give the photographs their life and charm. If Cameron had succeeded in her project of making seamless works of illustrative art, her work would be among the curiosities of Victorian photography—like Oscar Gustave Rejlander’s extravagantly awful The Two Ways of Life—rather than among its most vital images.
It is precisely the camera’s realism—its stubborn obsession with the surface of things—that has given Cameron’s theatricality and artificiality its atmosphere of truth. It is the truth of the sitting, rather than the fiction which all the dressing up was in aid of, that wafts out of these wonderful and strange, not-quite-in-focus photographs. They are what they are: pictures of housemaids and nieces and husbands and village children who are dressed up as Mary Madonnas and infant Jesuses and John the Baptists and Lancelots and Guineveres and trying desperately hard to sit still. The way each sitter endures his or her ordeal is the collective action of the photograph, its “plot” so to speak. When we look at a narrative painting we can suspend our disbelief; when we look at a narrative photograph we cannot. We are always aware of the photograph’s doubleness—of each figure’s imaginary and real personas. Theater can transcend its doubleness, can make us believe (for at least some of the time) that we are seeing only Lear or Medea. Still photographs of theatrical scenes can never escape being pictures of actors.
What gives Cameron’s pictures of actors their special quality—their status as treasures of photography of an unfathomably peculiar sort—is their singular combination of amateurism and artistry. In The Passing of Arthur, for example, the mast and oar of the makeshift boat representing a royal barge are obviously broomsticks and the water is white muslin drapery. But these details are insignificant. For once, the homely truth of the sitting gives right of place to the romantic fantasy of its director. The picture, a night scene, is magical and mysterious. While Cameron’s fancy-subject pictures have been compared to poor amateur theatricals, The Passing of Arthur puts one in mind of good amateur theatricals one has seen, and recalls with shameless delight.`;

export const Lesson9_Question15: Lesson = {
  id: "44-9",
  title: "Question 15: Passage Purpose",
  content: [
    { type: 'accordion', title: 'Read Passage', content: passageText },
    { type: 'h3', text: "Question Breakdown: PT-141-S-1-P-2-Q-15" },
    { type: 'blockquote', text: "The main purpose of the passage is" },
    { type: 'options', items: [
      "(A) to chronicle Cameron’s artistic development as a photographer, which culminated in her masterpiece The Passing of Arthur [4.0%]",
      "(B) to argue that the tension between Cameron’s aims and the results she achieved in some of her works enhances the works’ aesthetic value [74.0%] (Correct)",
      "(C) to show that Cameron’s essentially theatrical vision accounts for both the strengths and the weaknesses of her photographic oeuvre [17.0%]",
      "(D) to explain why Cameron’s project of acquiring for photography the prestige accorded to painting was doomed to failure [1.0%]",
      "(E) to defend Cameron’s masterpiece The Passing of Arthur against its detractors by showing that it transcends the homely details of its setting [4.0%]"
    ]},
    { type: 'paragraph', text: "This is a main purpose question, asking for the overall goal of the passage. It requires synthesizing the author's entire argument into a single statement that describes what the author is trying to accomplish.\n\nThe author's argument is a nuanced piece of art criticism. It revolves around a central paradox: Julia Margaret Cameron's \"fancy-subject\" pictures are artistically successful precisely because they fail to achieve their intended goal.\n*   **Cameron's Aim:** To create \"seamless works of illustrative art\" that could rival painting.\n*   **The Result:** Flawed, imperfect photographs that reveal the \"homely truth of the sitting.\"\n*   **The Author's Argument:** The *tension* between this grand aim and the imperfect result is what gives the works their \"life and charm,\" their \"aesthetic value,\" and makes them \"treasures of photography.\"\n\nThe main purpose, therefore, is to advance this specific critical argument about how the works' value is derived from this productive tension." },
    { type: 'breakdown', labels: { title: 'Option', text: 'Analysis' }, items: [
      { title: "(A) to chronicle Cameron’s artistic development as a photographer, which culminated in her masterpiece The Passing of Arthur", text: "This is incorrect. The passage is a thematic analysis of a particular style of her work, not a \"chronicle\" of her career development over time. *The Passing of Arthur* is used as a key example, not presented as the culmination of her entire career.", badge: "Incorrect", badgeColor: "red" },
      { title: "(B) to argue that the tension between Cameron’s aims and the results she achieved in some of her works enhances the works’ aesthetic value", text: "This is a perfect summary of the author's purpose. It correctly identifies the core of the argument as the \"tension between Cameron’s aims and the results she achieved\" and accurately states the author's conclusion that this tension \"enhances the works’ aesthetic value.\"", badge: "Correct", badgeColor: "green" },
      { title: "(C) to show that Cameron’s essentially theatrical vision accounts for both the strengths and the weaknesses of her photographic oeuvre", text: "This is subtly incorrect. The author's main point is not to separate the work into \"strengths\" and \"weaknesses\" but to argue that what might traditionally be seen as weaknesses (amateurism, flaws) are, in fact, the source of the work's greatest strengths. This choice misses that paradoxical twist.", badge: "Incorrect", badgeColor: "red" },
      { title: "(D) to explain why Cameron’s project of acquiring for photography the prestige accorded to painting was doomed to failure", text: "This misrepresents the author's positive appraisal. The author does not see Cameron's project as a \"failure\" in a negative sense. The argument is that it was a \"successful failure,\" succeeding brilliantly for reasons Cameron may not have intended. The phrase \"doomed to failure\" is too negative.", badge: "Incorrect", badgeColor: "red" },
      { title: "(E) to defend Cameron’s masterpiece The Passing of Arthur against its detractors by showing that it transcends the homely details of its setting", text: "This is too narrow. The passage is about her \"fancy-subject\" pictures as a category, not just a defense of a single photograph. *The Passing of Arthur* is an important example, but it is not the sole subject of the passage.", badge: "Incorrect", badgeColor: "red" }
    ]}
  ]
};
