import { Lesson } from '../../types';

const passageText = `From a critical discussion of the work of Victorian photographer Julia Margaret Cameron.
What Cameron called her “fancy-subject” pictures—photographs in which two or more costumed sitters enacted, under Cameron’s direction, scenes from the Bible, mythology, Shakespeare, or Tennyson—bear unmistakable traces of the often comical conditions under which they were taken. In many respects they have more connection to the family album pictures of recalcitrant relatives who have been herded together for the obligatory group picture than they do to the masterpieces of Western painting. In Raphael and Giotto there are no infant Christs whose faces are blurred because they moved, or who are looking at the viewer with frank hatred. These traces, of course, are what give the photographs their life and charm. If Cameron had succeeded in her project of making seamless works of illustrative art, her work would be among the curiosities of Victorian photography—like Oscar Gustave Rejlander’s extravagantly awful The Two Ways of Life—rather than among its most vital images.
It is precisely the camera’s realism—its stubborn obsession with the surface of things—that has given Cameron’s theatricality and artificiality its atmosphere of truth. It is the truth of the sitting, rather than the fiction which all the dressing up was in aid of, that wafts out of these wonderful and strange, not-quite-in-focus photographs. They are what they are: pictures of housemaids and nieces and husbands and village children who are dressed up as Mary Madonnas and infant Jesuses and John the Baptists and Lancelots and Guineveres and trying desperately hard to sit still. The way each sitter endures his or her ordeal is the collective action of the photograph, its “plot” so to speak. When we look at a narrative painting we can suspend our disbelief; when we look at a narrative photograph we cannot. We are always aware of the photograph’s doubleness—of each figure’s imaginary and real personas. Theater can transcend its doubleness, can make us believe (for at least some of the time) that we are seeing only Lear or Medea. Still photographs of theatrical scenes can never escape being pictures of actors.
What gives Cameron’s pictures of actors their special quality—their status as treasures of photography of an unfathomably peculiar sort—is their singular combination of amateurism and artistry. In The Passing of Arthur, for example, the mast and oar of the makeshift boat representing a royal barge are obviously broomsticks and the water is white muslin drapery. But these details are insignificant. For once, the homely truth of the sitting gives right of place to the romantic fantasy of its director. The picture, a night scene, is magical and mysterious. While Cameron’s fancy-subject pictures have been compared to poor amateur theatricals, The Passing of Arthur puts one in mind of good amateur theatricals one has seen, and recalls with shameless delight.`;

export const Lesson8_Question14: Lesson = {
  id: "44-8",
  title: "Question 14: Paragraph Function",
  content: [
    { type: 'accordion', title: 'Read Passage (PT-141-S-1-P-2)', content: passageText },
    { type: 'h3', text: "Question 14: Paragraph Function Breakdown (PT-141-S-1-P-2-Q-14)" },
    { type: 'blockquote', text: "The discussion of suspension of disbelief in the second paragraph serves which one of the following purposes?" },
    { type: 'options', items: [
      "(A) It is the main conclusion of the passage, for which the discussion of Cameron’s fancy-subject pictures serves as a case study.",
      "(B) It introduces a contrast the author uses in characterizing the peculiar nature of our response to Cameron’s fancy-subject pictures. (Correct)",
      "(C) It is the key step in an argument supporting the author’s negative appraisal of the project of narrative photography.",
      "(D) It is used to explain a criticism of Cameron’s fancy-subject pictures that the author shows to be conceptually confused.",
      "(E) It draws a contrast between narrative painting and drama to support the author’s conclusion that Cameron’s fancy-subject pictures are more like the former."
    ]},
    { type: 'h4', text: "Analysis" },
    { type: 'paragraph', text: "This paragraph function question should be resolved by matching each choice to what the passage actually establishes. Use the opening and closing claims as scope anchors, then select the option that satisfies the stem without unsupported assumptions." },
    { type: 'callout', title: "Text Evidence", variant: "tip", text: "Anchor your reading in phrases such as 'From a critical discussion of the work of Victorian photographer Julia...' and 'While Cameron’s fancy-subject pictures have been compared to poor amateur theatricals,...' when checking whether a choice preserves the passage's emphasis." },
    { type: 'breakdown', labels: { title: 'Option', text: 'Analysis' }, items: [
      { title: "(A) It is the main conclusion of the passage, for which the discussion of Cameron’s fancy-subject pictures serves as a case study.", text: "This reverses the logical hierarchy. The main conclusion is about the value of Cameron's pictures. The point about suspension of disbelief is a premise used to support that conclusion, not the conclusion itself. Additional check: trap type is reversal/contradiction, because it flips the passage's direction or conclusion.", badge: "Incorrect", badgeColor: "red" },
      { title: "(B) It introduces a contrast the author uses in characterizing the peculiar nature of our response to Cameron’s fancy-subject pictures.", text: "This is a perfect description of the concept's function. It \"introduces a contrast\" (between photography and other media) that is used to explain the \"peculiar nature of our response\" (our awareness of the \"doubleness\"). Additional check: this is strongest because it directly satisfies the stem while preserving the passage's scope and emphasis.", badge: "Correct", badgeColor: "green" },
      { title: "(C) It is the key step in an argument supporting the author’s negative appraisal of the project of narrative photography.", text: "The author's appraisal of Cameron's work is overwhelmingly positive, not negative. They call the images \"wonderful,\" \"vital,\" and \"treasures.\" Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support.", badge: "Incorrect", badgeColor: "red" },
      { title: "(D) It is used to explain a criticism of Cameron’s fancy-subject pictures that the author shows to be conceptually confused.", text: "In this paragraph, the author is building their own positive argument, not explaining or refuting a criticism made by others. Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support.", badge: "Incorrect", badgeColor: "red" },
      { title: "(E) It draws a contrast between narrative painting and drama to support the author’s conclusion that Cameron’s fancy-subject pictures are more like the former.", text: "This gets the conclusion of the comparison wrong. The author draws the contrast to show that Cameron's pictures are fundamentally *unlike* paintings, precisely because they do not allow for the same suspension of disbelief. Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support.", badge: "Incorrect", badgeColor: "red" }
    ]}
  ]
};
