import { Lesson } from '../../types';

const passageText = `From a critical discussion of the work of Victorian photographer Julia Margaret Cameron.
What Cameron called her “fancy-subject” pictures—photographs in which two or more costumed sitters enacted, under Cameron’s direction, scenes from the Bible, mythology, Shakespeare, or Tennyson—bear unmistakable traces of the often comical conditions under which they were taken. In many respects they have more connection to the family album pictures of recalcitrant relatives who have been herded together for the obligatory group picture than they do to the masterpieces of Western painting. In Raphael and Giotto there are no infant Christs whose faces are blurred because they moved, or who are looking at the viewer with frank hatred. These traces, of course, are what give the photographs their life and charm. If Cameron had succeeded in her project of making seamless works of illustrative art, her work would be among the curiosities of Victorian photography—like Oscar Gustave Rejlander’s extravagantly awful The Two Ways of Life—rather than among its most vital images.
It is precisely the camera’s realism—its stubborn obsession with the surface of things—that has given Cameron’s theatricality and artificiality its atmosphere of truth. It is the truth of the sitting, rather than the fiction which all the dressing up was in aid of, that wafts out of these wonderful and strange, not-quite-in-focus photographs. They are what they are: pictures of housemaids and nieces and husbands and village children who are dressed up as Mary Madonnas and infant Jesuses and John the Baptists and Lancelots and Guineveres and trying desperately hard to sit still. The way each sitter endures his or her ordeal is the collective action of the photograph, its “plot” so to speak. When we look at a narrative painting we can suspend our disbelief; when we look at a narrative photograph we cannot. We are always aware of the photograph’s doubleness—of each figure’s imaginary and real personas. Theater can transcend its doubleness, can make us believe (for at least some of the time) that we are seeing only Lear or Medea. Still photographs of theatrical scenes can never escape being pictures of actors.
What gives Cameron’s pictures of actors their special quality—their status as treasures of photography of an unfathomably peculiar sort—is their singular combination of amateurism and artistry. In The Passing of Arthur, for example, the mast and oar of the makeshift boat representing a royal barge are obviously broomsticks and the water is white muslin drapery. But these details are insignificant. For once, the homely truth of the sitting gives right of place to the romantic fantasy of its director. The picture, a night scene, is magical and mysterious. While Cameron’s fancy-subject pictures have been compared to poor amateur theatricals, The Passing of Arthur puts one in mind of good amateur theatricals one has seen, and recalls with shameless delight.`;

export const Lesson3_Question9: Lesson = {
  id: "44-3",
  title: "Question 9: Phrase Function",
  content: [
    { type: 'accordion', title: 'Read Passage', content: passageText },
    { type: 'h3', text: "Question Breakdown: PT-141-S-1-P-2-Q-9" },
    { type: 'blockquote', text: "The author mentions the props employed in The Passing of Arthur as" },
    { type: 'options', items: [
      "(A) examples of amateurish aspects of the work [85.0%] (Correct)",
      "(B) evidence of the transformative power of theater [4.0%]",
      "(C) testimonies to Cameron’s ingenuity [7.0%]",
      "(D) indications that the work is intended ironically [3.0%]",
      "(E) support for a negative appraisal of the work [1.0%]"
    ]},
    { type: 'paragraph', text: "This question asks for the purpose of mentioning the specific props in the photograph *The Passing of Arthur*. This is a \"purpose in context\" question, requiring us to understand the role this detail plays within the argument of the third paragraph.\n\nThe third paragraph begins by identifying the \"special quality\" of Cameron's pictures as their \"singular combination of **amateurism** and **artistry**.\" The author then uses *The Passing of Arthur* as a specific \"example\" to illustrate this point. The description of the props—\"the mast and oar... are obviously broomsticks and the water is white muslin drapery\"—serves as the direct evidence for the \"amateurism\" part of the author's claim. These makeshift props are the prime example of the \"homely truth\" that coexists with the \"romantic fantasy.\"" },
    { type: 'breakdown', labels: { title: 'Option', text: 'Analysis' }, items: [
      { title: "(A) examples of amateurish aspects of the work", text: "This aligns perfectly with the analysis. The author introduces the concept of \"amateurism\" and then immediately points to the broomsticks and drapery as the primary \"examples\" of this quality.", badge: "Correct", badgeColor: "green" },
      { title: "(B) evidence of the transformative power of theater", text: "This is incorrect. The author argues in the second paragraph that still photography, unlike live theater, *cannot* fully transform its reality. We are always aware of the props and actors.", badge: "Incorrect", badgeColor: "red" },
      { title: "(C) testimonies to Cameron’s ingenuity", text: "While one could see the props as ingenious, this is not the point the author is making. The author's focus is on how these props contribute to the \"amateurish\" feel of the work, which is a key component of its unique aesthetic, not on praising Cameron's cleverness.", badge: "Incorrect", badgeColor: "red" },
      { title: "(D) indications that the work is intended ironically", text: "The author's tone is one of sincere admiration, calling the picture \"magical and mysterious\" and something to be recalled with \"shameless delight.\" There is no suggestion of irony.", badge: "Incorrect", badgeColor: "red" },
      { title: "(E) support for a negative appraisal of the work", text: "This is the opposite of the author's intent. The author explicitly states these amateurish details are \"insignificant\" compared to the overall magical effect. The props are used as part of a highly positive appraisal of the work.", badge: "Incorrect", badgeColor: "red" }
    ]}
  ]
};
