import { Lesson } from '../../types';

const passageText = `From a critical discussion of the work of Victorian photographer Julia Margaret Cameron.
What Cameron called her “fancy-subject” pictures—photographs in which two or more costumed sitters enacted, under Cameron’s direction, scenes from the Bible, mythology, Shakespeare, or Tennyson—bear unmistakable traces of the often comical conditions under which they were taken. In many respects they have more connection to the family album pictures of recalcitrant relatives who have been herded together for the obligatory group picture than they do to the masterpieces of Western painting. In Raphael and Giotto there are no infant Christs whose faces are blurred because they moved, or who are looking at the viewer with frank hatred. These traces, of course, are what give the photographs their life and charm. If Cameron had succeeded in her project of making seamless works of illustrative art, her work would be among the curiosities of Victorian photography—like Oscar Gustave Rejlander’s extravagantly awful The Two Ways of Life—rather than among its most vital images.
It is precisely the camera’s realism—its stubborn obsession with the surface of things—that has given Cameron’s theatricality and artificiality its atmosphere of truth. It is the truth of the sitting, rather than the fiction which all the dressing up was in aid of, that wafts out of these wonderful and strange, not-quite-in-focus photographs. They are what they are: pictures of housemaids and nieces and husbands and village children who are dressed up as Mary Madonnas and infant Jesuses and John the Baptists and Lancelots and Guineveres and trying desperately hard to sit still. The way each sitter endures his or her ordeal is the collective action of the photograph, its “plot” so to speak. When we look at a narrative painting we can suspend our disbelief; when we look at a narrative photograph we cannot. We are always aware of the photograph’s doubleness—of each figure’s imaginary and real personas. Theater can transcend its doubleness, can make us believe (for at least some of the time) that we are seeing only Lear or Medea. Still photographs of theatrical scenes can never escape being pictures of actors.
What gives Cameron’s pictures of actors their special quality—their status as treasures of photography of an unfathomably peculiar sort—is their singular combination of amateurism and artistry. In The Passing of Arthur, for example, the mast and oar of the makeshift boat representing a royal barge are obviously broomsticks and the water is white muslin drapery. But these details are insignificant. For once, the homely truth of the sitting gives right of place to the romantic fantasy of its director. The picture, a night scene, is magical and mysterious. While Cameron’s fancy-subject pictures have been compared to poor amateur theatricals, The Passing of Arthur puts one in mind of good amateur theatricals one has seen, and recalls with shameless delight.`;

export const Lesson4_Question10: Lesson = {
  id: "44-4",
  title: "Question 10: Strengthen/Explain",
  content: [
    { type: 'accordion', title: 'Read Passage (PT-141-S-1-P-2)', content: passageText },
    { type: 'h3', text: "Question 10: Strengthen/Explain Breakdown (PT-141-S-1-P-2-Q-10)" },
    { type: 'blockquote', text: "Which one of the following, if true, would most help to explain the claim about suspension of disbelief (near the middle of the second paragraph)?" },
    { type: 'options', items: [
      "(A) Sitting for a painting typically takes much longer than sitting for a photograph.",
      "(B) Paintings, unlike photographs, can depict obviously impossible situations.",
      "(C) All of the sitters for a painting do not have to be present at the same time.",
      "(D) A painter can suppress details about a sitter that are at odds with an imaginary persona. (Correct)",
      "(E) Paintings typically bear the stylistic imprint of an artist, school, or period."
    ]},
    { type: 'h4', text: "Analysis" },
    { type: 'paragraph', text: "This strengthen/explain question should be resolved by matching each choice to what the passage actually establishes. Use the opening and closing claims as scope anchors, then select the option that satisfies the stem without unsupported assumptions." },
    { type: 'callout', title: "Text Evidence", variant: "tip", text: "Anchor your reading in phrases such as 'From a critical discussion of the work of Victorian photographer Julia...' and 'While Cameron’s fancy-subject pictures have been compared to poor amateur theatricals,...' when checking whether a choice preserves the passage's emphasis." },
    { type: 'breakdown', labels: { title: 'Option', text: 'Analysis' }, items: [
      { title: "(A) Sitting for a painting typically takes much longer than sitting for a photograph.", text: "The duration of the sitting does not directly explain why the finished product would be more or less believable to a viewer. This is a detail about the process, not its effect. Additional check: trap type is unsupported inference, because the passage never supplies the missing support.", badge: "Incorrect", badgeColor: "red" },
      { title: "(B) Paintings, unlike photographs, can depict obviously impossible situations.", text: "This is not relevant to the author's point. The author is comparing narrative paintings and photographs that depict the *same kinds of scenes* (biblical, mythological). The issue isn't the impossibility of the scene but the believability of the portrayal of the figures within it. Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support.", badge: "Incorrect", badgeColor: "red" },
      { title: "(C) All of the sitters for a painting do not have to be present at the same time.", text: "Like (A), this is a fact about the artistic process that does not inherently explain why the final, composite image would allow for a greater suspension of disbelief. Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support.", badge: "Incorrect", badgeColor: "red" },
      { title: "(D) A painter can suppress details about a sitter that are at odds with an imaginary persona.", text: "This choice directly addresses the core issue. The problem with the photographs is that distracting real-world details (the \"truth of the sitting\") intrude upon the fiction. If a painter can simply choose to \"suppress\" these details—to not paint the fidgeting or the hateful stare—they can create a more perfect illusion. This control over detail explains why a painting can be a more seamless fiction, thus allowing for the suspension of disbelief. Additional check: this is strongest because it directly satisfies the stem while preserving the passage's scope and emphasis.", badge: "Correct", badgeColor: "green" },
      { title: "(E) Paintings typically bear the stylistic imprint of an artist, school, or period.", text: "This stylistic imprint would likely make the viewer *more* aware of the artifice of the work (\"This is a Picasso\"), which would arguably make it harder, not easier, to suspend disbelief. Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support.", badge: "Incorrect", badgeColor: "red" }
    ]}
  ]
};
