import { Lesson } from '../../types';

const passageText = `From a critical discussion of the work of Victorian photographer Julia Margaret Cameron.
What Cameron called her “fancy-subject” pictures—photographs in which two or more costumed sitters enacted, under Cameron’s direction, scenes from the Bible, mythology, Shakespeare, or Tennyson—bear unmistakable traces of the often comical conditions under which they were taken. In many respects they have more connection to the family album pictures of recalcitrant relatives who have been herded together for the obligatory group picture than they do to the masterpieces of Western painting. In Raphael and Giotto there are no infant Christs whose faces are blurred because they moved, or who are looking at the viewer with frank hatred. These traces, of course, are what give the photographs their life and charm. If Cameron had succeeded in her project of making seamless works of illustrative art, her work would be among the curiosities of Victorian photography—like Oscar Gustave Rejlander’s extravagantly awful The Two Ways of Life—rather than among its most vital images.
It is precisely the camera’s realism—its stubborn obsession with the surface of things—that has given Cameron’s theatricality and artificiality its atmosphere of truth. It is the truth of the sitting, rather than the fiction which all the dressing up was in aid of, that wafts out of these wonderful and strange, not-quite-in-focus photographs. They are what they are: pictures of housemaids and nieces and husbands and village children who are dressed up as Mary Madonnas and infant Jesuses and John the Baptists and Lancelots and Guineveres and trying desperately hard to sit still. The way each sitter endures his or her ordeal is the collective action of the photograph, its “plot” so to speak. When we look at a narrative painting we can suspend our disbelief; when we look at a narrative photograph we cannot. We are always aware of the photograph’s doubleness—of each figure’s imaginary and real personas. Theater can transcend its doubleness, can make us believe (for at least some of the time) that we are seeing only Lear or Medea. Still photographs of theatrical scenes can never escape being pictures of actors.
What gives Cameron’s pictures of actors their special quality—their status as treasures of photography of an unfathomably peculiar sort—is their singular combination of amateurism and artistry. In The Passing of Arthur, for example, the mast and oar of the makeshift boat representing a royal barge are obviously broomsticks and the water is white muslin drapery. But these details are insignificant. For once, the homely truth of the sitting gives right of place to the romantic fantasy of its director. The picture, a night scene, is magical and mysterious. While Cameron’s fancy-subject pictures have been compared to poor amateur theatricals, The Passing of Arthur puts one in mind of good amateur theatricals one has seen, and recalls with shameless delight.`;

export const Lesson1_PassageAnalysis: Lesson = {
  id: "44-1",
  title: "Passage Analysis",
  content: [
    { type: 'accordion', title: 'Read Passage (PT-141-S-1-P-2)', content: passageText },
    { type: 'h3', text: "Passage Analysis: Julia Margaret Cameron's Photography (PT-141-S-1-P-2)" },
    { type: 'paragraph', text: "The passage advances a paradox: Cameron's staged photographs succeed artistically because they fail to erase signs of staging. Technical imperfection becomes the source of vitality." },
    { type: 'paragraph', text: "Read this as an argument about medium. Paragraph 1 introduces the success-through-failure claim, Paragraph 2 explains why photography's realism creates that effect, and Paragraph 3 refines the claim through a concrete case study." },
    { type: 'hr' },
    { type: 'h4', text: "Paragraph 1: Success Through Visible Artifice" },
    { type: 'paragraph', text: "The first paragraph defines Cameron's \"fancy-subject\" practice and then challenges conventional standards of pictorial perfection. Blurs, awkward gazes, and theatrical strain are treated as evidence of life, not defects to be eliminated." },
    { type: 'paragraph', text: "Its central move is evaluative reversal: what would count as failure under seamless pictorial ideals is reclassified as the work's artistic advantage." },
    { type: 'h4', text: "Paragraph 2: Photography's 'Doubleness' as Explanatory Principle" },
    { type: 'paragraph', text: "The second paragraph supplies the theoretical mechanism. Because photography records surfaces with stubborn specificity, staged scenes retain traces of the real sitting that produced them." },
    { type: 'paragraph', text: "The passage contrasts this with painting and theater to show that photographs of performance cannot fully suppress the actor beneath the role. That persistent doubleness is the source of their peculiar truth." },
    { type: 'h4', text: "Paragraph 3: From Amateur Means to Aesthetic Force" },
    { type: 'paragraph', text: "The final paragraph applies the principle to *The Passing of Arthur*. Improvised props are acknowledged as obvious, yet the image is still judged \"magical\" because directorial vision and emotional effect outrun technical crudity." },
    { type: 'paragraph', text: "The argument closes by defining Cameron's achievement as a fusion of amateur conditions and artistic control, not a victory of polish over imperfection." },
    { type: 'callout', title: "Summary of the Argument", variant: "summary", text: "The passage argues that Cameron's photographs derive their force from visible traces of production. Photography's built-in realism preserves both role and performer, and that doubleness allows apparently amateur elements to produce genuine artistic power." }
  ]
};
