import { Lesson } from '../../types';

const passageText = `From a critical discussion of the work of Victorian photographer Julia Margaret Cameron.
What Cameron called her “fancy-subject” pictures—photographs in which two or more costumed sitters enacted, under Cameron’s direction, scenes from the Bible, mythology, Shakespeare, or Tennyson—bear unmistakable traces of the often comical conditions under which they were taken. In many respects they have more connection to the family album pictures of recalcitrant relatives who have been herded together for the obligatory group picture than they do to the masterpieces of Western painting. In Raphael and Giotto there are no infant Christs whose faces are blurred because they moved, or who are looking at the viewer with frank hatred. These traces, of course, are what give the photographs their life and charm. If Cameron had succeeded in her project of making seamless works of illustrative art, her work would be among the curiosities of Victorian photography—like Oscar Gustave Rejlander’s extravagantly awful The Two Ways of Life—rather than among its most vital images.
It is precisely the camera’s realism—its stubborn obsession with the surface of things—that has given Cameron’s theatricality and artificiality its atmosphere of truth. It is the truth of the sitting, rather than the fiction which all the dressing up was in aid of, that wafts out of these wonderful and strange, not-quite-in-focus photographs. They are what they are: pictures of housemaids and nieces and husbands and village children who are dressed up as Mary Madonnas and infant Jesuses and John the Baptists and Lancelots and Guineveres and trying desperately hard to sit still. The way each sitter endures his or her ordeal is the collective action of the photograph, its “plot” so to speak. When we look at a narrative painting we can suspend our disbelief; when we look at a narrative photograph we cannot. We are always aware of the photograph’s doubleness—of each figure’s imaginary and real personas. Theater can transcend its doubleness, can make us believe (for at least some of the time) that we are seeing only Lear or Medea. Still photographs of theatrical scenes can never escape being pictures of actors.
What gives Cameron’s pictures of actors their special quality—their status as treasures of photography of an unfathomably peculiar sort—is their singular combination of amateurism and artistry. In The Passing of Arthur, for example, the mast and oar of the makeshift boat representing a royal barge are obviously broomsticks and the water is white muslin drapery. But these details are insignificant. For once, the homely truth of the sitting gives right of place to the romantic fantasy of its director. The picture, a night scene, is magical and mysterious. While Cameron’s fancy-subject pictures have been compared to poor amateur theatricals, The Passing of Arthur puts one in mind of good amateur theatricals one has seen, and recalls with shameless delight.`;

export const Lesson5_Question11: Lesson = {
  id: "44-5",
  title: "Question 11: Analogy",
  content: [
    { type: 'accordion', title: 'Read Passage (PT-141-S-1-P-2)', content: passageText },
    { type: 'h3', text: "Question 11: Analogy Breakdown (PT-141-S-1-P-2-Q-11)" },
    { type: 'blockquote', text: "Based on the passage, Cameron is most like which one of the following in relation to her fancy-subject pictures?" },
    { type: 'options', items: [
      "(A) a playwright who introduces incongruous elements to preserve an aesthetic distance between characters and audience",
      "(B) a rap artist whose lyrics are designed to subvert the meaning of a song sampled in his recording",
      "(C) a sculptor whose works possess a certain grandeur even though they are clearly constructed out of ordinary objects (Correct)",
      "(D) an architect whose buildings are designed to be as functional as possible",
      "(E) a film director who employs ordinary people as actors in order to give the appearance of a documentary"
    ]},
    { type: 'h4', text: "Analysis" },
    { type: 'paragraph', text: "This analogy question should be resolved by matching each choice to what the passage actually establishes. Use the opening and closing claims as scope anchors, then select the option that satisfies the stem without unsupported assumptions." },
    { type: 'callout', title: "Text Evidence", variant: "tip", text: "Anchor your reading in phrases such as 'From a critical discussion of the work of Victorian photographer Julia...' and 'While Cameron’s fancy-subject pictures have been compared to poor amateur theatricals,...' when checking whether a choice preserves the passage's emphasis." },
    { type: 'breakdown', labels: { title: 'Option', text: 'Analysis' }, items: [
      { title: "(A) a playwright who introduces incongruous elements to preserve an aesthetic distance between characters and audience", text: "This fails on intent. The passage suggests Cameron's use of humble materials was a result of circumstance and the nature of the medium, not a deliberate artistic choice to create \"aesthetic distance.\" Her goal was sincere romanticism, not intellectual detachment. Additional check: trap type is unsupported inference, because the passage never supplies the missing support.", badge: "Incorrect", badgeColor: "red" },
      { title: "(B) a rap artist whose lyrics are designed to subvert the meaning of a song sampled in his recording", text: "This fails on intent. Cameron was trying to *illustrate* and pay homage to her sources (the Bible, Shakespeare), not \"subvert\" their meaning. Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support.", badge: "Incorrect", badgeColor: "red" },
      { title: "(C) a sculptor whose works possess a certain grandeur even though they are clearly constructed out of ordinary objects", text: "This is a perfect analogy.\n*   \"possess a certain grandeur\" = Cameron's \"magical and mysterious\" scenes.\n*   \"clearly constructed out of ordinary objects\" = Cameron's use of broomsticks, housemaids, etc.\nThis choice perfectly captures the core tension between humble materials and grand artistic effect. Additional check: this is strongest because it directly satisfies the stem while preserving the passage's scope and emphasis.", badge: "Correct", badgeColor: "green" },
      { title: "(D) an architect whose buildings are designed to be as functional as possible", text: "This fails because Cameron's work is described as romantic and fantastical, not \"functional.\" Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support.", badge: "Incorrect", badgeColor: "red" },
      { title: "(E) a film director who employs ordinary people as actors in order to give the appearance of a documentary", text: "This fails on the goal. Cameron used ordinary people, but her goal was the opposite of documentary realism; she was aiming for romantic fantasy. The realistic \"truth of the sitting\" was an unintentional byproduct of her medium, not her primary aesthetic goal. Additional check: trap type is reversal/contradiction, because it flips the passage's direction or conclusion.", badge: "Incorrect", badgeColor: "red" }
    ]}
  ]
};
