import { Lesson } from '../../types';

const passageText = `Ronald Dworkin argues that judges are in danger of uncritically embracing an erroneous theory known as legal positivism because they think the only alternative is a theory that they (and Dworkin) see as clearly unacceptable—natural law. The latter theory holds that judges ought to interpret the law by consulting their own moral convictions, even if this means ignoring the letter of the law and the legal precedents for its interpretation. Dworkin regards this as an impermissible form of judicial activism that arrogates to judges powers properly reserved for legislators.
Legal positivism, the more popular of the two theories, holds that law and morality are wholly distinct. The meaning of the law rests on social convention in the same way as does the meaning of a word. Dworkin’s view is that legal positivists regard disagreement among jurists as legitimate only if it arises over what the underlying convention is, and it is to be resolved by registering a consensus, not by deciding what is morally right. In the same way, disagreement about the meaning of a word is settled by determining how people actually use it, and not by deciding what it ought to mean. Where there is no consensus, there is no legal fact of the matter. The judge’s interpretive role is limited to discerning this consensus, or the absence thereof.
According to Dworkin, this account is incompatible with the actual practice of judges and lawyers, who act as if there is a fact of the matter even in cases where there is no consensus. The theory he proposes seeks to validate this practice without falling into what Dworkin correctly sees as the error of natural law theory. It represents a kind of middle ground between the latter and legal positivism. Dworkin stresses the fact that there is an internal logic to a society’s laws and the general principles they typically embody. An interpretation that conforms to these principles may be correct even if it is not supported by a consensus. Since these general principles may involve such moral concepts as justice and fairness, judges may be called upon to consult their own moral intuitions in arriving at an interpretation. But this is not to say that judges are free to impose their own morality at will, without regard to the internal logic of the laws.
The positivist’s mistake, as Dworkin points out, is assuming that the meaning of the law can only consist in what people think it means, whether these people be the original authors of the law or a majority of the interpreter’s peers. Once we realize, as Dworkin does, that the law has an internal logic of its own that constrains interpretation, we open up the possibility of improving upon the interpretations not only of our contemporaries but of the original authors.`;

export const Lesson1_PassageAnalysis: Lesson = {
  id: "54-1",
  title: "Passage Analysis",
  content: [
    { type: 'accordion', title: 'Read Passage', content: passageText },
    { type: 'h3', text: "Passage Analysis" },
    { type: 'paragraph', text: "The passage is a breakdown of Ronald Dworkin's 'third way' of thinking about law. Dworkin argues that judges get stuck between two bad options: one where they can just use their personal morals ('natural law'), and another where they can only follow what the group agrees on ('legal positivism'). He proposes a middle ground, and the author of the passage agrees with him." },
    { type: 'h4', text: "Paragraph 1: The Problem - A Rock and a Hard Place" },
    { type: 'paragraph', text: "The passage starts by explaining Dworkin's view of the big problem for judges. They feel forced to choose between two extreme theories for interpreting the law. The first is 'natural law,' which Dworkin hates because it turns judges into lawmakers by letting them use their own moral beliefs. The second is 'legal positivism,' which Dworkin also rejects." },
    { type: 'h4', text: "Paragraph 2: Theory #1 - Legal Positivism (The 'Rules are Rules' View)" },
    { type: 'paragraph', text: "This paragraph explains legal positivism. This theory says that law and morality are completely separate. A law's meaning is just what the legal community agrees it is (the 'consensus'). If there's no consensus, there's no single right answer, and a judge's job is just to find that agreement." },
    { type: 'h4', text: "Paragraph 3: Dworkin's 'Middle Ground' Solution" },
    { type: 'paragraph', text: "Here, the author lays out Dworkin's solution, a 'middle ground.' Dworkin argues that law has its own 'internal logic,' based on big principles like justice and fairness. This logic allows a judge to find a right answer even if there's no consensus. It also lets judges use their moral compass, but in a way that's guided and constrained by the law itself, not a free-for-all like 'natural law.'" },
    { type: 'h4', text: "Paragraph 4: The Takeaway - Law Has Its Own Logic" },
    { type: 'paragraph', text: "The final paragraph sums up why Dworkin's idea is better. The author agrees with Dworkin that legal positivists are wrong to think a law's meaning is just what people agree it is. Because law has its own 'internal logic,' we can find interpretations that are better than what anyone—even the original lawmakers—first thought." },
    { type: 'callout', title: "Summary", variant: "summary", text: "The passage explains Ronald Dworkin's legal theory, which carves a middle path between two extremes. Dworkin rejects both the idea that judges can use any moral reasoning they want ('natural law') and the idea that they can only rely on community agreement ('legal positivism'). He argues that law has an 'internal logic' that guides judges, allowing for a constrained use of morality to find the right answer, even without a consensus." }
  ]
};