import { Lesson } from '../../types';

const passageText = `Recent investigations into the psychology of decision making have sparked interest among scholars seeking to understand why governments sometimes take gambles that appear theoretically unjustifiable on the basis of expected costs and benefits. Researchers have demonstrated some significant discrepancies between objective measurements of possible decision outcomes and the ways in which people subjectively value such possible results. Many of these discrepancies relate to the observation that a possible outcome perceived as a loss typically motivates more strongly than the prospect of an equivalent gain. Risk-taking is thus a more common strategy for those who believe they will lose what they already possess than it is for those who wish to gain something they do not have.
Previously, the notion that rational decision makers prefer risk-avoiding choices was considered to apply generally, epitomized by the assumption of many economists that entrepreneurs and consumers will choose a risky venture over a sure thing only when the expected measurable value of the outcome is sufficiently high to compensate the decision maker for taking the risk. What is the minimum prize that would be required to make a gamble involving a 50 percent chance of losing $100 and a 50 percent chance of winning the prize acceptable? It is commonplace that the pleasure of winning a sum of money is much less intense than the pain of losing the same amount; accordingly, such a gamble would typically be accepted only when the possible gain greatly exceeds the possible loss. Research subjects do, in fact, commonly judge that a 50 percent chance to lose $100 is unacceptable unless it is combined with an equal chance to win more than $300. Nevertheless, the recent studies indicate that risk-accepting strategies are common when the alternative to a sure loss is a substantial chance of losing an even larger amount, coupled with some chance—even a small one—of losing nothing.
Such observations are quite salient to scholars of international conflict and crisis. For example, governments typically are cautious in foreign policy initiatives that entail risk, especially the risk of armed conflict. But nations also often take huge gambles to retrieve what they perceive to have been taken from them by other nations. This type of motivation, then, can lead states to take risks that far outweigh the objectively measurable value of the lost assets. For example, when Britain and Argentina entered into armed conflict in 1982 over possession of the Falkland Islands—or Malvinas, as they are called in Spanish—each viewed the islands as territory that had been taken from them by the other; thus each was willing to commit enormous resources—and risks—to recapturing them. In international affairs, it is vital that each actor in such a situation understand the other’s subjective view of what is at stake.`;

export const Lesson1_PassageAnalysis: Lesson = {
  id: "56-1",
  title: "Passage Analysis: Psychology of Risk",
  content: [
    { type: 'accordion', title: 'Read Passage (PT-113-S-1-P-4)', content: passageText },
    { type: 'h3', text: "Passage Analysis: Psychology of Risk (PT-113-S-1-P-4)" },
    { type: 'paragraph', text: "The passage explains why decision-makers often take high risks to avoid perceived losses. Its central claim is that subjective loss framing can outweigh objective cost-benefit analysis." },
    { type: 'paragraph', text: "Read for model transfer. Paragraph 1 introduces the psychological pattern, Paragraph 2 contrasts it with standard economic expectations, and Paragraph 3 applies the framework to interstate conflict behavior." },
    { type: 'hr' },
    { type: 'h4', text: "Paragraph 1: Loss Aversion as Core Premise" },
    { type: 'paragraph', text: "The opening paragraph presents a discrepancy between objective outcome measurement and subjective valuation. Losses are weighted more heavily than equivalent gains, which shifts risk behavior under perceived threat." },
    { type: 'paragraph', text: "This paragraph establishes the explanatory variable used throughout the rest of the passage: perception of loss, not absolute expected value." },
    { type: 'h4', text: "Paragraph 2: Revising the Standard Risk Model" },
    { type: 'paragraph', text: "The second paragraph contrasts the new findings with older assumptions of generalized risk aversion. The coin-flip example demonstrates asymmetric valuation: avoiding a loss often requires disproportionately large potential gain." },
    { type: 'paragraph', text: "It then identifies the crucial exception: when a loss is framed as certain, actors may prefer gambles with severe downside if there is even a small chance of escaping loss entirely." },
    { type: 'h4', text: "Paragraph 3: International-Conflict Application" },
    { type: 'paragraph', text: "The final paragraph applies the psychology to state behavior. Governments that are usually cautious can become highly risk-acceptant when attempting to recover territory perceived as wrongly taken." },
    { type: 'paragraph', text: "The Falklands/Malvinas example operationalizes the model: both sides interpreted the dispute through loss recovery, making high-cost conflict behavior intelligible under subjective valuation." },
    { type: 'callout', title: "Summary of the Argument", variant: "summary", text: "The passage argues that loss aversion can produce risk-seeking behavior when actors face perceived certain losses. It uses this framework to explain why states may pursue high-cost conflicts that appear irrational under purely objective expected-value analysis." }
  ]
};
