import { Lesson } from '../../types';

const passageText = `Recent investigations into the psychology of decision making have sparked interest among scholars seeking to understand why governments sometimes take gambles that appear theoretically unjustifiable on the basis of expected costs and benefits. Researchers have demonstrated some significant discrepancies between objective measurements of possible decision outcomes and the ways in which people subjectively value such possible results. Many of these discrepancies relate to the observation that a possible outcome perceived as a loss typically motivates more strongly than the prospect of an equivalent gain. Risk-taking is thus a more common strategy for those who believe they will lose what they already possess than it is for those who wish to gain something they do not have.
Previously, the notion that rational decision makers prefer risk-avoiding choices was considered to apply generally, epitomized by the assumption of many economists that entrepreneurs and consumers will choose a risky venture over a sure thing only when the expected measurable value of the outcome is sufficiently high to compensate the decision maker for taking the risk. What is the minimum prize that would be required to make a gamble involving a 50 percent chance of losing $100 and a 50 percent chance of winning the prize acceptable? It is commonplace that the pleasure of winning a sum of money is much less intense than the pain of losing the same amount; accordingly, such a gamble would typically be accepted only when the possible gain greatly exceeds the possible loss. Research subjects do, in fact, commonly judge that a 50 percent chance to lose $100 is unacceptable unless it is combined with an equal chance to win more than $300. Nevertheless, the recent studies indicate that risk-accepting strategies are common when the alternative to a sure loss is a substantial chance of losing an even larger amount, coupled with some chance—even a small one—of losing nothing.
Such observations are quite salient to scholars of international conflict and crisis. For example, governments typically are cautious in foreign policy initiatives that entail risk, especially the risk of armed conflict. But nations also often take huge gambles to retrieve what they perceive to have been taken from them by other nations. This type of motivation, then, can lead states to take risks that far outweigh the objectively measurable value of the lost assets. For example, when Britain and Argentina entered into armed conflict in 1982 over possession of the Falkland Islands—or Malvinas, as they are called in Spanish—each viewed the islands as territory that had been taken from them by the other; thus each was willing to commit enormous resources—and risks—to recapturing them. In international affairs, it is vital that each actor in such a situation understand the other’s subjective view of what is at stake.`;

export const Lesson1_PassageAnalysis: Lesson = {
  id: "56-1",
  title: "Passage Analysis: Psychology of Risk",
  content: [
    { type: 'accordion', title: 'Read Passage', content: passageText },
    { type: 'h3', text: "Passage Analysis" },
    { type: 'paragraph', text: "This passage is about the psychology of risk. The big idea is that people (and countries) are wired to hate losing more than they love winning. This simple fact, called 'loss aversion,' explains why we sometimes make big, seemingly irrational gambles to avoid a loss." },
    { type: 'h4', text: "Paragraph 1: The Main Idea - We Hate Losing" },
    { type: 'paragraph', text: "The passage kicks off with a core concept from psychology: the fear of losing something you have is a much stronger motivator than the hope of gaining something of equal value. This makes people more willing to take big risks to avoid a loss they see as certain." },
    { type: 'h4', text: "Paragraph 2: Old Theory vs. New Research" },
    { type: 'paragraph', text: "This paragraph contrasts the new idea of loss aversion with the old economic view. The old theory said people are generally risk-averse. The new research shows the big exception: when facing a guaranteed loss, people suddenly become risk-takers. They'll risk a bigger loss for even a small chance to lose nothing at all." },
    { type: 'h4', text: "Paragraph 3: Applying It to Countries" },
    { type: 'paragraph', text: "The author applies this psychological rule to international politics. While governments are usually cautious, they become huge risk-takers when trying to get back territory they feel was taken from them. The Falklands/Malvinas war is the perfect example: both sides saw the islands as a loss to be recovered, so they were willing to take risks that seemed illogical from a cost-benefit standpoint." },
    { type: 'callout', title: "Summary", variant: "summary", text: "The passage explains 'loss aversion'—the idea that the fear of losing is a more powerful motivator than the hope of winning. It contrasts this with older economic theories and uses it to explain why countries take huge, seemingly irrational risks in conflicts to get back what they believe they've lost." }
  ]
};