import { Lesson } from '../../types';

const passageText = `Recent investigations into the psychology of decision making have sparked interest among scholars seeking to understand why governments sometimes take gambles that appear theoretically unjustifiable on the basis of expected costs and benefits. Researchers have demonstrated some significant discrepancies between objective measurements of possible decision outcomes and the ways in which people subjectively value such possible results. Many of these discrepancies relate to the observation that a possible outcome perceived as a loss typically motivates more strongly than the prospect of an equivalent gain. Risk-taking is thus a more common strategy for those who believe they will lose what they already possess than it is for those who wish to gain something they do not have.
Previously, the notion that rational decision makers prefer risk-avoiding choices was considered to apply generally, epitomized by the assumption of many economists that entrepreneurs and consumers will choose a risky venture over a sure thing only when the expected measurable value of the outcome is sufficiently high to compensate the decision maker for taking the risk. What is the minimum prize that would be required to make a gamble involving a 50 percent chance of losing $100 and a 50 percent chance of winning the prize acceptable? It is commonplace that the pleasure of winning a sum of money is much less intense than the pain of losing the same amount; accordingly, such a gamble would typically be accepted only when the possible gain greatly exceeds the possible loss. Research subjects do, in fact, commonly judge that a 50 percent chance to lose $100 is unacceptable unless it is combined with an equal chance to win more than $300. Nevertheless, the recent studies indicate that risk-accepting strategies are common when the alternative to a sure loss is a substantial chance of losing an even larger amount, coupled with some chance—even a small one—of losing nothing.
Such observations are quite salient to scholars of international conflict and crisis. For example, governments typically are cautious in foreign policy initiatives that entail risk, especially the risk of armed conflict. But nations also often take huge gambles to retrieve what they perceive to have been taken from them by other nations. This type of motivation, then, can lead states to take risks that far outweigh the objectively measurable value of the lost assets. For example, when Britain and Argentina entered into armed conflict in 1982 over possession of the Falkland Islands—or Malvinas, as they are called in Spanish—each viewed the islands as territory that had been taken from them by the other; thus each was willing to commit enormous resources—and risks—to recapturing them. In international affairs, it is vital that each actor in such a situation understand the other’s subjective view of what is at stake.`;

export const Lesson2_Question22: Lesson = {
  id: "56-2",
  title: "Question 22: Application",
  content: [
    { type: 'accordion', title: 'Read Passage (PT-113-S-1-P-4)', content: passageText },
    { type: 'h3', text: "Question 22: Application Breakdown (PT-113-S-1-P-4-Q-22)" },
    { type: 'blockquote', text: "**Question:** Suppose that a country seizes a piece of territory with great mineral wealth that is claimed by a neighboring country, with a concomitant risk of failure involving moderate but easily tolerable harm in the long run. Given the information in the passage, the author would most likely say that" },
    { type: 'options', items: [
      "(A) the country’s actions are consistent with previously accepted views of the psychology of risk-taking (Correct)",
      "(B) the new research findings indicate that the country from which the territory has been seized probably weighs the risk factors involved in the situation similarly to the way in which they are weighed by the aggressor nation",
      "(C) in spite of surface appearances to the contrary, the new research findings suggest that the objective value of the potential gain is overridden by the risks",
      "(D) the facts of the situation show that the government is motivated by factors other than objective calculation of the measurable risks and probable benefits",
      "(E) the country’s leaders most likely subjectively perceive the territory as having been taken from their country in the past"
    ]},
    { type: 'h4', text: "Analysis" },
    { type: 'paragraph', text: "This application question should be resolved by matching each choice to what the passage actually establishes. Use the opening and closing claims as scope anchors, then select the option that satisfies the stem without unsupported assumptions." },
    { type: 'callout', title: "Text Evidence", variant: "tip", text: "Anchor your reading in phrases such as 'Recent investigations into the psychology of decision making have sparked interest...' and 'In international affairs, it is vital that each actor in such...' when checking whether a choice preserves the passage's emphasis." },
    { 
      type: 'breakdown',
      labels: { title: 'Option', text: 'Analysis' },
      items: [
        { title: "(A)", text: "This is correct. The country is making a calculated gamble where the high potential gain ('great mineral wealth') seems to justify the low risk ('moderate but easily tolerable'). This aligns perfectly with the traditional economic view that 'entrepreneurs and consumers will choose a risky venture... only when the expected measurable value of the outcome is sufficiently high.' Additional check: this is strongest because it directly satisfies the stem while preserving the passage's scope and emphasis.", badge: "Correct", badgeColor: "green" },
        { title: "(B)", text: "The passage suggests the opposite. The new research on loss aversion indicates that the country that lost the territory would feel a much stronger motivation to take risks than the aggressor nation seeking a gain. They would weigh the factors very differently. Additional check: trap type is reversal/contradiction, because it flips the passage's direction or conclusion.", badge: "Incorrect", badgeColor: "red" },
        { title: "(C)", text: "The scenario contradicts this. It implies the potential gain *outweighs* the risk, not the other way around. The gain is 'great' while the risk is 'tolerable.' Additional check: trap type is reversal/contradiction, because it flips the passage's direction or conclusion.", badge: "Incorrect", badgeColor: "red" },
        { title: "(D)", text: "This is incorrect. The country's actions are actually consistent with an objective calculation of benefits versus risks, which is the hallmark of the older, traditional view. Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support.", badge: "Incorrect", badgeColor: "red" },
        { title: "(E)", text: "The scenario describes a country 'seizing' territory for its wealth, which is an act of gain. The motivation of recapturing a perceived past loss is linked to the *new* research and often involves taking much larger, not 'easily tolerable,' risks. Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support.", badge: "Incorrect", badgeColor: "red" }
      ]
    }
  ]
};
