import { Lesson } from '../../types';

const passageText = `By the time Bentham turned his interest to the subject, late in the eighteenth century, most components of modern evidence law had been assembled. Among common-law doctrines regarding evidence there were, however, principles that today are regarded as bizarre; thus, a well-established (but now abandoned) rule forbade the parties to a case from testifying. Well into the nineteenth century, even defendants in criminal cases were denied the right to testify to facts that would prove their innocence.
Although extreme in its irrationality, this proscription was in other respects quite typical of the law of evidence. Much of that law consisted of rules excluding relevant evidence, usually on some rational grounds. Hearsay evidence was generally excluded because absent persons could not be cross-examined. Yet such evidence was mechanically excluded even where out-of-court statements were both relevant and reliable, but the absent persons could not appear in court (for example, because they were dead).
The morass of evidentiary technicalities often made it unlikely that the truth would emerge in a judicial contest, no matter how expensive and protracted. Reform was frustrated both by the vested interests of lawyers and by the profession’s reverence for tradition and precedent. Bentham’s prescription was revolutionary: virtually all evidence tending to prove or disprove the issue in dispute should be admissible. Narrow exceptions were envisioned: instances in which the trouble or expense of presenting or considering proof outweighed its value, confessions to a Catholic priest, and a few other instances.
One difficulty with Bentham’s nonexclusion principle is that some kinds of evidence are inherently unreliable or misleading. Such was the argument underlying the exclusions of interested-party testimony and hearsay evidence. Bentham argued that the character of evidence should be weighed by the jury: the alternative was to prefer ignorance to knowledge. Yet some evidence, although relevant, is actually more likely to produce a false jury verdict than a true one. To use a modern example, evidence of a defendant’s past bank robberies is excluded, since the prejudicial character of the evidence substantially outweighs its value in helping the jury decide correctly. Further, in granting exclusions such as sacramental confessions, Bentham conceded that competing social interests or values might override the desire for relevant evidence. But then, why not protect conversations between social workers and their clients, or parents and children?
Despite concerns such as these, the approach underlying modern evidence law began to prevail soon after Bentham’s death: relevant evidence should be admitted unless there are clear grounds of policy for excluding it. This clear-grounds proviso allows more exclusions than Bentham would have liked, but the main thrust of the current outlook is Bentham’s own nonexclusion principle, demoted from a rule to a presumption.`;

export const Lesson1_PassageAnalysis: Lesson = {
  id: "51-1",
  title: "Passage Analysis",
  content: [
    { type: 'accordion', title: 'Read Passage', content: passageText },
    { type: 'h3', text: "Passage Analysis" },
    { type: 'paragraph', text: "The passage is a balanced look at Jeremy Bentham's big idea for legal reform. It argues his 'nonexclusion principle'—the idea that almost all evidence should be allowed in court—was brilliant and shaped modern law, but also had some serious flaws. His idea was a game-changer, even if we don't follow it perfectly today." },
    { type: 'h4', text: "Paragraph 1: The Old, Irrational System" },
    { type: 'paragraph', text: "The author starts by painting a picture of how bizarre the law was in the 18th century. The rules were so strange that people involved in a case weren't even allowed to speak to prove their own innocence." },
    { type: 'h4', text: "Paragraph 2: Rules That Hid the Truth" },
    { type: 'paragraph', text: "The second paragraph explains that the old system was full of rules that blocked good evidence. For example, hearsay was automatically excluded, even if it was reliable and the speaker was dead. These rigid rules often made it impossible to find out what really happened." },
    { type: 'h4', text: "Paragraph 3: Bentham's Radical Solution" },
    { type: 'paragraph', text: "This is where we meet the hero of the story, Jeremy Bentham. He proposed a radical fix for the broken system: his 'nonexclusion principle.' The idea was simple: let in *all* the evidence, unless there's a very good, practical reason to exclude it." },
    { type: 'h4', text: "Paragraph 4: Problems with the Solution" },
    { type: 'paragraph', text: "The author then plays devil's advocate, pointing out the weak spots in Bentham's idea. What about evidence that's really misleading, like a defendant's past crimes? Also, if you make one exception for social values (like priest confessions), where do you draw the line? The author shows Bentham's rule wasn't a perfect fix." },
    { type: 'h4', text: "Paragraph 5: Bentham's Enduring Legacy" },
    { type: 'paragraph', text: "The passage wraps up by showing that despite the problems, Bentham's core idea won. Modern evidence law starts from his basic principle: evidence should be allowed unless there's a strong reason to exclude it. It's not the absolute rule he wanted, but his thinking changed everything." }
  ]
};