import { Lesson } from '../../types';

const passageText = `In explaining the foundations of the discipline known as historical sociology—the examination of history using the methods of sociology—historical sociologist Philip Abrams argues that, while people are made by society as much as society is made by people, sociologists’ approach to the subject is usually to focus on only one of these forms of influence to the exclusion of the other. Abrams insists on the necessity for sociologists to move beyond these one-sided approaches to understand society as an entity constructed by individuals who are at the same time constructed by their society. Abrams refers to this continuous process as “structuring.”
Abrams also sees history as the result of structuring. People, both individually and as members of collectives, make history. But our making of history is itself formed and informed not only by the historical conditions we inherit from the past, but also by the prior formation of our own identities and capacities, which are shaped by what Abrams calls “contingencies”—social phenomena over which we have varying degrees of control. Contingencies include such things as the social conditions under which we come of age, the condition of our household’s economy, the ideologies available to help us make sense of our situation, and accidental circumstances. The ways in which contingencies affect our individual or group identities create a structure of forces within which we are able to act, and that partially determines the sorts of actions we are able to perform.
In Abrams’s analysis, historical structuring, like social structuring, is manifold and unremitting. To understand it, historical sociologists must extract from it certain significant episodes, or events, that their methodology can then analyze and interpret. According to Abrams, these events are points at which action and contingency meet, points that represent a cross section of the specific social and individual forces in play at a given time. At such moments, individuals stand forth as agents of history not simply because they possess a unique ability to act, but also because in them we see the force of the specific social conditions that allowed their actions to come forth. Individuals can “make their mark” on history, yet in individuals one also finds the convergence of wider social forces. In order to capture the various facets of this mutual interaction, Abrams recommends a fourfold structure to which he believes the investigations of historical sociologists should conform: first, description of the event itself; second, discussion of the social context that helped bring the event about and gave it significance; third, summary of the life history of the individual agent in the event; and fourth, analysis of the consequences of the event both for history and for the individual.`;

export const Lesson1_PassageAnalysis: Lesson = {
  id: "57-1",
  title: "Passage Analysis: Historical Sociology",
  content: [
    { type: 'accordion', title: 'Read Passage (PT-114-S-3-P-3)', content: passageText },
    { type: 'h3', text: "Passage Analysis: Historical Sociology (PT-114-S-3-P-3)" },
    { type: 'paragraph', text: "The passage explains Philip Abrams's concept of \"structuring,\" a two-way process in which individuals and social structures continuously produce one another. It then extends that model from sociology to historical explanation." },
    { type: 'paragraph', text: "Track the movement from theory to method. Paragraph 1 introduces the conceptual correction, Paragraph 2 applies it to historical agency under contingency, and Paragraph 3 converts it into a practical analytic framework for historians." },
    { type: 'hr' },
    { type: 'h4', text: "Paragraph 1: Correcting One-Sided Sociology" },
    { type: 'paragraph', text: "The first paragraph rejects models that privilege either individual agency or social determination alone. Abrams's intervention is to treat both as mutually constitutive within an ongoing process he calls structuring." },
    { type: 'paragraph', text: "Its function is conceptual: it replaces either/or explanation with reciprocal causation as the default lens." },
    { type: 'h4', text: "Paragraph 2: Historical Action Under Contingency" },
    { type: 'paragraph', text: "The second paragraph applies structuring to history. Individuals act, but the scope and form of action are shaped by contingencies such as class position, household economy, ideology, and chance." },
    { type: 'paragraph', text: "This reframes agency as situated capacity. Historical actors are neither fully autonomous nor fully determined; they operate within structured opportunity sets." },
    { type: 'h4', text: "Paragraph 3: Method for Event-Based Historical Sociology" },
    { type: 'paragraph', text: "The final paragraph converts theory into method by identifying analytically rich \"events\" where agency and contingency intersect. These moments reveal both individual action and the social forces enabling it." },
    { type: 'paragraph', text: "Abrams's four-part procedure operationalizes that goal: describe the event, specify its social context, profile the agent, and analyze consequences for both history and actor." },
    { type: 'callout', title: "Summary of the Argument", variant: "summary", text: "The passage argues that social and historical explanation requires a reciprocal model of structuring, in which people and institutions co-produce one another. It then proposes an event-centered method for analyzing how contingent social conditions and individual agency interact to generate historical outcomes." }
  ]
};
