import { Lesson } from '../../types';

const passageText = `In explaining the foundations of the discipline known as historical sociology—the examination of history using the methods of sociology—historical sociologist Philip Abrams argues that, while people are made by society as much as society is made by people, sociologists’ approach to the subject is usually to focus on only one of these forms of influence to the exclusion of the other. Abrams insists on the necessity for sociologists to move beyond these one-sided approaches to understand society as an entity constructed by individuals who are at the same time constructed by their society. Abrams refers to this continuous process as “structuring.”
Abrams also sees history as the result of structuring. People, both individually and as members of collectives, make history. But our making of history is itself formed and informed not only by the historical conditions we inherit from the past, but also by the prior formation of our own identities and capacities, which are shaped by what Abrams calls “contingencies”—social phenomena over which we have varying degrees of control. Contingencies include such things as the social conditions under which we come of age, the condition of our household’s economy, the ideologies available to help us make sense of our situation, and accidental circumstances. The ways in which contingencies affect our individual or group identities create a structure of forces within which we are able to act, and that partially determines the sorts of actions we are able to perform.
In Abrams’s analysis, historical structuring, like social structuring, is manifold and unremitting. To understand it, historical sociologists must extract from it certain significant episodes, or events, that their methodology can then analyze and interpret. According to Abrams, these events are points at which action and contingency meet, points that represent a cross section of the specific social and individual forces in play at a given time. At such moments, individuals stand forth as agents of history not simply because they possess a unique ability to act, but also because in them we see the force of the specific social conditions that allowed their actions to come forth. Individuals can “make their mark” on history, yet in individuals one also finds the convergence of wider social forces. In order to capture the various facets of this mutual interaction, Abrams recommends a fourfold structure to which he believes the investigations of historical sociologists should conform: first, description of the event itself; second, discussion of the social context that helped bring the event about and gave it significance; third, summary of the life history of the individual agent in the event; and fourth, analysis of the consequences of the event both for history and for the individual.`;

export const Lesson1_PassageAnalysis: Lesson = {
  id: "57-1",
  title: "Passage Analysis: Historical Sociology",
  content: [
    { type: 'accordion', title: 'Read Passage', content: passageText },
    { type: 'h3', text: "Passage Breakdown" },
    { type: 'paragraph', text: "This passage dives into some heady academic theory from a sociologist named Philip Abrams. The main takeaway is his argument that we can't understand society or history with a one-sided view. Instead, he proposes a two-way model where people and the world they live in are constantly shaping each other." },
    { type: 'hr' },
    { type: 'h4', text: "Paragraph 1: The Problem with Sociology & Abrams's Fix" },
    { type: 'paragraph', text: "Abrams starts by pointing out a flaw in his field. He says sociologists tend to see things as a one-way street: either people make society, or society makes people. Abrams says this is wrong. His big idea, which he calls 'structuring,' is that it's a continuous, two-way process. People build society, and society builds people, all at the same time." },
    { type: 'h4', text: "Paragraph 2: Applying 'Structuring' to History" },
    { type: 'paragraph', text: "Next, the passage shows how Abrams applies this idea to history. Sure, people 'make history,' but they don't do it in a vacuum. Abrams argues that our ability to act is limited by the world we're born into—our 'contingencies.' These are things like our social class, our family's wealth, the political ideas around us, and even just plain luck. These contingencies shape who we are and what actions are possible for us." },
    { type: 'h4', text: "Paragraph 3: A 'How-To' Guide for Historians" },
    { type: 'paragraph', text: "The final paragraph gets practical. To understand this complex process, Abrams says historians should focus on specific, significant 'events' where an individual's action and their social circumstances (contingencies) collide. He argues a great historical figure isn't great in isolation; they are great because they perfectly embody the social forces that made their actions possible. To analyze these moments, he lays out a four-step method: describe the event, explain the social context, detail the life of the person involved, and analyze the consequences." },
    { type: 'callout', title: "Summary of the Argument", variant: "summary", text: "The passage explains sociologist Philip Abrams's theory of 'structuring'—a two-way process where people shape society and society shapes people. Abrams applies this to history, arguing that individuals can only 'make history' within the limits set by their social conditions ('contingencies'). To analyze this, he proposes a four-step method for studying key historical events where individual action and broader social forces intersect." }
  ]
};