import { Lesson } from '../../types';

const passageText = `In explaining the foundations of the discipline known as historical sociology—the examination of history using the methods of sociology—historical sociologist Philip Abrams argues that, while people are made by society as much as society is made by people, sociologists’ approach to the subject is usually to focus on only one of these forms of influence to the exclusion of the other. Abrams insists on the necessity for sociologists to move beyond these one-sided approaches to understand society as an entity constructed by individuals who are at the same time constructed by their society. Abrams refers to this continuous process as “structuring.”
Abrams also sees history as the result of structuring. People, both individually and as members of collectives, make history. But our making of history is itself formed and informed not only by the historical conditions we inherit from the past, but also by the prior formation of our own identities and capacities, which are shaped by what Abrams calls “contingencies”—social phenomena over which we have varying degrees of control. Contingencies include such things as the social conditions under which we come of age, the condition of our household’s economy, the ideologies available to help us make sense of our situation, and accidental circumstances. The ways in which contingencies affect our individual or group identities create a structure of forces within which we are able to act, and that partially determines the sorts of actions we are able to perform.
In Abrams’s analysis, historical structuring, like social structuring, is manifold and unremitting. To understand it, historical sociologists must extract from it certain significant episodes, or events, that their methodology can then analyze and interpret. According to Abrams, these events are points at which action and contingency meet, points that represent a cross section of the specific social and individual forces in play at a given time. At such moments, individuals stand forth as agents of history not simply because they possess a unique ability to act, but also because in them we see the force of the specific social conditions that allowed their actions to come forth. Individuals can “make their mark” on history, yet in individuals one also finds the convergence of wider social forces. In order to capture the various facets of this mutual interaction, Abrams recommends a fourfold structure to which he believes the investigations of historical sociologists should conform: first, description of the event itself; second, discussion of the social context that helped bring the event about and gave it significance; third, summary of the life history of the individual agent in the event; and fourth, analysis of the consequences of the event both for history and for the individual.`;

export const Lesson3_Question16: Lesson = {
  id: "57-3",
  title: "Question 16: Inference",
  content: [
    { type: 'accordion', title: 'Read Passage (PT-114-S-3-P-3)', content: passageText },
    { type: 'h3', text: "Question 16: Inference Breakdown (PT-114-S-3-P-3-Q-16)" },
    { type: 'blockquote', text: "**Question:** Given the passage’s argument, which one of the following sentences most logically completes the last paragraph?" },
    { type: 'options', items: [
      "(A) Only if they adhere to this structure, Abrams believes, can historical sociologists conclude with any certainty that the events that constitute the historical record are influenced by the actions of individuals.",
      "(B) Only if they adhere to this structure, Abrams believes, will historical sociologists be able to counter the standard sociological assumption that there is very little connection between history and individual agency.",
      "(C) Unless they can agree to adhere to this structure, Abrams believes, historical sociologists risk having their discipline treated as little more than an interesting but ultimately indefensible adjunct to history and sociology.",
      "(D) By adhering to this structure, Abrams believes, historical sociologists can shed light on issues that traditional sociologists have chosen to ignore in their one-sided approaches to the formation of societies.",
      "(E) By adhering to this structure, Abrams believes, historical sociologists will be able to better portray the complex connections between human agency and history. (Correct)"
    ]},
    { type: 'h4', text: "Analysis" },
    { type: 'paragraph', text: "This inference question should be resolved by matching each choice to what the passage actually establishes. Use the opening and closing claims as scope anchors, then select the option that satisfies the stem without unsupported assumptions." },
    { type: 'callout', title: "Text Evidence", variant: "tip", text: "Anchor your reading in phrases such as 'In explaining the foundations of the discipline known as historical sociology—the...' and 'In order to capture the various facets of this mutual interaction,...' when checking whether a choice preserves the passage's emphasis." },
    { 
      type: 'breakdown',
      labels: { title: 'Option', text: 'Analysis' },
      items: [
        { title: "(A)", text: "This is too narrow. It only mentions the influence of individuals on events, ignoring the other half of Abrams's 'mutual interaction'—the influence of society on individuals. Additional check: trap type is too narrow, since it leaves out a required part of the passage's claim.", badge: "Incorrect", badgeColor: "red" },
        { title: "(B)", text: "This misrepresents the problem. The passage states that sociologists take a 'one-sided' approach, not that they see 'very little connection' between individuals and history. Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support.", badge: "Incorrect", badgeColor: "red" },
        { title: "(C)", text: "The passage discusses Abrams's theory, not the professional reputation or academic standing of historical sociology. This is out of scope. Additional check: trap type is out of scope, because it shifts away from the stem's target issue.", badge: "Incorrect", badgeColor: "red" },
        { title: "(D)", text: "This is a plausible goal, but it's not the primary purpose of the four-part method. The method's explicit goal is to capture the 'mutual interaction' in history, not just to critique other sociologists. Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support.", badge: "Incorrect", badgeColor: "red" },
        { title: "(E)", text: "This choice perfectly summarizes the purpose of Abrams's method as described in the passage. The entire passage builds to this idea of a 'mutual interaction' between individuals making history ('human agency') and the social forces that shape them ('history'). The four-part structure is designed to analyze and 'portray' these 'complex connections.' Additional check: this is strongest because it directly satisfies the stem while preserving the passage's scope and emphasis.", badge: "Correct", badgeColor: "green" }
      ]
    }
  ]
};
