import { Lesson } from '../../types';

export const Lesson12_ReferenceGuide: Lesson = {
  id: "5-12",
  title: "Reference Guide",
  content: [
    { type: 'h1', text: 'MODULE 5: Flaw Reference Guide' },
    { type: 'paragraph', text: "A condensed reference for every concept, flaw type, method, trap, and strategy in Flaw questions. Print this or bookmark it for review before test day." },
    { type: 'hr' },

    { type: 'h3', text: 'The Goal: Find the Logical Gap' },
    { type: 'paragraph', text: "Your job is not to challenge the truth of the premises, but to evaluate the reasoning. **Accept the premises as true** and identify the specific logical error — the unwarranted assumption or structural failure — that prevents the premises from proving the conclusion. The flaw is always located in the *inference*, never in the facts themselves." },
    { type: 'hr' },

    { type: 'h3', text: 'The 4-Step Method' },
    { type: 'process', steps: [
      "**Step 1 — Deconstruct the Argument:** Identify the Main Conclusion and the Premises. Note any background facts, opposing viewpoints, or intermediate conclusions. Separate the structural components before evaluating the logic.",
      "**Step 2 — Find the Logical Gap:** Ask: **\"Why do these premises NOT guarantee this conclusion?\"** Accept the premises as true but imagine the conclusion is false. What overlooked possibility, unjustified assumption, or structural error makes this possible? This is the gap.",
      "**Step 3 — Prephrase the Flaw:** Describe the error in your own words at a moderate level of abstraction — specific enough to match one answer choice, abstract enough to recognize formal descriptions. Use the Mental Flaw Checklist to categorize: Is it causal? Conditional? Statistical? Scope shift? Name the category before reading the choices.",
      "**Step 4 — Evaluate the Answers:** Scan the choices for the one that matches your prephrase. For each contender, use the **Substitution Technique**: replace abstract phrases with the stimulus's specific content. Verify that every clause in the answer accurately describes the argument. Eliminate answers that misdescribe the conclusion, the premises, or the direction of the error.",
    ]},
    { type: 'hr' },

    { type: 'h3', text: 'Complete Flaw Taxonomy' },
    { type: 'paragraph', text: "Every major flaw type tested on the LSAT, organized by category. Study this table until you can recite the categories from memory:" },
    { type: 'table', headers: ['Category', 'Flaw Type', 'Core Error', 'LSAT Answer Choice Language'], rows: [
      ['**Causal**', 'Correlation → Causation', 'Assumes co-occurrence proves causation', '"infers a causal relationship from a mere correlation"'],
      ['**Causal**', 'Reverse Causation', 'Gets the causal direction backward', '"fails to consider that the cause and effect may be reversed"'],
      ['**Causal**', 'Third Factor / Common Cause', 'Ignores a third factor that explains both', '"fails to establish that the phenomena are not both effects of some other factor"'],
      ['**Conditional**', 'Mistaken Reversal (Affirming Consequent)', 'From "If A then B" and B, concludes A', '"confuses a sufficient condition with a necessary condition"'],
      ['**Conditional**', 'Mistaken Negation (Denying Antecedent)', 'From "If A then B" and ~A, concludes ~B', '"assumes the absence of a sufficient condition guarantees the absence of the result"'],
      ['**Conditional**', 'Necessary vs. Sufficient Confusion', 'Treats a requirement as a guarantee (or vice versa)', '"takes a condition necessary for a result as sufficient for that result"'],
      ['**Statistical**', 'Unrepresentative Sample', 'Generalizes from biased or too-small sample', '"generalizes from a sample that is unlikely to be representative"'],
      ['**Statistical**', 'Numbers vs. Percentages', 'Confuses raw numbers with rates or proportions', '"confuses absolute numbers with proportional rates"'],
      ['**Statistical**', 'Base Rate Neglect', 'Ignores overall frequency when interpreting statistics', '"fails to consider the overall incidence in the population"'],
      ['**Scope Shift**', 'Part → Whole (Composition)', 'Properties of parts assumed for the whole', '"assumes what is true of each member is true of the group as a whole"'],
      ['**Scope Shift**', 'Whole → Part (Division)', 'Properties of whole assumed for each part', '"assumes what is true of the whole is true of each part"'],
      ['**Scope Shift**', 'Some → All (Hasty Generalization)', 'Evidence about some → conclusion about all', '"generalizes on the basis of what could be exceptional cases"'],
      ['**Scope Shift**', 'Possibility → Certainty', 'Treats what could happen as what will happen', '"treats a possibility as a certainty"'],
      ['**Other**', 'Ad Hominem / Source Attack', 'Attacks the person instead of the argument', '"rejects a claim by attacking the person who made it"'],
      ['**Other**', 'Straw Man', 'Misrepresents opponent\'s position before attacking it', '"distorts the position it seeks to criticize"'],
      ['**Other**', 'Appeal to Ignorance', 'Absence of proof ≠ proof of absence', '"takes the absence of evidence as evidence of absence"'],
      ['**Other**', 'False Dichotomy', 'Only two options presented when more exist', '"treats two options as though they are the only possibilities"'],
      ['**Other**', 'Circular Reasoning', 'Conclusion restated as a premise', '"assumes what it sets out to prove"'],
      ['**Other**', 'Equivocation', 'Key term shifts meaning between premise and conclusion', '"relies on an ambiguity in a key term"'],
      ['**Other**', 'Appeal to Authority', 'Relies on irrelevant or unqualified authority', '"cites an authority whose expertise is not relevant to the issue"'],
    ]},
    { type: 'hr' },

    { type: 'h3', text: 'Valid vs. Invalid Conditional Inferences' },
    { type: 'paragraph', text: "From any conditional statement \"If A, then B\" (A → B), exactly two inferences are valid and two are invalid:" },
    { type: 'table', headers: ['Inference Name', 'Form', 'Valid?', 'Example (from \"If it rains, the ground is wet\")'], rows: [
      ['**Modus Ponens** (Direct Application)', 'A is true → B is true', '✅ Valid', '"It is raining → The ground is wet"'],
      ['**Modus Tollens** (Contrapositive)', '~B → ~A', '✅ Valid', '"The ground is NOT wet → It is NOT raining"'],
      ['**Affirming the Consequent** (Mistaken Reversal)', 'B → A', '❌ Invalid', '"The ground IS wet → It IS raining" (could be a sprinkler)'],
      ['**Denying the Antecedent** (Mistaken Negation)', '~A → ~B', '❌ Invalid', '"It is NOT raining → Ground is NOT wet" (could be wet from other causes)'],
    ]},
    { type: 'hr' },

    { type: 'h3', text: 'LSAT Language Decoder' },
    { type: 'paragraph', text: "The LSAT describes flaws using dense, formal language. This decoder maps the most common abstract phrases to the specific flaw types they describe:" },
    { type: 'table', headers: ['Abstract Language in Answer Choice', 'Flaw Type (Plain English)'], rows: [
      ['"treats a condition that is sufficient for a result as necessary for that result"', 'Mistaken Reversal — sufficient ≠ necessary'],
      ['"takes a condition necessary for a result as sufficient for that result"', 'Necessary → Sufficient confusion'],
      ['"confuses a condition\'s being required with the condition\'s being sufficient"', 'Nec. vs. Suff. (the Straw Man variant)'],
      ['"presumes that because two things are correlated, one must be the cause of the other"', 'Correlation → Causation'],
      ['"fails to consider that the presumed cause may actually be the effect"', 'Reverse Causation'],
      ['"overlooks a common cause that could explain both phenomena"', 'Third Factor / Common Cause'],
      ['"draws a conclusion about the population based on a sample unlikely to be representative"', 'Unrepresentative Sample'],
      ['"confuses a change in total numbers with a change in proportions"', 'Numbers vs. Percentages'],
      ['"assumes what is true of each part is true of the whole"', 'Composition (Part → Whole)'],
      ['"assumes what is true of the whole is true of each part"', 'Division (Whole → Part)'],
      ['"treats a possibility as a certainty"', 'Possibility → Certainty scope shift'],
      ['"treats a probability as though it were a certainty"', 'Probability → Certainty scope shift'],
      ['"rejects a claim based on the source rather than its merits"', 'Ad Hominem / Source Attack'],
      ['"distorts or misrepresents the position it seeks to refute"', 'Straw Man'],
      ['"takes the absence of evidence for a claim as evidence against it"', 'Appeal to Ignorance'],
      ['"treats two options as the only possibilities when others exist"', 'False Dichotomy'],
      ['"its conclusion is merely a restatement of a claim in its premises"', 'Circular Reasoning'],
      ['"relies on an ambiguity in a key term"', 'Equivocation'],
      ['"presumes that trying to bring about a condition that ensures an end is the most likely way to achieve that end"', 'Strategy vs. Certainty confusion'],
      ['"confuses a sufficient condition with a required condition" (in surveys)', 'Quantitative-Conditional flaw (\"if\" vs. \"only if\")'],
    ]},
    { type: 'hr' },

    { type: 'h3', text: 'Common Traps: Complete Breakdown' },
    { type: 'paragraph', text: "Flaw questions have predictable trap answer types. Learning to spot these saves time and prevents errors:" },
    { type: 'breakdown', labels: { title: 'Trap', text: 'How It Works & How to Avoid It' }, items: [
      { title: 'The "Out of Scope" Trap', text: "**How it works:** The answer raises a valid real-world concern that seems related to the topic but doesn't address the *logical connection* between the premises and the conclusion.\n\n**How to avoid it:** Check: does this point actually affect the *reasoning structure*? If removing this concern wouldn't fix the argument's logic, it's out of scope.", badge: 'Very Common', badgeColor: 'red' },
      { title: 'The "Wrong Flaw" Trap', text: "**How it works:** The answer perfectly describes a classic logical fallacy using familiar language — but the argument *didn't actually commit that specific error.* The flaw type is real; it's just not present in this stimulus.\n\n**How to avoid it:** Don't just recognize the flaw name. Verify that the argument actually committed this error by pointing to the exact sentences where it occurs.", badge: 'Very Common', badgeColor: 'red' },
      { title: 'The "Premise Attack" Trap', text: "**How it works:** The answer questions the truth or support for a premise, saying things like \"fails to establish that [premise] is true\" or \"relies on a claim for which no support is provided.\"\n\n**How to avoid it:** Accept the premises as true. The flaw is in the *reasoning from* the premises, not the premises themselves. Answers that attack the starting point miss the actual reasoning error.", badge: 'Very Common', badgeColor: 'red' },
      { title: 'The "Reverse Logic" Trap', text: "**How it works:** The answer describes the right *family* of flaw but reverses the direction. If the stimulus commits a Mistaken Reversal, the trap describes a Mistaken Negation. If it's a Composition flaw, the trap describes Division.\n\n**How to avoid it:** Diagram the logic carefully. Confirm the direction of the error before selecting. For conditional flaws, verify: is it B→A (reversal) or ~A→~B (negation)?", badge: 'Common', badgeColor: 'red' },
      { title: 'The "Describes Method, Not Flaw" Trap', text: "**How it works:** The answer accurately describes *what the argument does* without explaining *why it's wrong*. It reads like a Method of Reasoning answer — a neutral description rather than an evaluative critique.\n\n**How to avoid it:** The correct Flaw answer must identify an *error*. If the answer sounds like it could be true of a valid argument, it's describing the method, not the flaw.", badge: 'Common', badgeColor: 'red' },
      { title: 'The "Opposite Flaw Direction" Trap (Causal)', text: "**How it works:** If the stimulus gets the causal direction wrong (A→B when it should be B→A), the trap answer accuses it of a different causal error entirely (like ignoring a third factor). Both are causal flaws, but only one matches the specific argument.\n\n**How to avoid it:** Identify the *specific* causal error: Is it correlation→causation? Reverse causation? Third factor? Each has distinct answer-choice language.", badge: 'Moderate', badgeColor: 'slate' },
      { title: 'The "Too Broad" Trap', text: "**How it works:** The answer describes the flaw in such general terms that it could apply to virtually any flawed argument: \"fails to consider all relevant evidence\" or \"draws a hasty conclusion.\"\n\n**How to avoid it:** The correct answer is *specifically* accurate, not just generally true. If it could describe any flawed argument, it's too vague.", badge: 'Moderate', badgeColor: 'slate' },
    ]},
    { type: 'hr' },

    { type: 'h3', text: 'Quick Identification Flowchart' },
    { type: 'paragraph', text: "Use this decision process to rapidly narrow down the flaw type when reading a stimulus:" },
    { type: 'process', title: 'Flaw Identification Steps', steps: [
      '**Does the conclusion claim CAUSATION?** ("causes," "leads to," "results in," "stimulates") → Check for **Causal Flaw** (correlation→causation, reverse causation, third factor).',
      '**Does the argument contain IF/THEN, ALL, ONLY IF, MUST, or REQUIRES?** → Check for **Conditional Logic Flaw** (mistaken reversal, mistaken negation, necessary vs. sufficient confusion).',
      '**Does the argument cite a STUDY, SURVEY, POLL, or STATISTIC?** → Check for **Statistical Flaw** (unrepresentative sample, numbers vs. percentages, base rate neglect). If the survey uses "if" or "only if," check for the **Quantitative-Conditional Flaw**.',
      '**Does the conclusion\'s scope EXCEED the evidence\'s scope?** (some→all, part→whole, past→future, possible→certain) → Check for **Scope Shift Flaw** (composition, division, hasty generalization, certainty flaw).',
      '**Does the argument ATTACK A PERSON rather than address a claim?** → Check for **Ad Hominem** or **Source Attack**.',
      '**Does the argument MISREPRESENT someone\'s position before attacking it?** → Check for **Straw Man** (often combined with Nec. vs. Suff. confusion).',
      '**Does the argument claim something must be true because it HASN\'T BEEN DISPROVEN?** → Check for **Appeal to Ignorance**.',
      '**Does the argument present ONLY TWO OPTIONS?** → Check for **False Dichotomy**.',
      '**Does a KEY TERM seem to shift meaning between premise and conclusion?** → Check for **Equivocation**.',
      '**Does the argument seem to RESTATE its conclusion as evidence?** → Check for **Circular Reasoning**.',
      '**Does the argument confuse a GUARANTEED outcome with the MOST LIKELY path?** → Check for **Strategy vs. Certainty** confusion.',
    ]},
    { type: 'hr' },

    { type: 'h3', text: 'The Mental Flaw Checklist (Speed Version)' },
    { type: 'paragraph', text: "When you've found the gap but aren't sure which category it fits, run through this rapid checklist:" },
    { type: 'list', ordered: true, items: [
      "**Causation?** Correlation treated as causation? Reverse causation? Third factor ignored?",
      "**Conditional?** Arrow reversed (B→A instead of A→B)? Both sides negated (~A→~B)? Necessary treated as sufficient (or vice versa)?",
      "**Statistical?** Biased sample? Numbers confused with percentages? Base rate ignored?",
      "**Scope Shift?** Part→whole? Whole→part? Some→all? Possible→certain? Past→future?",
      "**Source Attack?** Person attacked instead of argument?",
      "**Straw Man?** Opponent's position misrepresented?",
      "**Ignorance?** Absence of proof treated as proof of absence?",
      "**Dichotomy?** Only two options when more exist?",
      "**Equivocation?** Key term shifts meaning?",
      "**Circular?** Conclusion restated in premises?",
    ]},
    { type: 'hr' },

    { type: 'h3', text: 'Answer Choice Evaluation Strategies' },
    { type: 'breakdown', labels: { title: 'Strategy', text: 'How It Works' }, items: [
      { title: 'The Substitution Technique', text: "Replace every abstract phrase in the answer choice with the specific content from the stimulus. \"A condition sufficient for a result\" becomes \"unplugging the mouse.\" \"The result\" becomes \"the software becoming unusable.\" Read the translated version and check if it matches the actual argument.", badge: 'Essential', badgeColor: 'green' },
      { title: 'The Direction Check', text: "For conditional and causal flaws, verify the direction. Does the answer say the argument confuses sufficient→necessary or necessary→sufficient? Does it say cause→effect or effect→cause? The wrong direction is the most common trap on hard questions.", badge: 'Essential', badgeColor: 'green' },
      { title: 'The \"Fix It\" Test', text: "Ask: if the flaw described in this answer were corrected, would the argument become substantially stronger? If fixing this problem wouldn't help the argument, the answer probably doesn't describe the core flaw.", badge: 'Useful', badgeColor: 'blue' },
      { title: 'The Every-Clause Verification', text: "Many wrong answers contain two clauses connected by \"and\" or \"by.\" One clause is accurate, the other is wrong. Verify *every* clause independently against the stimulus. Both must be accurate for the answer to be correct.", badge: 'Useful', badgeColor: 'blue' },
      { title: 'Elimination by Flaw Family', text: "If you can confidently identify the *family* of the flaw (causal, conditional, statistical, etc.), immediately eliminate all answers describing a different family. This typically removes 2–3 answers before detailed analysis.", badge: 'Speed', badgeColor: 'slate' },
    ]},
    { type: 'hr' },

    { type: 'h3', text: 'Conditional Language Quick Reference' },
    { type: 'paragraph', text: "Conditional logic appears in many disguises. Use this reference to translate everyday language into formal conditionals:" },
    { type: 'table', headers: ['Natural Language', 'Formal Translation', 'Notes'], rows: [
      ['"If A, then B"', 'A → B', 'A is sufficient for B'],
      ['"All A are B"', 'A → B', 'Same as "If A, then B"'],
      ['"Every A is B"', 'A → B', 'Universal = conditional'],
      ['"A only if B"', 'A → B', 'B is necessary for A'],
      ['"Only B are A"', 'A → B', '"Only" introduces necessary condition'],
      ['"A requires B" / "B is required for A"', 'A → B', 'B is necessary'],
      ['"A is sufficient for B" / "A guarantees B"', 'A → B', 'A is sufficient'],
      ['"Unless B, A" / "A unless B"', '~B → A', '"Unless" = "If not"'],
      ['"No A are B"', 'A → ~B', 'Universal negative'],
      ['"A if B"', 'B → A', 'B is sufficient for A (note direction!)'],
      ['"A if and only if B"', 'A ↔ B', 'Biconditional: both directions valid'],
    ]},
    { type: 'hr' },

    { type: 'callout', variant: 'summary', title: 'Test Day Checklist', text: "Before selecting your answer on any Flaw question:\n\n**1.** Can you state the **Main Conclusion** in your own words?\n**2.** Can you identify the **Premises** supporting that conclusion?\n**3.** Can you describe the **Logical Gap** — why the premises don't guarantee the conclusion?\n**4.** Can you **name the flaw category** (causal, conditional, statistical, scope shift, etc.)?\n**5.** Have you **prephrased** the flaw before reading the answer choices?\n**6.** Does your chosen answer accurately describe the **specific error** (not just a general weakness)?\n**7.** Have you verified the **direction** of the error (for conditional and causal flaws)?\n**8.** Have you used the **Substitution Technique** to confirm every abstract phrase matches the stimulus?\n**9.** Have you checked for the **top 3 traps** — Wrong Flaw, Premise Attack, and Reverse Logic?\n**10.** If stuck between two answers, have you applied the **\"Fix It\" Test** to determine which describes the core error?\n\n**Time Budget:** 1:30–2:00 per question. If you can prephrase the flaw within 30 seconds, you're on pace." },
  ]
};
