import { Lesson } from '../../types';

const passageText = `As the twentieth century draws to a close, we are learning to see the extent to which accounts and definitions of cultures are influenced by human biases and purposes, benevolent in what they include, incorporate, and validate, less so in what they exclude and demote. A number of recent studies have argued that the anxieties and agendas of the present exert an extraordinary influence on the national identities we construct from the cultural past. For example, Greek civilization was known originally to have had roots in Egyptian and various other African and Eastern cultures, but some current scholars charge that its identity was revised during the course of the nineteenth century to support an image of European cultural dominance—its African and other cultural influences either actively purged or hidden from view by European scholars. Because ancient Greek writers themselves openly acknowledged their culture’s hybrid past, nineteenth-century European commentators habitually passed over these acknowledgments without comment.

Another example is the use of “tradition” to determine national identity. Images of European authority over other cultures were shaped and reinforced during the nineteenth century, through the manufacture and reinterpretation of rituals, ceremonies, and traditions. At a time when many of the institutions that had helped maintain imperial societies were beginning to recede in influence, and when the pressures of administering numerous overseas territories and large new domestic constituencies mounted, the ruling elites of Europe felt the clear need to project their power backward in time, giving it a legitimacy that only longevity could impart. Thus in 1876, Queen Victoria of England was declared empress of India and was celebrated in numerous “traditional” jamborees, as if her rule were not mainly a matter of recent edict but of age-old custom.

Similar constructions have also been made by native cultures about their precolonial past, as in the case of Algeria during its war of independence from France, when decolonization encouraged Algerians to create idealized images of what they believed their culture to have been prior to French occupation. This strategy is at work in what many revolutionary poets say and write during wars of independence elsewhere, giving their adherents something to revive and admire.

Though for the most part colonized societies have won their independence, in many cultures the imperial attitudes of uniqueness and superiority underlying colonial conquest remain. There is in all nationally defined cultures an aspiration to sovereignty and dominance that expresses itself in definitions of cultural identity. At the same time, paradoxically, we have never been as aware as we are now of the fact that historical and cultural experiences partake of many social and cultural domains and even cross national boundaries, despite the claims to the contrary made by purveyors of nationalist dogma. Far from being unitary, monolithic, or autonomous, cultures actually include more “foreign” elements than they consciously exclude.`;

export const Lesson2_Question14: Lesson = {
  id: "41-2",
  title: "Question 14: Main Point",
  content: [
    { type: 'accordion', title: 'Read Passage', content: passageText },
    { type: 'h3', text: "Question Breakdown: PT-128-S-1-P-3-Q-14" },
    { type: 'blockquote', text: "**Question:** Which one of the following statements most accurately expresses the main point of the passage?" },
    { type: 'options', items: [
      "(A) Either by ignoring a native culture’s own self-understanding or by substituting fabricated traditions and rituals, imperial societies often obscure the heterogeneous cultures of the peoples they colonize. [11.0%]",
      "(B) Attempts to reconstruct a native, precolonial culture by members of decolonized societies are essentially no different from European colonial creation of traditions and rituals to validate their authority. [8.0%]",
      "(C) In attempting to impose a monolithic culture on the peoples they colonize, imperial societies adopt artifices very similar to the tactics employed by revisionist historians of ancient Greek culture. [3.0%]",
      "(D) While most colonized societies have regained their independence, they retain trappings of imperial culture that will need to be discarded if they are to regain the traditions of their past. [3.0%]",
      "(E) Despite nationalistic creation of images of cultures as unified and monolithic, we now more clearly understand the extent to which cultures are in fact made up of heterogeneous elements. [76.0%] (Correct)"
    ]},
    { type: 'paragraph', text: "This is a main point question asking for the statement that best encapsulates the author's entire argument. A strong answer must account for the initial thesis about present-day bias, the various examples provided (both colonial and native), and the final conclusion about the paradoxical nature of cultural identity." },
    { type: 'paragraph', text: "The author's argument develops from the premise that cultures are defined based on present needs, leading various groups to construct images of a pure, monolithic past. The author provides examples from European imperialists, revisionist historians of Greece, and Algerian revolutionaries to show how widespread this tendency is. The passage culminates in a final, crucial point: despite these nationalistic constructions, we are now more aware that cultures are, in reality, heterogeneous and interconnected." },
    { type: 'paragraph', text: "A good main point answer must capture both this process of artificial construction and the concluding realization of cultural hybridity." },
    { 
      type: 'breakdown',
      labels: { title: 'Option', text: 'Analysis' },
      items: [
        { title: "(A) Either by ignoring a native culture’s own self-understanding or by substituting fabricated traditions and rituals, imperial societies often obscure the heterogeneous cultures of the peoples they colonize.", text: "This statement is too narrow. While true according to the passage, it only focuses on the actions of \"imperial societies.\" This ignores the other key examples, such as the revision of Greek history and the \"similar constructions\" made by native cultures like Algeria. The main point must be broad enough to cover all the evidence.", badge: "Incorrect", badgeColor: "red" },
        { title: "(B) Attempts to reconstruct a native, precolonial culture by members of decolonized societies are essentially no different from European colonial creation of traditions and rituals to validate their authority.", text: "This is also too narrow. It correctly identifies a parallel the author draws between two examples but fails to state the overarching thesis that these examples are meant to support. It's a supporting comparison, not the main point of the entire passage.", badge: "Incorrect", badgeColor: "red" },
        { title: "(C) In attempting to impose a monolithic culture on the peoples they colonize, imperial societies adopt artifices very similar to the tactics employed by revisionist historians of ancient Greek culture.", text: "Like choice (B), this correctly connects two of the author's examples but misses the larger argument that encompasses all the examples and the final conclusion about cultural hybridity.", badge: "Incorrect", badgeColor: "red" },
        { title: "(D) While most colonized societies have regained their independence, they retain trappings of imperial culture that will need to be discarded if they are to regain the traditions of their past.", text: "This is incorrect because the author's tone is descriptive, not prescriptive. The passage analyzes *how* cultures are constructed but does not make recommendations about what societies \"will need to do.\"", badge: "Incorrect", badgeColor: "red" },
        { title: "(E) Despite nationalistic creation of images of cultures as unified and monolithic, we now more clearly understand the extent to which cultures are in fact made up of heterogeneous elements.", text: "This choice effectively summarizes the entire arc of the author's argument. It addresses the central phenomenon—the \"nationalistic creation of images of cultures as unified and monolithic\" (which covers all the examples)—and incorporates the author's final, paradoxical conclusion that \"we now more clearly understand\" that cultures are actually \"heterogeneous.\" It captures both the problem and the modern awareness of it.", badge: "Correct", badgeColor: "green" }
      ]
    }
  ]
};
