import { Lesson } from '../../types';

const passageText = `As the twentieth century draws to a close, we are learning to see the extent to which accounts and definitions of cultures are influenced by human biases and purposes, benevolent in what they include, incorporate, and validate, less so in what they exclude and demote. A number of recent studies have argued that the anxieties and agendas of the present exert an extraordinary influence on the national identities we construct from the cultural past. For example, Greek civilization was known originally to have had roots in Egyptian and various other African and Eastern cultures, but some current scholars charge that its identity was revised during the course of the nineteenth century to support an image of European cultural dominance—its African and other cultural influences either actively purged or hidden from view by European scholars. Because ancient Greek writers themselves openly acknowledged their culture’s hybrid past, nineteenth-century European commentators habitually passed over these acknowledgments without comment.

Another example is the use of “tradition” to determine national identity. Images of European authority over other cultures were shaped and reinforced during the nineteenth century, through the manufacture and reinterpretation of rituals, ceremonies, and traditions. At a time when many of the institutions that had helped maintain imperial societies were beginning to recede in influence, and when the pressures of administering numerous overseas territories and large new domestic constituencies mounted, the ruling elites of Europe felt the clear need to project their power backward in time, giving it a legitimacy that only longevity could impart. Thus in 1876, Queen Victoria of England was declared empress of India and was celebrated in numerous “traditional” jamborees, as if her rule were not mainly a matter of recent edict but of age-old custom.

Similar constructions have also been made by native cultures about their precolonial past, as in the case of Algeria during its war of independence from France, when decolonization encouraged Algerians to create idealized images of what they believed their culture to have been prior to French occupation. This strategy is at work in what many revolutionary poets say and write during wars of independence elsewhere, giving their adherents something to revive and admire.

Though for the most part colonized societies have won their independence, in many cultures the imperial attitudes of uniqueness and superiority underlying colonial conquest remain. There is in all nationally defined cultures an aspiration to sovereignty and dominance that expresses itself in definitions of cultural identity. At the same time, paradoxically, we have never been as aware as we are now of the fact that historical and cultural experiences partake of many social and cultural domains and even cross national boundaries, despite the claims to the contrary made by purveyors of nationalist dogma. Far from being unitary, monolithic, or autonomous, cultures actually include more “foreign” elements than they consciously exclude.`;

export const Lesson1_PassageAnalysis: Lesson = {
  id: "41-1",
  title: "Passage Analysis",
  content: [
    { type: 'accordion', title: 'Read Passage', content: passageText },
    { type: 'h3', text: "Passage Analysis" },
    { type: 'h4', text: "Paragraph 1: The Problem of Cultural Definitions and Present Bias" },
    { type: 'paragraph', text: "The first paragraph introduces the central theme: definitions of cultures are shaped by human biases and contemporary purposes. It argues that present-day anxieties and agendas strongly influence the construction of national identities from the past. The primary example is the revision of ancient Greek civilization's identity. The author notes that its known roots in Egyptian, African, and Eastern cultures were downplayed or purged by nineteenth-century European scholars to support a narrative of European cultural dominance. This was done despite the fact that ancient Greek writers themselves had acknowledged their culture's hybrid origins." },
    { type: 'h4', text: 'Paragraph 2: "Tradition" as a Tool for Power' },
    { type: 'paragraph', text: "This paragraph expands on the theme by focusing on the concept of \"tradition\" as a tool for shaping national identity and reinforcing authority. It provides the example of nineteenth-century European imperial powers, who, facing administrative pressures, manufactured or reinterpreted rituals to project their power backward in time. This created a false sense of historical legitimacy. The specific case cited is Queen Victoria's 1876 declaration as empress of India, which was celebrated with newly created \"traditional\" jamborees to make her rule appear as an age-old custom rather than a recent decree." },
    { type: 'h4', text: "Paragraph 3: Native Cultures Creating Idealized Pasts" },
    { type: 'paragraph', text: "The third paragraph demonstrates that this process of constructing an idealized past is not unique to colonial powers. It presents a parallel case from a native culture: Algeria during its war of independence from France. The decolonization movement encouraged Algerians to create idealized images of their precolonial culture. The author notes this is a common strategy for revolutionary movements, as it provides adherents with a noble heritage to revive and admire." },
    { type: 'h4', text: "Paragraph 4: The Paradox of Sovereignty and Interconnectedness" },
    { type: 'paragraph', text: "The final paragraph synthesizes the argument and introduces a modern paradox. It observes that while the imperial attitude of cultural superiority persists and all national cultures aspire to sovereignty, there is a growing contemporary awareness of cultural interconnectedness. Historical and cultural experiences are now understood to cross national boundaries, contradicting the claims of \"nationalist dogma.\" The passage concludes that cultures are not unitary or autonomous but are, in fact, composed of more \"foreign\" elements than they consciously exclude." },
    { type: 'callout', title: "Summary", variant: "summary", text: "• **The Influence of the Present on the Past:** The passage's central argument is that our understanding of cultures is not objective but is heavily influenced by present-day biases and agendas.\n• **Manufactured Tradition and Identity:** Both colonial powers (e.g., nineteenth-century Europe) and decolonizing societies (e.g., Algeria) construct or reinterpret traditions and historical narratives to legitimize power or create idealized national identities.\n• **The Paradox of Culture:** Despite nationalistic efforts to create images of pure, monolithic cultures, there is a growing modern understanding that all cultures are inherently heterogeneous, interconnected, and composed of \"foreign\" elements." }
  ]
};
