import { Lesson } from '../../types';

const passageText = `What it means to “explain” something in science often comes down to the application of mathematics. Some thinkers hold that mathematics is a kind of language—a systematic contrivance of signs, the criteria for the authority of which are internal coherence, elegance, and depth. The application of such a highly artificial system to the physical world, they claim, results in the creation of a kind of statement about the world. Accordingly, what matters in the sciences is finding a mathematical concept that attempts, as other language does, to accurately describe the functioning of some aspect of the world.
At the center of the issue of scientific knowledge can thus be found questions about the relationship between language and what it refers to. A discussion about the role played by language in the pursuit of knowledge has been going on among linguists for several decades. The debate centers around whether language corresponds in some essential way to objects and behaviors, making knowledge a solid and reliable commodity; or, on the other hand, whether the relationship between language and things is purely a matter of agreed-upon conventions, making knowledge tenuous, relative, and inexact.g wider acceptance. According to linguists who support this theory, the way language is used varies depending upon changes in accepted practices and theories among those who work in a particular discipline. These linguists argue that, in the pursuit of knowledge, a statement is true only when there are no promising alternatives that might lead one to question it. Certainly this characterization would seem to be applicable to the sciences. In science, a mathematical statement may be taken to account for every aspect of a phenomenon it is applied to, but, some would argue, there is nothing inherent in mathematical language that guarantees such a correspondence. Under this view, acceptance of a mathematical statement by the scientific community—by virtue of the statement’s predictive power or methodological efficiency—transforms what is basically an analogy or metaphor into an explanation of the physical process in question, to be held as true until another, more compelling analogy takes its place.
In pursuing the implications of this theory, linguists have reached the point at which they must ask: If words or sentences do not correspond in an essential way to life or to our ideas about life, then just what are they capable of telling us about the world? In science and mathematics, then, it would seem equally necessary to ask: If models of electrolytes or E = mc2, say, do not correspond essentially to the physical world, then just what functions do they perform in the acquisition of scientific knowledge? But this question has yet to be significantly addressed in the sciences.`;

export const Lesson1_PassageAnalysis: Lesson = {
  id: "50-1",
  title: "Passage Analysis",
  content: [
    { type: 'accordion', title: 'Read Passage', content: passageText },
    { type: 'h3', text: "Passage Analysis: Mathematics as Language" },
    { type: 'paragraph', text: "This passage is about how science uses math to explain things. The author uses an idea from language studies to suggest that maybe math isn't a perfect picture of reality, but more like a powerful tool we've all agreed to use. The main point is that scientists should be asking the same tough questions about their 'math-language' that language experts ask about words." },
    { type: 'hr' },
    { type: 'h4', text: "Paragraph 1: Math as a Language" },
    { type: 'paragraph', text: "The passage starts with the main idea: in science, 'explaining' usually means using math. Some people think of math as its own special language made of signs and rules. The goal for a scientist, then, is to find the right math 'sentence' to describe how something in the world works." },
    { type: 'h4', text: "Paragraph 2: The Big Debate in Language" },
    { type: 'paragraph', text: "The author brings in a big debate from language studies to make a comparison. The debate is about whether words have a real, direct connection to the things they describe, or if they're just rules we all agree on.\n1. **Direct Connection:** Language is a true mirror of reality.\n2. **Agreed-Upon Rules:** Language is just a system of social conventions." },
    { type: 'h4', text: "Paragraph 3: Applying the 'Rules' View to Science" },
    { type: 'paragraph', text: "The author applies the 'agreed-upon rules' idea to science. In this view, a statement is 'true' just because it's the best explanation we have right now. This is how science works, the author says. A math equation is accepted because it works—it can predict things and is efficient. It's not a perfect picture of reality, but a powerful metaphor that we use until a better one comes along." },
    { type: 'h4', text: "Paragraph 4: The Unanswered Question for Scientists" },
    { type: 'paragraph', text: "The passage wraps up by bringing the argument back to the scientists. The language experts who believe in the 'rules' view have to ask a big question: If words don't have a direct link to reality, what are they really telling us? The author argues that scientists need to ask the same thing about their math models (like E=mc²). The passage ends by criticizing scientists for not having seriously tackled this fundamental question yet." },
    { type: 'callout', title: "Summary", variant: "summary", text: "The author argues that scientists should be more self-critical, just like some language experts. The main idea is that mathematical explanations might not be a direct mirror of reality, but are powerful, agreed-upon tools (or metaphors). The author's final point is a challenge to scientists: it's time to figure out what these mathematical tools are really doing." }
  ]
};