import { Lesson } from '../../types';

const passageText = `What it means to “explain” something in science often comes down to the application of mathematics. Some thinkers hold that mathematics is a kind of language—a systematic contrivance of signs, the criteria for the authority of which are internal coherence, elegance, and depth. The application of such a highly artificial system to the physical world, they claim, results in the creation of a kind of statement about the world. Accordingly, what matters in the sciences is finding a mathematical concept that attempts, as other language does, to accurately describe the functioning of some aspect of the world.
At the center of the issue of scientific knowledge can thus be found questions about the relationship between language and what it refers to. A discussion about the role played by language in the pursuit of knowledge has been going on among linguists for several decades. The debate centers around whether language corresponds in some essential way to objects and behaviors, making knowledge a solid and reliable commodity; or, on the other hand, whether the relationship between language and things is purely a matter of agreed-upon conventions, making knowledge tenuous, relative, and inexact.g wider acceptance. According to linguists who support this theory, the way language is used varies depending upon changes in accepted practices and theories among those who work in a particular discipline. These linguists argue that, in the pursuit of knowledge, a statement is true only when there are no promising alternatives that might lead one to question it. Certainly this characterization would seem to be applicable to the sciences. In science, a mathematical statement may be taken to account for every aspect of a phenomenon it is applied to, but, some would argue, there is nothing inherent in mathematical language that guarantees such a correspondence. Under this view, acceptance of a mathematical statement by the scientific community—by virtue of the statement’s predictive power or methodological efficiency—transforms what is basically an analogy or metaphor into an explanation of the physical process in question, to be held as true until another, more compelling analogy takes its place.
In pursuing the implications of this theory, linguists have reached the point at which they must ask: If words or sentences do not correspond in an essential way to life or to our ideas about life, then just what are they capable of telling us about the world? In science and mathematics, then, it would seem equally necessary to ask: If models of electrolytes or E = mc2, say, do not correspond essentially to the physical world, then just what functions do they perform in the acquisition of scientific knowledge? But this question has yet to be significantly addressed in the sciences.`;

export const Lesson1_PassageAnalysis: Lesson = {
  id: "50-1",
  title: "Passage Analysis",
  content: [
    { type: 'accordion', title: 'Read Passage (PT-108-S-1-P-4)', content: passageText },
    { type: 'h3', text: "Passage Analysis: Mathematics as Language (PT-108-S-1-P-4)" },
    { type: 'paragraph', text: "The passage examines whether mathematical explanation in science reflects reality directly or functions as a disciplined linguistic convention. Its thesis is that science may rely on accepted symbolic frameworks rather than essential correspondence." },
    { type: 'paragraph', text: "Track the argument as a transfer from linguistics to philosophy of science. Paragraph 1 frames mathematics as language, Paragraph 2 develops the underlying linguistic debate, Paragraph 3 applies the convention view to scientific practice, and Paragraph 4 states the unresolved implication." },
    { type: 'hr' },
    { type: 'h4', text: "Paragraph 1: Framing Mathematics as Explanatory Language" },
    { type: 'paragraph', text: "The opening paragraph defines scientific explanation as largely mathematical and introduces a key analogy: mathematics behaves like language, with internal standards such as coherence and elegance." },
    { type: 'paragraph', text: "This framing shifts the question from \"Which equation is correct?\" to \"What kind of representational claim does equation use actually make?\"" },
    { type: 'h4', text: "Paragraph 2: Linguistic Theory as Conceptual Backbone" },
    { type: 'paragraph', text: "The second paragraph imports a linguistic dispute: whether language tracks reality inherently or through social convention. This distinction becomes the conceptual backbone for the passage's later claims about science." },
    { type: 'paragraph', text: "By presenting both sides, the author prepares the reader to evaluate scientific explanation as potentially contingent rather than fixed by direct correspondence." },
    { type: 'h4', text: "Paragraph 3: Convention Model Applied to Scientific Truth" },
    { type: 'paragraph', text: "The third paragraph applies the convention-based model to mathematics in science. On this view, models are accepted because they organize inquiry, predict effectively, and outperform alternatives." },
    { type: 'paragraph', text: "Scientific truth is therefore treated as provisional and comparative: explanatory status attaches to the strongest available framework, not to guaranteed metaphysical identity with the world." },
    { type: 'h4', text: "Paragraph 4: The Outstanding Methodological Question" },
    { type: 'paragraph', text: "The final paragraph states the unresolved implication. If mathematical models are not essentially identical with reality, science must explain what knowledge-function they actually perform." },
    { type: 'paragraph', text: "The passage closes as a challenge: science has benefited from mathematical formalism but has not fully theorized what that formalism epistemically commits us to." },
    { type: 'callout', title: "Summary of the Argument", variant: "summary", text: "The passage argues that mathematical explanation may function more like a convention-governed language than a direct mirror of reality. After importing a linguistic framework, it applies that framework to science and concludes that the discipline still owes a clearer account of what its mathematical models are doing epistemically." }
  ]
};
