
import { Lesson } from '../../types';

const passageText = `What it means to “explain” something in science often comes down to the application of mathematics. Some thinkers hold that mathematics is a kind of language—a systematic contrivance of signs, the criteria for the authority of which are internal coherence, elegance, and depth. The application of such a highly artificial system to the physical world, they claim, results in the creation of a kind of statement about the world. Accordingly, what matters in the sciences is finding a mathematical concept that attempts, as other language does, to accurately describe the functioning of some aspect of the world.
At the center of the issue of scientific knowledge can thus be found questions about the relationship between language and what it refers to. A discussion about the role played by language in the pursuit of knowledge has been going on among linguists for several decades. The debate centers around whether language corresponds in some essential way to objects and behaviors, making knowledge a solid and reliable commodity; or, on the other hand, whether the relationship between language and things is purely a matter of agreed-upon conventions, making knowledge tenuous, relative, and inexact.g wider acceptance. According to linguists who support this theory, the way language is used varies depending upon changes in accepted practices and theories among those who work in a particular discipline. These linguists argue that, in the pursuit of knowledge, a statement is true only when there are no promising alternatives that might lead one to question it. Certainly this characterization would seem to be applicable to the sciences. In science, a mathematical statement may be taken to account for every aspect of a phenomenon it is applied to, but, some would argue, there is nothing inherent in mathematical language that guarantees such a correspondence. Under this view, acceptance of a mathematical statement by the scientific community—by virtue of the statement’s predictive power or methodological efficiency—transforms what is basically an analogy or metaphor into an explanation of the physical process in question, to be held as true until another, more compelling analogy takes its place.
In pursuing the implications of this theory, linguists have reached the point at which they must ask: If words or sentences do not correspond in an essential way to life or to our ideas about life, then just what are they capable of telling us about the world? In science and mathematics, then, it would seem equally necessary to ask: If models of electrolytes or E = mc2, say, do not correspond essentially to the physical world, then just what functions do they perform in the acquisition of scientific knowledge? But this question has yet to be significantly addressed in the sciences.`;

export const Lesson6_Question26: Lesson = {
  id: "50-6",
  title: "Question 26: 3rd-Party Viewpoint",
  content: [
    { type: 'accordion', title: 'Read Passage (PT-108-S-1-P-4)', content: passageText },
    { type: 'h3', text: "Question 26: 3rd-Party Viewpoint Breakdown (PT-108-S-1-P-4-Q-26)" },
    { type: 'blockquote', text: "**Question:** Based on the passage, linguists who subscribe to the theory that “the relationship between language and things is purely a matter of agreed-upon conventions\" (near the end of the second paragraph) would hold that the statement “The ball is red” is true because" },
    { type: 'options', items: [
      "(A) speakers of English have accepted that “The ball is red” applies to the particular physical relationship being described (Correct)",
      "(B) speakers of English do not accept that synonyms for “ball” and “red” express these concepts as elegantly",
      "(C) “The ball is red” corresponds essentially to every aspect of the particular physical relationship being described",
      "(D) “ball” and “red” actually refer to an entity and a property respectively",
      "(E) “ball” and “red” are mathematical concepts that attempt to accurately describe some particular physical relationship in the world"
    ]},
    { type: 'h4', text: "Analysis" },
    { type: 'paragraph', text: "This 3rd-party viewpoint question should be resolved by matching each choice to what the passage actually establishes. Use the opening and closing claims as scope anchors, then select the option that satisfies the stem without unsupported assumptions." },
    { type: 'callout', title: "Text Evidence", variant: "tip", text: "Anchor your reading in phrases such as 'What it means to “explain” something in science often comes down...' and 'In pursuing the implications of this theory, linguists have reached the...' when checking whether a choice preserves the passage's emphasis." },
    { type: 'breakdown', labels: { title: 'Option', text: 'Analysis' }, items: [
      { title: "(A)", text: "This answer aligns with the theory that truth in language comes from social agreement. The linguists mentioned believe a statement is true because people have agreed to use those words to describe that specific situation. It is the community's acceptance that matters. Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support." },
      { title: "(B)", text: "The passage mentions \"elegance\" in the first paragraph when discussing mathematics. However, it is not presented as the reason why a statement is considered true under the \"agreed-upon conventions\" theory. Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support." },
      { title: "(C)", text: "This choice describes the opposing viewpoint mentioned in the passage. The linguists in the question reject the idea that language \"corresponds essentially\" to the world, arguing instead for a system of conventions. Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support." },
      { title: "(D)", text: "This statement describes a basic function of words but doesn't explain why a particular statement is considered true according to the theory. The theory focuses on social agreement, not the fundamental nature of reference. Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support." },
      { title: "(E)", text: "This choice incorrectly labels \"ball\" and \"red\" as mathematical concepts. While the passage uses mathematics as an example of a scientific language, the specific terms in the question are from everyday language. Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support." }
    ]}
  ]
};
