import { Lesson } from '../../types';

const passageText = `Some critics of advertising have assumed that the creation of false needs in consumers is the principal mechanism underlying what these critics regard as its manipulative and hegemonic power. Central to this type of critique are the writings of political theorist Herbert Marcuse, who maintained that modern people succumb to oppression by believing themselves satisfied in spite of their living in an objectively unsatisfying world. This process occurs because in mass market culture the powerful psychological techniques of advertising create “needs” that are false and whose satisfaction thus contributes, not to the genuine well-being of consumers, but rather to the profit—and thereby the disproportionate power—of corporations.

Marcuse supposed that we all have certain real needs, both physical and psychological. Advertising appropriates these needs for its own purposes, forging psychological associations between them and consumer items, e.g., between sex and perfume, thereby creating a false “need” for these items. Since the quest for fulfillment is thus displaced from its true objects to consumer items, the implicit promises of advertisements are never really fulfilled and the consumer remains at some level unsatisfied.

Unfortunately, the distinction between real and false needs upon which this critique depends is extremely problematic. If Marcusians are right, we cannot, with any assurance, separate our real needs from the alleged false needs we feel as a result of the manipulation of advertisers. For, in order to do so, it would be necessary to eliminate forces of persuasion that are so prevalent in society that they have come to inform our instinctive judgments about things.

But, in fact, Marcusians make a major mistake in assuming that the majority of consumers who respond to advertising do not do so autonomously. Advertising techniques are unable to induce unwilling behavior in rational, informed adults, and regulations prohibit misinformation in advertising claims. Moreover, evidence suggests that most adults understand and recognize the techniques used and are not merely passive instruments. If there is a real need for emotional fulfillment, and if we can freely and authentically choose our means of obtaining it, then free, informed individuals may choose to obtain it through the purchase of commodities or even through the enjoyment occasionally provided by advertisements themselves. It is no doubt true that in many—perhaps even most—cases the use of an advertised product does not yield the precise sort of emotional dividend that advertisements seem to promise. This does not mean, however, that consumers do not freely and intentionally use the product as a means to another sort of fulfillment, or even that its genuine fulfillment of needs must be less than the advertisement suggests.`;

export const Lesson4_Question18: Lesson = {
  id: "45-4",
  title: "Question 18: Paragraph Function",
  content: [
    { type: 'accordion', title: 'Read Passage (PT-141-S-1-P-3)', content: passageText },
    { type: 'h3', text: "Question 18: Paragraph Function Breakdown (PT-141-S-1-P-3-Q-18)" },
    { type: 'blockquote', text: "The main function of the first paragraph is to" },
    { type: 'options', items: [
      "(A) summarize the political and economic context from which Marcusian critiques of advertising arise",
      "(B) outline the mechanisms by which false needs originate in mass market culture",
      "(C) evaluate the psychological processes by which the manipulative techniques of mass market advertising influence individuals",
      "(D) describe the prevailing views among contemporary critics of advertising and categorize Marcuse’s theories in relation to those views",
      "(E) describe Marcusian views regarding mass market manipulation and indicate their role in certain criticisms of advertising (Correct)"
    ]},
    { type: 'h4', text: "Analysis" },
    { type: 'paragraph', text: "This paragraph function question should be resolved by matching each choice to what the passage actually establishes. Use the opening and closing claims as scope anchors, then select the option that satisfies the stem without unsupported assumptions." },
    { type: 'callout', title: "Text Evidence", variant: "tip", text: "Anchor your reading in phrases such as 'Some critics of advertising have assumed that the creation of false...' and 'This does not mean, however, that consumers do not freely and...' when checking whether a choice preserves the passage's emphasis." },
    { type: 'breakdown', labels: { title: 'Option', text: 'Analysis' }, items: [
      { title: "(A) summarize the political and economic context from which Marcusian critiques of advertising arise", text: "The paragraph focuses tightly on summarizing Marcuse's *theory*, not the broader historical or political \"context\" that produced it. Additional check: trap type is too broad, since it extends beyond what the passage actually supports.", badge: "Incorrect", badgeColor: "red" },
      { title: "(B) outline the mechanisms by which false needs originate in mass market culture", text: "The first paragraph introduces the *concept* of false needs, but the more detailed explanation of the \"mechanisms\" (e.g., the perfume example) is found in the second paragraph. The first paragraph's function is more introductory. Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support.", badge: "Incorrect", badgeColor: "red" },
      { title: "(C) evaluate the psychological processes by which the manipulative techniques of mass market advertising influence individuals", text: "The key verb here is \"evaluate.\" The first paragraph is purely descriptive; it explains the Marcusian view without passing judgment on it. The author's \"evaluation\" does not begin until the third paragraph. Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support.", badge: "Incorrect", badgeColor: "red" },
      { title: "(D) describe the prevailing views among contemporary critics of advertising and categorize Marcuse’s theories in relation to those views", text: "The word \"prevailing\" is an overstatement. The passage says this is the view of \"*some* critics\" and that Marcuse is central to \"*this type* of critique,\" which is more specific than a general \"prevailing view.\" Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support.", badge: "Incorrect", badgeColor: "red" },
      { title: "(E) describe Marcusian views regarding mass market manipulation and indicate their role in certain criticisms of advertising", text: "This choice accurately captures the paragraph's dual function. It \"describes Marcusian views\" and also \"indicates their role in certain criticisms of advertising\" by identifying Marcuse as a central figure in that school of thought. Additional check: this is strongest because it directly satisfies the stem while preserving the passage's scope and emphasis.", badge: "Correct", badgeColor: "green" }
    ]}
  ]
};
