import { Lesson } from '../../types';

const passageText = `Some critics of advertising have assumed that the creation of false needs in consumers is the principal mechanism underlying what these critics regard as its manipulative and hegemonic power. Central to this type of critique are the writings of political theorist Herbert Marcuse, who maintained that modern people succumb to oppression by believing themselves satisfied in spite of their living in an objectively unsatisfying world. This process occurs because in mass market culture the powerful psychological techniques of advertising create “needs” that are false and whose satisfaction thus contributes, not to the genuine well-being of consumers, but rather to the profit—and thereby the disproportionate power—of corporations.

Marcuse supposed that we all have certain real needs, both physical and psychological. Advertising appropriates these needs for its own purposes, forging psychological associations between them and consumer items, e.g., between sex and perfume, thereby creating a false “need” for these items. Since the quest for fulfillment is thus displaced from its true objects to consumer items, the implicit promises of advertisements are never really fulfilled and the consumer remains at some level unsatisfied.

Unfortunately, the distinction between real and false needs upon which this critique depends is extremely problematic. If Marcusians are right, we cannot, with any assurance, separate our real needs from the alleged false needs we feel as a result of the manipulation of advertisers. For, in order to do so, it would be necessary to eliminate forces of persuasion that are so prevalent in society that they have come to inform our instinctive judgments about things.

But, in fact, Marcusians make a major mistake in assuming that the majority of consumers who respond to advertising do not do so autonomously. Advertising techniques are unable to induce unwilling behavior in rational, informed adults, and regulations prohibit misinformation in advertising claims. Moreover, evidence suggests that most adults understand and recognize the techniques used and are not merely passive instruments. If there is a real need for emotional fulfillment, and if we can freely and authentically choose our means of obtaining it, then free, informed individuals may choose to obtain it through the purchase of commodities or even through the enjoyment occasionally provided by advertisements themselves. It is no doubt true that in many—perhaps even most—cases the use of an advertised product does not yield the precise sort of emotional dividend that advertisements seem to promise. This does not mean, however, that consumers do not freely and intentionally use the product as a means to another sort of fulfillment, or even that its genuine fulfillment of needs must be less than the advertisement suggests.`;

export const Lesson2_Question16: Lesson = {
  id: "45-2",
  title: "Question 16: Main Idea",
  content: [
    { type: 'accordion', title: 'Read Passage', content: passageText },
    { type: 'h3', text: "Question Breakdown: PT-141-S-1-P-3-Q-16" },
    { type: 'blockquote', text: "Which one of the following most accurately expresses the main point of the passage?" },
    { type: 'options', items: [
      "(A) Advertising has greater social value than Marcusians have supposed, because it is both an effective means of informing consumers and often an intrinsically entertaining medium of mass communication. [1.0%]",
      "(B) Even if, as Marcusians have argued, there is a theoretical difference between real and false needs, that difference is obscured in practice by the relationship of consumers to the forces of persuasion in profit-motivated, consumer-oriented societies. [4.0%]",
      "(C) Marcusian arguments regarding advertisers’ creation of false needs are mistaken, because individuals are able to make autonomous decisions regarding their needs and are even able to use the elements of mass market culture to achieve genuine fulfillment. [78.0%] (Correct)",
      "(D) Critics of advertising typically focus on the development of false needs in the consumer and do not fully consider the ability of people to make independent choices by distinguishing their own real needs from the apparent needs that advertising induces. [15.0%]",
      "(E) The problematic distinction that Marcusians have drawn between real and false needs provides an inadequate basis for their attacks on advertising, because the distinction overlooks consumers’ physical and psychological needs. [2.0%]"
    ]},
    { type: 'paragraph', text: "This question asks for the \"main point of the passage.\" It requires identifying the author's central thesis, which is the primary argument the entire text is constructed to support. The passage is structured as a debate: it first explains the Marcusian critique of advertising and then systematically refutes it. The author's own position is most clearly articulated in the final paragraph.\n\nThe author's core argument is that the Marcusian critique, which views consumers as passive victims manipulated into having \"false needs,\" is fundamentally flawed. The author's rebuttal centers on the idea of consumer autonomy—the belief that individuals are rational agents who are aware of advertising's techniques and make their own free choices.\n\nTherefore, the main point should be a statement that rejects the Marcusian view *because* it fails to account for the autonomy of the consumer." },
    { type: 'breakdown', labels: { title: 'Option', text: 'Analysis' }, items: [
      { title: "(A) Advertising has greater social value than Marcusians have supposed...", text: "The author's argument is not about the \"social value\" of advertising. The focus is on the nature of the consumer (autonomous vs. manipulated), not on whether advertising is a net positive for society.", badge: "Incorrect", badgeColor: "red" },
      { title: "(B) Even if, as Marcusians have argued...", text: "This statement accurately summarizes the philosophical point made in the third paragraph. However, this is a supporting argument, not the main point. The author's primary rebuttal, which they call the \"major mistake\" of the critique, is presented in the final paragraph.", badge: "Incorrect", badgeColor: "red" },
      { title: "(C) Marcusian arguments regarding advertisers’ creation of false needs are mistaken...", text: "This choice perfectly captures the author's central thesis. It identifies the target of the critique (\"Marcusian arguments... are mistaken\"), states the core reason for the refutation (\"because individuals are able to make autonomous decisions\"), and includes the final nuance about achieving \"genuine fulfillment.\"", badge: "Correct", badgeColor: "green" },
      { title: "(D) Critics of advertising typically focus on the development of false needs...", text: "This is a description of the flaw in the critique but is not framed as the author's main point. It describes what the critics do wrong but does not state the author's own positive thesis as clearly as choice (C) does.", badge: "Incorrect", badgeColor: "red" },
      { title: "(E) The problematic distinction that Marcusians have drawn...", text: "The \"because\" clause is incorrect. The Marcuse theory does not overlook real needs; it is predicated on the idea that advertising *appropriates* those needs. This choice misrepresents the theory being discussed.", badge: "Incorrect", badgeColor: "red" }
    ]}
  ]
};
