import { Lesson } from '../../types';

const passageText = `Some critics of advertising have assumed that the creation of false needs in consumers is the principal mechanism underlying what these critics regard as its manipulative and hegemonic power. Central to this type of critique are the writings of political theorist Herbert Marcuse, who maintained that modern people succumb to oppression by believing themselves satisfied in spite of their living in an objectively unsatisfying world. This process occurs because in mass market culture the powerful psychological techniques of advertising create “needs” that are false and whose satisfaction thus contributes, not to the genuine well-being of consumers, but rather to the profit—and thereby the disproportionate power—of corporations.

Marcuse supposed that we all have certain real needs, both physical and psychological. Advertising appropriates these needs for its own purposes, forging psychological associations between them and consumer items, e.g., between sex and perfume, thereby creating a false “need” for these items. Since the quest for fulfillment is thus displaced from its true objects to consumer items, the implicit promises of advertisements are never really fulfilled and the consumer remains at some level unsatisfied.

Unfortunately, the distinction between real and false needs upon which this critique depends is extremely problematic. If Marcusians are right, we cannot, with any assurance, separate our real needs from the alleged false needs we feel as a result of the manipulation of advertisers. For, in order to do so, it would be necessary to eliminate forces of persuasion that are so prevalent in society that they have come to inform our instinctive judgments about things.

But, in fact, Marcusians make a major mistake in assuming that the majority of consumers who respond to advertising do not do so autonomously. Advertising techniques are unable to induce unwilling behavior in rational, informed adults, and regulations prohibit misinformation in advertising claims. Moreover, evidence suggests that most adults understand and recognize the techniques used and are not merely passive instruments. If there is a real need for emotional fulfillment, and if we can freely and authentically choose our means of obtaining it, then free, informed individuals may choose to obtain it through the purchase of commodities or even through the enjoyment occasionally provided by advertisements themselves. It is no doubt true that in many—perhaps even most—cases the use of an advertised product does not yield the precise sort of emotional dividend that advertisements seem to promise. This does not mean, however, that consumers do not freely and intentionally use the product as a means to another sort of fulfillment, or even that its genuine fulfillment of needs must be less than the advertisement suggests.`;

export const Lesson1_PassageAnalysis: Lesson = {
  id: "45-1",
  title: "Passage Analysis",
  content: [
    { type: 'accordion', title: 'Read Passage', content: passageText },
    { type: 'h3', text: "Passage Analysis" },
    { type: 'h4', text: "Paragraphs 1 & 2: The Marcuse Critique of Advertising" },
    { type: 'paragraph', text: "The first two paragraphs are dedicated to explaining a specific critical theory of advertising, primarily associated with the political theorist Herbert Marcuse. This can be called the \"False Needs\" argument. The core idea is that modern corporate society is oppressive, but it prevents people from realizing this by making them feel satisfied. The primary tool for this is advertising, which works by creating \"false needs.\" Marcuse distinguished between *real* needs (food, connection, safety) and the \"false needs\" created by advertising. The mechanism involves hijacking a real need and creating a psychological association between it and a consumer product, such as linking the real human need for sexual connection with the desire for a specific perfume. According to this theory, the consumer now feels a \"false need\" for the product, believing it will help satisfy the real need. The problem, Marcuse argues, is that the product can never truly deliver on this implicit promise, leaving the consumer perpetually unsatisfied and trapped in a cycle of consumption that serves to increase corporate power. In this view, advertising is a tool of social control." },
    
    { type: 'h4', text: "Paragraph 3: The First Rebuttal - A Philosophical Problem" },
    { type: 'paragraph', text: "In the third paragraph, the author of the passage begins a counter-argument. The first criticism is philosophical: the author argues that the very distinction between \"real\" and \"false\" needs, which is the foundation of the Marcuse critique, is \"extremely problematic.\" The author presents a logical dilemma: if advertising is so powerful that it shapes our \"instinctive judgments,\" then individuals would be incapable of distinguishing their \"real\" needs from the false ones imposed upon them. A person completely manipulated would lack the clear perspective needed to make such a judgment, undermining the basis of the critique from within." },

    { type: 'h4', text: "Paragraph 4: The Main Rebuttal - The Autonomous Consumer" },
    { type: 'paragraph', text: "This final paragraph contains the core of the author's own argument. The author asserts that Marcusians make one \"major mistake\": they assume that consumers are not **autonomous**. The author defends the idea that people are rational, free-thinking agents, not \"passive instruments.\" To support this, the author notes that advertising cannot force rational adults to act against their will, that regulations prohibit outright misinformation, and, most importantly, that evidence suggests adults are aware of the techniques being used. The author's conclusion is that if a free, informed person chooses to buy a product in a search for emotional fulfillment, that is an \"authentic\" choice. Even if the product fails to deliver the promised experience, the consumer's choice to use the product as a means to fulfillment was freely and intentionally made." },
    
    { type: 'callout', title: "Summary", variant: "summary", text: "• **The Critique (Marcuse's View):** This argument posits that advertising is a manipulative force that creates \"false needs\" by linking products to real psychological needs. This process leaves consumers perpetually unsatisfied and serves corporate power, making it a tool of social control. The consumer is a **manipulated victim**.\n• **The Rebuttal (The Author's View):** The author counters this by first pointing out a philosophical flaw in the \"real vs. false needs\" distinction. The main argument, however, is that the critique fundamentally misunderstands the consumer. The author argues that most adults are rational, aware of advertising's techniques, and make free, autonomous choices. The consumer is a **rational agent**.\n• **The Central Conflict:** The passage presents a debate centered on the nature of the consumer: Are people passive victims controlled by a powerful system, or are they active, rational participants who make their own choices?" }
  ]
};
