import { Lesson } from '../../types';

const passageText = `Some critics of advertising have assumed that the creation of false needs in consumers is the principal mechanism underlying what these critics regard as its manipulative and hegemonic power. Central to this type of critique are the writings of political theorist Herbert Marcuse, who maintained that modern people succumb to oppression by believing themselves satisfied in spite of their living in an objectively unsatisfying world. This process occurs because in mass market culture the powerful psychological techniques of advertising create “needs” that are false and whose satisfaction thus contributes, not to the genuine well-being of consumers, but rather to the profit—and thereby the disproportionate power—of corporations.

Marcuse supposed that we all have certain real needs, both physical and psychological. Advertising appropriates these needs for its own purposes, forging psychological associations between them and consumer items, e.g., between sex and perfume, thereby creating a false “need” for these items. Since the quest for fulfillment is thus displaced from its true objects to consumer items, the implicit promises of advertisements are never really fulfilled and the consumer remains at some level unsatisfied.

Unfortunately, the distinction between real and false needs upon which this critique depends is extremely problematic. If Marcusians are right, we cannot, with any assurance, separate our real needs from the alleged false needs we feel as a result of the manipulation of advertisers. For, in order to do so, it would be necessary to eliminate forces of persuasion that are so prevalent in society that they have come to inform our instinctive judgments about things.

But, in fact, Marcusians make a major mistake in assuming that the majority of consumers who respond to advertising do not do so autonomously. Advertising techniques are unable to induce unwilling behavior in rational, informed adults, and regulations prohibit misinformation in advertising claims. Moreover, evidence suggests that most adults understand and recognize the techniques used and are not merely passive instruments. If there is a real need for emotional fulfillment, and if we can freely and authentically choose our means of obtaining it, then free, informed individuals may choose to obtain it through the purchase of commodities or even through the enjoyment occasionally provided by advertisements themselves. It is no doubt true that in many—perhaps even most—cases the use of an advertised product does not yield the precise sort of emotional dividend that advertisements seem to promise. This does not mean, however, that consumers do not freely and intentionally use the product as a means to another sort of fulfillment, or even that its genuine fulfillment of needs must be less than the advertisement suggests.`;

export const Lesson5_Question19: Lesson = {
  id: "45-5",
  title: "Question 19: Inference",
  content: [
    { type: 'accordion', title: 'Read Passage', content: passageText },
    { type: 'h3', text: "Question Breakdown: PT-141-S-1-P-3-Q-19" },
    { type: 'blockquote', text: "Which one of the following is a claim that the author attributes to Marcuse?" },
    { type: 'options', items: [
      "(A) In modern society, advertising helps lead people to think that they are satisfied. [45.0%] (Correct)",
      "(B) Modern societies differ from earlier societies in that they fail to satisfy basic physical needs. [1.0%]",
      "(C) It is impossible to draw any meaningful distinction between real and false psychological needs in modern society. [29.0%]",
      "(D) Advertising in modern society has sometimes become a tool of oppression working to the benefit of totalitarian political systems. [4.0%]",
      "(E) Advertising exploits basic human needs by deriving from them certain secondary needs which, though they become real needs, subtly work to the detriment of consumers. [22.0%]"
    ]},
    { type: 'paragraph', text: "This question asks for a specific claim that the author attributes to Marcuse. This requires a careful reading of the first two paragraphs, where the author outlines the Marcusian critique. We are looking for an idea explicitly presented as part of Marcuse's theory.\n\nThe core of Marcuse's argument is that modern corporate society, while objectively unsatisfying, maintains control by making people *feel* satisfied. The passage states that Marcuse believed \"modern people succumb to oppression by believing themselves satisfied,\" and that this process occurs because advertising creates false needs. Therefore, a key claim in Marcuse's theory is that advertising is a mechanism for creating a false sense of satisfaction in an oppressive society." },
    { type: 'breakdown', labels: { title: 'Option', text: 'Analysis' }, items: [
      { title: "(A) In modern society, advertising helps lead people to think that they are satisfied.", text: "This is a direct and accurate paraphrase of the claim made in the first paragraph. The text states that according to Marcuse, people are led to \"[believe] themselves satisfied,\" and that advertising is the primary cause of this process.", badge: "Correct", badgeColor: "green" },
      { title: "(B) Modern societies differ from earlier societies in that they fail to satisfy basic physical needs.", text: "Marcuse's theory, as presented, focuses on the manipulation of psychological needs and the creation of \"false\" consumer needs. The passage does not suggest that he believed modern society fails to meet basic *physical* needs.", badge: "Incorrect", badgeColor: "red" },
      { title: "(C) It is impossible to draw any meaningful distinction between real and false psychological needs in modern society.", text: "This is a claim made by the *author* in the third paragraph as a critique *of* Marcuse. Marcuse's own theory is entirely dependent on the idea that such a distinction is possible and meaningful. This is a misattribution.", badge: "Incorrect", badgeColor: "red" },
      { title: "(D) Advertising in modern society has sometimes become a tool of oppression working to the benefit of totalitarian political systems.", text: "The passage attributes to Marcuse the view that advertising is a tool of oppression that benefits *corporations*. There is no mention of \"totalitarian political systems.\"", badge: "Incorrect", badgeColor: "red" },
      { title: "(E) Advertising exploits basic human needs by deriving from them certain secondary needs which, though they become real needs, subtly work to the detriment of consumers.", text: "This misrepresents a key term. The passage is clear that Marcuse believed the needs created by advertising are \"**false**,\" not that they \"become real needs.\"", badge: "Incorrect", badgeColor: "red" }
    ]}
  ]
};
