import { Lesson } from '../../types';

const passageText = `Some critics of advertising have assumed that the creation of false needs in consumers is the principal mechanism underlying what these critics regard as its manipulative and hegemonic power. Central to this type of critique are the writings of political theorist Herbert Marcuse, who maintained that modern people succumb to oppression by believing themselves satisfied in spite of their living in an objectively unsatisfying world. This process occurs because in mass market culture the powerful psychological techniques of advertising create “needs” that are false and whose satisfaction thus contributes, not to the genuine well-being of consumers, but rather to the profit—and thereby the disproportionate power—of corporations.

Marcuse supposed that we all have certain real needs, both physical and psychological. Advertising appropriates these needs for its own purposes, forging psychological associations between them and consumer items, e.g., between sex and perfume, thereby creating a false “need” for these items. Since the quest for fulfillment is thus displaced from its true objects to consumer items, the implicit promises of advertisements are never really fulfilled and the consumer remains at some level unsatisfied.

Unfortunately, the distinction between real and false needs upon which this critique depends is extremely problematic. If Marcusians are right, we cannot, with any assurance, separate our real needs from the alleged false needs we feel as a result of the manipulation of advertisers. For, in order to do so, it would be necessary to eliminate forces of persuasion that are so prevalent in society that they have come to inform our instinctive judgments about things.

But, in fact, Marcusians make a major mistake in assuming that the majority of consumers who respond to advertising do not do so autonomously. Advertising techniques are unable to induce unwilling behavior in rational, informed adults, and regulations prohibit misinformation in advertising claims. Moreover, evidence suggests that most adults understand and recognize the techniques used and are not merely passive instruments. If there is a real need for emotional fulfillment, and if we can freely and authentically choose our means of obtaining it, then free, informed individuals may choose to obtain it through the purchase of commodities or even through the enjoyment occasionally provided by advertisements themselves. It is no doubt true that in many—perhaps even most—cases the use of an advertised product does not yield the precise sort of emotional dividend that advertisements seem to promise. This does not mean, however, that consumers do not freely and intentionally use the product as a means to another sort of fulfillment, or even that its genuine fulfillment of needs must be less than the advertisement suggests.`;

export const Lesson7_Question21: Lesson = {
  id: "45-7",
  title: "Question 21: Complete the Passage",
  content: [
    { type: 'accordion', title: 'Read Passage (PT-141-S-1-P-3)', content: passageText },
    { type: 'h3', text: "Question 21: Complete the Passage Breakdown (PT-141-S-1-P-3-Q-21)" },
    { type: 'blockquote', text: "Which one of the following sentences would most logically complete the passage?" },
    { type: 'options', items: [
      "(A) Therefore, while in principle there might be grounds for holding that advertising is detrimental to society, the Marcusian critique does not provide such grounds. (Correct)",
      "(B) Therefore, although Marcusian claims about advertising are rationally justified, the mistake of many recent critics of advertising is in their use of these claims for political gain.",
      "(C) Therefore, any shift in basic assumptions required to correct the abuses of advertising will require a change in the perception of human nature held by corporate leaders.",
      "(D) Therefore, while emphasizing only detrimental social aspects of advertising, Marcusians have failed to consider that such aspects are clearly outweighed by numerous social benefits.",
      "(E) Therefore, the Marcusian critique of advertising is mistaken except in its claim that advertisers exert economic power over those few people who are unable or unwilling to distinguish real from false needs."
    ]},
    { type: 'h4', text: "Analysis" },
    { type: 'paragraph', text: "This complete the passage question should be resolved by matching each choice to what the passage actually establishes. Use the opening and closing claims as scope anchors, then select the option that satisfies the stem without unsupported assumptions." },
    { type: 'callout', title: "Text Evidence", variant: "tip", text: "Anchor your reading in phrases such as 'Some critics of advertising have assumed that the creation of false...' and 'This does not mean, however, that consumers do not freely and...' when checking whether a choice preserves the passage's emphasis." },
    { type: 'breakdown', labels: { title: 'Option', text: 'Analysis' }, items: [
      { title: "(A) Therefore, while in principle there might be grounds for holding that advertising is detrimental to society, the Marcusian critique does not provide such grounds.", text: "This is an excellent conclusion. It directly states the author's final judgment: \"the Marcusian critique does not provide such grounds\" (i.e., it fails). The first clause (\"while in principle there might be grounds...\") adds a sophisticated nuance that perfectly reflects the passage's scope. The author has not defended advertising against all possible attacks, only against this specific one. This sentence provides a precise and logical summary of the author's project. Additional check: this is strongest because it directly satisfies the stem while preserving the passage's scope and emphasis.", badge: "Correct", badgeColor: "green" },
      { title: "(B) Therefore, although Marcusian claims about advertising are rationally justified...", text: "This directly contradicts the author's argument. The author has spent two paragraphs arguing that Marcusian claims are *not* rationally justified, calling them \"problematic\" and a \"major mistake.\" Additional check: trap type is reversal/contradiction, because it flips the passage's direction or conclusion.", badge: "Incorrect", badgeColor: "red" },
      { title: "(C) Therefore, any shift in basic assumptions required to correct the abuses of advertising...", text: "The passage is an academic critique of a theory, not a call to action. It does not discuss \"correcting abuses\" or the views of \"corporate leaders.\" This conclusion introduces new topics and is not a logical extension of the argument. Additional check: trap type is out of scope, because it shifts away from the stem's target issue.", badge: "Incorrect", badgeColor: "red" },
      { title: "(D) Therefore, while emphasizing only detrimental social aspects of advertising, Marcusians have failed to consider that such aspects are clearly outweighed by numerous social benefits.", text: "The author's critique of Marcuse is not based on a cost-benefit analysis. The author never discusses the \"social benefits\" of advertising. The argument is about consumer autonomy, a different line of reasoning altogether. Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support.", badge: "Incorrect", badgeColor: "red" },
      { title: "(E) Therefore, the Marcusian critique of advertising is mistaken except in its claim that advertisers exert economic power...", text: "The author's critique is more fundamental than this. The author argues that the very *distinction* between real and false needs is \"extremely problematic\" for everyone, not just that the theory fails for most people. This choice offers a compromise that the author's strong language (\"major mistake\") does not support. Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support.", badge: "Incorrect", badgeColor: "red" }
    ]}
  ]
};
