import { Lesson } from '../../types';

const passageText = `The following passage was written in the mid-1990s.
Users of the Internet—the worldwide network of interconnected computer systems—envision it as a way for people to have free access to information via their personal computers. Most Internet communication consists of sending electronic mail or exchanging ideas on electronic bulletin boards; however, a growing number of transmissions are of copyrighted works—books, photographs, videos and films, and sound recordings. In Canada, as elsewhere, the goals of Internet users have begun to conflict with reality as copyright holders look for ways to protect their material from unauthorized and uncompensated distribution.
Copyright experts say that Canadian copyright law, which was revised in 1987 to cover works such as choreography and photography, has not kept pace with technology—specifically with digitalization, the conversion of data into a series of digits that are transmitted as electronic signals over computer networks. Digitalization makes it possible to create an unlimited number of copies of a book, recording, or movie and distribute them to millions of people around the world. Current law prohibits unauthorized parties from reproducing a work or any substantial part of it in any material form (e.g., photocopies of books or pirated audiotapes), but because digitalization merely transforms the work into electronic signals in a computer’s memory, it is not clear whether digitalization constitutes a material reproduction—and so unauthorized digitalization is not yet technically a crime.
Some experts propose simply adding unauthorized digitalization to the list of activities proscribed under current law, to make it clear that copyright holders own electronic reproduction rights just as they own rights to other types of reproduction. But criminalizing digitalization raises a host of questions. For example, given that digitalization allows the multiple recipients of a transmission to re-create copies of a work, would only the act of digitalization itself be criminal, or should each copy made from the transmission be considered a separate instance of piracy—even though those who made the copies never had access to the original? In addition, laws against digitalization might be virtually unenforceable given that an estimated 20 million people around the world have access to the Internet, and that copying and distributing material is a relatively simple process. Furthermore, even an expanded law might not cover the majority of transmissions, given the vast numbers of users who are academics and the fact that current copyright law allows generous exemptions for those engaged in private study or research. But even if the law is revised to contain a more sophisticated treatment of digitalization, most experts think it will be hard to resolve the clash between the Internet community, which is accustomed to treating information as raw material available for everyone to use, and the publishing community, which is accustomed to treating it as a commodity owned by its creator.`;

export const Lesson1_PassageAnalysis: Lesson = {
  id: "58-1",
  title: "Passage Analysis: Digitalization and Copyright Law",
  content: [
    { type: 'accordion', title: 'Read Passage (PT-115-S-3-P-4)', content: passageText },
    { type: 'h3', text: "Passage Analysis: Digitalization and Copyright (PT-115-S-3-P-4)" },
    { type: 'paragraph', text: "The passage analyzes a legal transition problem: copyright doctrine designed for physical reproduction does not map cleanly onto digital transmission. It frames both doctrinal and policy-level friction between open-access norms and ownership claims." },
    { type: 'paragraph', text: "Read this as problem-solution-complication structure. Paragraph 1 states the normative conflict, Paragraph 2 isolates the statutory gap, and Paragraph 3 evaluates why the proposed legal fix remains difficult to define, enforce, and socially reconcile." },
    { type: 'hr' },
    { type: 'h4', text: "Paragraph 1: Normative Conflict in the Early Internet" },
    { type: 'paragraph', text: "The opening paragraph sets up a clash between two value systems: internet culture's expectation of broad information access and copyright holders' claims to controlled distribution and compensation." },
    { type: 'paragraph', text: "Its purpose is not to resolve the conflict but to establish that technological adoption has created direct pressure on inherited legal assumptions." },
    { type: 'h4', text: "Paragraph 2: Statutory Ambiguity Around Digitalization" },
    { type: 'paragraph', text: "The second paragraph identifies the legal hinge. Existing law targets unauthorized reproduction in material form, but digitalization converts works into signals and memory states that may not fit that statutory language." },
    { type: 'paragraph', text: "The result is a doctrinal gap: unauthorized digital conversion can evade clear criminal classification under rules built for analog copying." },
    { type: 'h4', text: "Paragraph 3: Limits of the Proposed Fix" },
    { type: 'paragraph', text: "The final paragraph reviews a proposed amendment that would explicitly criminalize unauthorized digitalization, then enumerates implementation problems. These include offense definition, derivative-copy attribution, enforceability at internet scale, and preexisting educational exemptions." },
    { type: 'paragraph', text: "The passage closes by broadening from legal mechanics to political economy: even revised doctrine may not resolve the underlying conflict between information-as-public-resource and information-as-proprietary-good models." },
    { type: 'callout', title: "Summary of the Argument", variant: "summary", text: "The passage argues that copyright law lags behind digital technology because statutory categories built for material copying do not cleanly capture digital reproduction. It shows that even an explicit criminalization fix would face definitional, enforcement, and normative barriers rooted in competing views of what information is." }
  ]
};
