import { Lesson } from '../../types';

const passageText = `The following passage was written in the mid-1990s.
Users of the Internet—the worldwide network of interconnected computer systems—envision it as a way for people to have free access to information via their personal computers. Most Internet communication consists of sending electronic mail or exchanging ideas on electronic bulletin boards; however, a growing number of transmissions are of copyrighted works—books, photographs, videos and films, and sound recordings. In Canada, as elsewhere, the goals of Internet users have begun to conflict with reality as copyright holders look for ways to protect their material from unauthorized and uncompensated distribution.
Copyright experts say that Canadian copyright law, which was revised in 1987 to cover works such as choreography and photography, has not kept pace with technology—specifically with digitalization, the conversion of data into a series of digits that are transmitted as electronic signals over computer networks. Digitalization makes it possible to create an unlimited number of copies of a book, recording, or movie and distribute them to millions of people around the world. Current law prohibits unauthorized parties from reproducing a work or any substantial part of it in any material form (e.g., photocopies of books or pirated audiotapes), but because digitalization merely transforms the work into electronic signals in a computer’s memory, it is not clear whether digitalization constitutes a material reproduction—and so unauthorized digitalization is not yet technically a crime.
Some experts propose simply adding unauthorized digitalization to the list of activities proscribed under current law, to make it clear that copyright holders own electronic reproduction rights just as they own rights to other types of reproduction. But criminalizing digitalization raises a host of questions. For example, given that digitalization allows the multiple recipients of a transmission to re-create copies of a work, would only the act of digitalization itself be criminal, or should each copy made from the transmission be considered a separate instance of piracy—even though those who made the copies never had access to the original? In addition, laws against digitalization might be virtually unenforceable given that an estimated 20 million people around the world have access to the Internet, and that copying and distributing material is a relatively simple process. Furthermore, even an expanded law might not cover the majority of transmissions, given the vast numbers of users who are academics and the fact that current copyright law allows generous exemptions for those engaged in private study or research. But even if the law is revised to contain a more sophisticated treatment of digitalization, most experts think it will be hard to resolve the clash between the Internet community, which is accustomed to treating information as raw material available for everyone to use, and the publishing community, which is accustomed to treating it as a commodity owned by its creator.`;

export const Lesson2_Question24: Lesson = {
  id: "58-2",
  title: "Question 24: Main Idea",
  content: [
    { type: 'accordion', title: 'Read Passage (PT-115-S-3-P-4)', content: passageText },
    { type: 'h3', text: "Question 24: Main Idea Breakdown (PT-115-S-3-P-4-Q-24)" },
    { type: 'blockquote', text: "**Question:** Which one of the following most accurately expresses the main point of the passage?" },
    { type: 'options', items: [
      "(A) Despite the widely recognized need to revise Canadian copyright law to protect works from unauthorized reproduction and distribution over the Internet, users of the Internet have mounted many legal challenges to the criminalizing of digitalization.",
      "(B) Although the necessity of revising Canadian copyright law to protect works from unauthorized reproduction and distribution over the Internet is widely recognized, effective criminalizing of digitalization is likely to prove highly complicated. (Correct)",
      "(C) While the unauthorized reproduction and distribution of copyrighted works over the Internet is not yet a crime, legal experts believe it is only a matter of time before Canadian copyright law is amended to prohibit unauthorized digitalization.",
      "(D) Despite the fact that current Canadian copyright law does not cover digitalization, the unauthorized reproduction and distribution of copyrighted works over the Internet clearly ought to be considered a crime.",
      "(E) Although legal experts in Canada disagree about the most effective way to punish the unauthorized reproduction and distribution of copyrighted works over the Internet, they nonetheless agree that such digitalization should clearly be a punishable crime."
    ]},
    { type: 'h4', text: "Analysis" },
    { type: 'paragraph', text: "This main idea question should be resolved by matching each choice to what the passage actually establishes. Use the opening and closing claims as scope anchors, then select the option that satisfies the stem without unsupported assumptions." },
    { type: 'callout', title: "Text Evidence", variant: "tip", text: "Anchor your reading in phrases such as 'The following passage was written in the mid-1990s.' and 'But even if the law is revised to contain a more...' when checking whether a choice preserves the passage's emphasis." },
    { 
      type: 'breakdown',
      labels: { title: 'Option', text: 'Analysis' },
      items: [
        { title: "(A)", text: "The passage describes a philosophical conflict, but it never mentions internet users mounting 'legal challenges.' This is an unsupported detail. Additional check: trap type is unsupported inference, because the passage never supplies the missing support.", badge: "Incorrect", badgeColor: "red" },
        { title: "(B)", text: "This is a perfect summary. It acknowledges the 'necessity of revising' the law (the problem) but focuses on the author's main argument that doing so is 'highly complicated' (the analysis in paragraph 3). Additional check: this is strongest because it directly satisfies the stem while preserving the passage's scope and emphasis.", badge: "Correct", badgeColor: "green" },
        { title: "(C)", text: "The passage doesn't suggest that a legal change is inevitable ('only a matter of time'). In fact, it emphasizes the deep-seated philosophical clash that will be 'hard to resolve,' making a solution uncertain. Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support.", badge: "Incorrect", badgeColor: "red" },
        { title: "(D)", text: "The author describes the problem from a neutral, analytical perspective. They do not take a personal stance on what 'ought to be considered a crime.' This is a prescriptive statement the author does not make. Additional check: this option misses the stem by adding assumptions or emphasis that the passage does not support.", badge: "Incorrect", badgeColor: "red" },
        { title: "(E)", text: "The passage mentions that 'some experts' propose criminalizing digitalization, not that there is a broad agreement among all experts. This overstates the level of consensus. Additional check: trap type is too broad, since it extends beyond what the passage actually supports.", badge: "Incorrect", badgeColor: "red" }
      ]
    }
  ]
};
