import { Lesson } from '../../types';

const passageText = `The following passage was written in the mid-1990s.
Users of the Internet—the worldwide network of interconnected computer systems—envision it as a way for people to have free access to information via their personal computers. Most Internet communication consists of sending electronic mail or exchanging ideas on electronic bulletin boards; however, a growing number of transmissions are of copyrighted works—books, photographs, videos and films, and sound recordings. In Canada, as elsewhere, the goals of Internet users have begun to conflict with reality as copyright holders look for ways to protect their material from unauthorized and uncompensated distribution.
Copyright experts say that Canadian copyright law, which was revised in 1987 to cover works such as choreography and photography, has not kept pace with technology—specifically with digitalization, the conversion of data into a series of digits that are transmitted as electronic signals over computer networks. Digitalization makes it possible to create an unlimited number of copies of a book, recording, or movie and distribute them to millions of people around the world. Current law prohibits unauthorized parties from reproducing a work or any substantial part of it in any material form (e.g., photocopies of books or pirated audiotapes), but because digitalization merely transforms the work into electronic signals in a computer’s memory, it is not clear whether digitalization constitutes a material reproduction—and so unauthorized digitalization is not yet technically a crime.
Some experts propose simply adding unauthorized digitalization to the list of activities proscribed under current law, to make it clear that copyright holders own electronic reproduction rights just as they own rights to other types of reproduction. But criminalizing digitalization raises a host of questions. For example, given that digitalization allows the multiple recipients of a transmission to re-create copies of a work, would only the act of digitalization itself be criminal, or should each copy made from the transmission be considered a separate instance of piracy—even though those who made the copies never had access to the original? In addition, laws against digitalization might be virtually unenforceable given that an estimated 20 million people around the world have access to the Internet, and that copying and distributing material is a relatively simple process. Furthermore, even an expanded law might not cover the majority of transmissions, given the vast numbers of users who are academics and the fact that current copyright law allows generous exemptions for those engaged in private study or research. But even if the law is revised to contain a more sophisticated treatment of digitalization, most experts think it will be hard to resolve the clash between the Internet community, which is accustomed to treating information as raw material available for everyone to use, and the publishing community, which is accustomed to treating it as a commodity owned by its creator.`;

export const Lesson1_PassageAnalysis: Lesson = {
  id: "58-1",
  title: "Passage Analysis: Digitalization and Copyright Law",
  content: [
    { type: 'accordion', title: 'Read Passage', content: passageText },
    { type: 'h3', text: "Passage Analysis" },
    { type: 'h4', text: "Paragraph 1: The Problem - Free Info vs. Copyright" },
    { type: 'paragraph', text: "The passage kicks off by explaining a big conflict: the internet's culture of 'free information for everyone' is clashing with creators' need to protect their work. As more copyrighted material gets shared online, copyright holders are looking for ways to stop it, putting them in direct opposition to the goals of many internet users." },
    { type: 'h4', text: "Paragraph 2: Why the Law is Outdated" },
    { type: 'paragraph', text: "This paragraph explains the specific legal loophole. Canadian copyright law was written for the physical world and bans making unauthorized copies in a 'material form,' like a photocopy. But digitalization turns a work into electronic signals, not a physical object. The law isn't clear on whether this counts as 'material reproduction,' so making an unauthorized digital copy isn't technically illegal yet." },
    { type: 'h4', text: "Paragraph 3: Why Fixing the Law is Hard" },
    { type: 'paragraph', text: "The final paragraph explores why simply making digitalization a crime isn't an easy fix. The author brings up several major problems: (1) **What's the crime?** Is it just the first digital copy, or every copy made from it? (2) **How do you enforce it?** With millions of users, policing this would be nearly impossible. (3) **Who does it apply to?** The law already has big exceptions for academics, who are a huge group of users. The author concludes that even if the law is updated, the basic philosophical fight between the 'information wants to be free' internet culture and the 'information is a product' publishing world will be very hard to solve." },
    { type: 'callout', title: "Summary", variant: "summary", text: "The passage argues that current Canadian copyright law is unprepared for the digital age. It highlights a legal loophole that makes it hard to prosecute unauthorized digital copying. While changing the law seems like the obvious answer, the author explains that doing so is full of practical challenges and doesn't solve the deeper philosophical conflict between the internet's open-access culture and the publishing industry's view of information as property." }
  ]
};