import { Lesson } from '../../types';

const passageText = `Joy Kogawa’s Obasan is an account of a Japanese-Canadian family’s experiences during World War II. The events are seen from the viewpoint of a young girl who watches her family disintegrate as it undergoes the relocation that occurred in both Canada and the United States. Although the experience depicted in Obasan is mainly one of dislocation, Kogawa employs subtle techniques that serve to emphasize her major character’s heroism and to critique the majority culture. The former end is achieved through the novel’s form and the latter through the symbols it employs.

The form of the novel parallels the three-stage structure noted by anthropologists in their studies of rites of passage. According to these anthropologists, a rite of passage begins with separation from a position of security in a highly structured society; proceeds to alienation in a deathlike state where one is stripped of status, property, and rank; and concludes with reintegration into society accompanied by a heightened status gained as a result of the second stage. The process thus has the effect of transforming a society’s victim into a hero. The first eleven chapters of Obasan situate the young protagonist Naomi Nakane in a close-knit, securely placed family within Vancouver society. Chapters 12–32 chronicle the fall into alienation, when Naomi’s family is dislodged from its structured social niche and removed from the city into work camps or exile. Separated from her parents, Naomi follows her aunt Aya Obasan to the ghost town of Slocan, where Naomi joins the surrogate family of her uncle and aunt. In chapters 33–39 this surrogate family nurtures Naomi as she develops toward a final integration with the larger society and with herself: as an adult, when she receives a bundle of family documents and letters from her aunt, Naomi breaks through the personal and cultural screens of silence and secretiveness that have enshrouded her past, and reconciles herself with her history.

Kogawa’s use of motifs drawn from Christian rituals and symbols forms a subtle critique of the professed ethics of the majority culture that has shunned Naomi. In one example of such symbolism, Naomi’s reacquaintance with her past is compared with the biblical story of turning stone into bread. The bundle of documents—which Kogawa refers to as “stone-hard facts”—brings Naomi to the recognition of her country’s abuse of her people. But implicit in these hard facts, Kogawa suggests, is also the “bread” of a spiritual sustenance that will allow Naomi to affirm the durability of her people and herself. Through the careful deployment of structure and symbol, Kogawa thus manages to turn Naomi’s experience—and by extension the wartime experiences of many Japanese Canadians—into a journey of heroic transformation and a critique of the majority culture.`;

export const Lesson2_Question8: Lesson = {
  id: "39-2",
  title: "Question 8: Main Idea",
  content: [
    { type: 'accordion', title: 'Read Passage (PT-119-S-1-P-2)', content: passageText },
    { type: 'h3', text: "Question 8: Main Idea Breakdown (PT-119-S-1-P-2-Q-8)" },
    { type: 'blockquote', text: "**Question:** Which one of the following most accurately states the main idea of the passage?" },
    { type: 'options', items: [
      "(A) While telling a story of familial disruption, Obasan uses structure and symbolism to valorize its protagonist and critique the majority culture. (Correct)",
      "(B) By means of its structure and symbolism, Obasan mounts a harsh critique of a society that disrupts its citizens’ lives.",
      "(C) Although intended primarily as social criticism, given its structure Obasan can also be read as a tale of heroic transformation.",
      "(D) With its three-part structure that parallels rites of passage, Obasan manages to valorize its protagonist in spite of her traumatic experiences.",
      "(E) Although intended primarily as a story of heroic transformation, Obasan can also be read as a work of social criticism."
    ]},
    { type: 'h4', text: "Analysis" },
    { type: 'paragraph', text: "The main idea is a balanced two-part claim: Kogawa uses form to frame Naomi's heroic transformation and uses symbolism to critique the majority culture. The correct answer must preserve both techniques and both outcomes without making one side primary." },
    { type: 'callout', title: "Text Evidence", variant: "tip", text: "\"The former end is achieved through the novel's form and the latter through the symbols it employs.\" The close reinforces that dual structure: \"through the careful deployment of structure and symbol... heroic transformation and a critique of the majority culture.\"" },
    { 
      type: 'breakdown',
      labels: { title: 'Option', text: 'Analysis' },
      items: [
        { title: "(A) While telling a story of familial disruption, Obasan uses structure and symbolism to valorize its protagonist and critique the majority culture.", text: "Let's check this against our prediction. Does it mention the techniques? Yes, \"structure and symbolism.\" Does it mention the goals? Yes, \"valorize its protagonist\" (which is another way of saying make her a hero) and \"critique the majority culture.\" It also correctly identifies the novel's subject matter (\"familial disruption\"). This answer choice includes all the key components of the author's thesis. It looks very strong.", badge: "Correct", badgeColor: "green" },
        { title: "(B) By means of its structure and symbolism, Obasan mounts a harsh critique of a society that disrupts its citizens’ lives.", text: "This choice is a classic trap. Is it true? Yes, the novel does this. But is it the *main idea*? No, because it's incomplete. It correctly mentions the techniques (\"structure and symbolism\") and one of the goals (\"critique of a society\"), but it completely leaves out the other major goal: the protagonist's heroic transformation. A main idea must be complete, and this one is missing half the argument.", badge: "Incorrect", badgeColor: "red" },
        { title: "(C) Although intended primarily as social criticism, given its structure Obasan can also be read as a tale of heroic transformation.", text: "This choice creates a false hierarchy. It claims the novel is \"primarily\" social criticism. Does the author of the passage say that? No. The author presents the two goals—heroism and critique—as equally important parts of a dual project. This answer choice distorts the author's argument by prioritizing one goal over the other.", badge: "Incorrect", badgeColor: "red" },
        { title: "(D) With its three-part structure that parallels rites of passage, Obasan manages to valorize its protagonist in spite of her traumatic experiences.", text: "This is another incomplete answer, just like choice (B). It correctly identifies one technique (\"three-part structure\") and one goal (\"valorize its protagonist\"), but it completely ignores the other half of the author's argument: the use of symbolism to critique the culture. It's only half the story.", badge: "Incorrect", badgeColor: "red" },
        { title: "(E) Although intended primarily as a story of heroic transformation, Obasan can also be read as a work of social criticism.", text: "This is the same false hierarchy error we saw in choice (C), but flipped. It claims the \"heroic transformation\" is the primary goal. Again, the author of the passage presents these two aims as a matched pair, not as a primary and a secondary goal.", badge: "Incorrect", badgeColor: "red" }
      ]
    }
  ]
};
