#!/usr/bin/env node
/**
 * Scans the LR (Module 48), RC (Module 49), and Advanced RC (Module 53) repository
 * lesson files and writes REPOSITORY_GAPS.txt listing any accordion with missing ID
 * or placeholder/missing content.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const MODULES = path.join(ROOT, 'modules');
const OUTPUT_FILE = path.join(ROOT, 'REPOSITORY_GAPS.txt');

const PLACEHOLDER_PATTERNS = [
  '[Content in Module',
  '[Missing content]',
  '[Missing ID]',
  '[Missing ID or key content]',
];

function checkAccordion(title, contentSlice) {
  const issues = [];
  if (title.includes('[Missing ID]')) issues.push('Missing ID');
  for (const p of PLACEHOLDER_PATTERNS) {
    if (p !== '[Missing ID]' && contentSlice.includes(p)) {
      issues.push('Missing/placeholder content');
      break;
    }
  }
  return issues;
}

function extractAccordionsFromFile(filePath) {
  const text = fs.readFileSync(filePath, 'utf8');
  const accordions = [];
  // Title can contain escaped quotes (\' or \"), so match (?:[^'"\\]|\\.)*
  const accordionRegex = /type:\s*['"]accordion['"][\s\S]*?title:\s*['"]((?:[^'"\\]|\\.)*)['"][\s\S]*?content:\s*(\w+|\[)/g;
  let m;
  while ((m = accordionRegex.exec(text)) !== null) {
    const title = m[1].replace(/\\'/g, "'").replace(/\\"/g, '"');
    const contentStart = m.index + m[0].length;
    const nextAccordion = text.indexOf("type: 'accordion'", contentStart);
    const contentEnd = nextAccordion === -1 ? text.length : nextAccordion;
    const contentSlice = text.slice(contentStart, Math.min(contentStart + 2500, contentEnd));
    accordions.push({ title, contentSlice });
  }
  return accordions;
}

function scanLrRepo() {
  const dir = path.join(MODULES, 'module48');
  const lines = [];
  lines.push('=== LR Repository (Module 48) ===');
  const files = fs.readdirSync(dir).filter((f) => f.endsWith('.tsx') && f.includes('Module'));
  let count = 0;
  for (const file of files.sort()) {
    const filePath = path.join(dir, file);
    const accordions = extractAccordionsFromFile(filePath);
    for (const { title, contentSlice } of accordions) {
      const issues = checkAccordion(title, contentSlice);
      if (issues.length > 0) {
        lines.push(`  ${title}`);
        issues.forEach((i) => lines.push(`    - ${i}`));
        count++;
      }
    }
  }
  if (count === 0) lines.push('  None');
  lines.push('');
  return lines;
}

function scanRcRepo() {
  const filePath = path.join(MODULES, 'module49', 'Lesson1_QuestionRepository.tsx');
  const lines = [];
  lines.push('=== RC Repository (Module 49) ===');
  if (!fs.existsSync(filePath)) {
    lines.push('  File not found.');
    lines.push('');
    return lines;
  }
  const accordions = extractAccordionsFromFile(filePath);
  let count = 0;
  for (const { title, contentSlice } of accordions) {
    const issues = checkAccordion(title, contentSlice);
    if (issues.length > 0) {
      lines.push(`  ${title}`);
      issues.forEach((i) => lines.push(`    - ${i}`));
      count++;
    }
  }
  if (count === 0) lines.push('  None');
  lines.push('');
  return lines;
}

function scanAdvancedRcRepo() {
  const filePath = path.join(MODULES, 'module53', 'Lesson1_AdvancedRCQuestionRepository.tsx');
  const lines = [];
  lines.push('=== Advanced RC Repository (Module 53) ===');
  if (!fs.existsSync(filePath)) {
    lines.push('  File not found.');
    lines.push('');
    return lines;
  }
  const accordions = extractAccordionsFromFile(filePath);
  let count = 0;
  for (const { title, contentSlice } of accordions) {
    const issues = checkAccordion(title, contentSlice);
    if (issues.length > 0) {
      lines.push(`  ${title}`);
      issues.forEach((i) => lines.push(`    - ${i}`));
      count++;
    }
  }
  if (count === 0) lines.push('  None');
  lines.push('');
  return lines;
}

function main() {
  const sections = [
    ['LR Repository (Module 48)', scanLrRepo],
    ['RC Repository (Module 49)', scanRcRepo],
    ['Advanced RC Repository (Module 53)', scanAdvancedRcRepo],
  ];
  const out = [
    'REPOSITORY GAPS REPORT',
    '=====================',
    'Generated by scripts/repository-gaps.mjs',
    'Lists accordions with missing PT ID or placeholder/missing content.',
    '',
    ...scanLrRepo(),
    ...scanRcRepo(),
    ...scanAdvancedRcRepo(),
  ];
  fs.writeFileSync(OUTPUT_FILE, out.join('\n'), 'utf8');
  console.log(`Wrote ${OUTPUT_FILE}`);
}

main();
