import { Lesson } from '../../types';

const passageText = `In filmmaker Woody Allen’s Deconstructing Harry, the writer Harry Block is presented as extremely neurotic and narcissistic. Block uses his experiences as fodder for his work, no matter how embarrassing the result may be for the other people in his life. And while Allen exaggerates Block’s narcissism for comic effect, the effect is not simply comic: the film is emblematic of Allen’s career precisely because of its extravagantly exaggerated censure of a life dedicated to and obsessed with art. Deconstructing Harry may be the most unequivocally peevish of Allen’s depictions of artists, but it is less a new direction for Allen than a concentrated reprise of a theme present throughout his career.
For instance, a film producer in Stardust Memories, Allen’s sourest portrait of artists before Harry, articulates a particularly cynical view of cinematic art after a screening of a film-in-progress by Stardust Memories’ main character, Sandy Bates. The producer says of Bates, “His insights are shallow and morbid. I’ve seen it all before. They try to document their private suffering and fob it off as art.” The producer, like all the figures in this film, often seems less a distinct individual than a projection of Bates’s personal self-recriminations. This effectively reinforces the charge of solipsism with which Bates, the unstable and demoralized artist, indicts himself. Indeed, the possibility that artists are merely “documenting their private suffering and fobbing it off as art” appears sufficiently often in Allen’s films to seem an unresolved personal issue.
In Manhattan, the ex-wife of a television writer and aspiring novelist offers a denigratory take on the artistic enterprise that is similar to the producer’s in Stardust Memories. Her book documenting the collapse of her marriage punctures her ex-husband’s artistic pretensions by revealing that he “longed to be an artist but balked at the necessary sacrifices. In his most private moments, he spoke of the fear of death, which he elevated to tragic heights when, in fact, it was mere narcissism.”
It is also significant that in Allen’s films, the less artistic the characters, the more likely their narrative is to result in a happy ending. Thus, the filmmaker in Crimes and Misdemeanors, the novelist in Husbands and Wives, and the screenwriter in Celebrity all wind up desolate and solitary, largely because of the egocentric and exploitative attitudes embodied in their art and the effects of those attitudes on those around them. On the other hand, the unpretentious, thoroughly inartistic title character in Zelig dies an untroubled, even happy, death, only slightly compromised by his failure to finish reading Moby-Dick. And the title character and talent agent in Broadway Danny Rose is the beneficiary of the most gratifying resolution Allen has scripted, primarily due to altruistic devotion to his utterly talentless nightclub performers.`;

export const Lesson3_Question8: Lesson = {
      id: "42-3",
      title: "Question 8: Passage Principle",
      content: [
        { type: 'accordion', title: 'Read Passage (PT-128-S-4-P-2)', content: passageText },
        { type: 'h3', text: "Question 8: Passage Principle Breakdown (PT-128-S-4-P-2-Q-8)" },
        { type: 'blockquote', text: "**Question:** Which one of the following principles most likely underlies the author's argument?" },
        { type: 'options', items: [
          "(A) Critics should consider not only an individual film in isolation, but also its relation to the filmmaker’s entire body of work, when attempting to gauge that film’s artistic merit.",
          "(B) People who are not themselves artists should not presume to interpret films that take as their subject the artistic temperament.",
          "(C) The fate that a character in a movie meets can give an indication of the filmmaker’s views concerning his approval or disapproval of that character. (Correct)",
          "(D) The writer of a film’s screenplay should be considered only one of many contributors to the ultimate meaning of that film.",
          "(E) Prior work of a film’s cast members should be taken into account when assessing the artistic merits of a film."
        ]},
        { type: 'h4', text: "Analysis" },
        { type: 'paragraph', text: "Concept focus: this is a bridge-principle lesson. The author moves from evidence about story outcomes to a claim about Allen's viewpoint. The skill is to name the rule that makes that move valid. Here, the evidence is that artist characters end badly while inartistic characters end well. The unstated rule is that character outcomes can reveal what the filmmaker approves or disapproves." },
        { type: 'callout', title: "Text Evidence", variant: "tip", text: "Track the chain directly: (1) artist figures \"wind up desolate and solitary,\" (2) Zelig dies \"untroubled\" and Danny Rose gets \"the most gratifying resolution,\" so (3) Allen's endings are being read as judgments about those character types. The right answer must state step (3), not just repeat step (1) or (2)." },
        { type: 'breakdown', labels: { title: 'Option', text: 'Analysis' }, items: [
          { title: "(A) Critics should consider not only an individual film in isolation, but also its relation to the filmmaker’s entire body of work, when attempting to gauge that film’s artistic merit.", text: "This is a method claim, not a bridge claim. It may describe one way to do criticism, but it does not explain why endings in specific films justify conclusions about Allen's approval or disapproval.", badge: "Incorrect", badgeColor: "red" },
          { title: "(B) People who are not themselves artists should not presume to interpret films that take as their subject the artistic temperament.", text: "This would block the argument instead of supporting it. The author is interpreting the films directly, so a rule forbidding that interpretation cannot be the principle underneath the passage.", badge: "Incorrect", badgeColor: "red" },
          { title: "(C) The fate that a character in a movie meets can give an indication of the filmmaker’s views concerning his approval or disapproval of that character.", text: "This is the exact bridge the author needs. It links the observed ending pattern (artists miserable, inartistic characters rewarded) to the conclusion that Allen is judging those ways of life differently.", badge: "Correct", badgeColor: "green" },
          { title: "(D) The writer of a film’s screenplay should be considered only one of many contributors to the ultimate meaning of that film.", text: "This dilutes author-level inference, but the passage does the opposite: it treats recurring outcomes across Allen films as evidence of Allen's own stance. So this principle points away from the argument's logic.", badge: "Incorrect", badgeColor: "red" },
          { title: "(E) Prior work of a film’s cast members should be taken into account when assessing the artistic merits of a film.", text: "This introduces a new source of evidence the passage never uses. The argument is built from narrative outcomes and character treatment, not actor biography or cast history.", badge: "Incorrect", badgeColor: "red" }
        ]}
      ]
};
