import { Lesson } from '../../types';

const passageText = `In filmmaker Woody Allen’s Deconstructing Harry, the writer Harry Block is presented as extremely neurotic and narcissistic. Block uses his experiences as fodder for his work, no matter how embarrassing the result may be for the other people in his life. And while Allen exaggerates Block’s narcissism for comic effect, the effect is not simply comic: the film is emblematic of Allen’s career precisely because of its extravagantly exaggerated censure of a life dedicated to and obsessed with art. Deconstructing Harry may be the most unequivocally peevish of Allen’s depictions of artists, but it is less a new direction for Allen than a concentrated reprise of a theme present throughout his career.
For instance, a film producer in Stardust Memories, Allen’s sourest portrait of artists before Harry, articulates a particularly cynical view of cinematic art after a screening of a film-in-progress by Stardust Memories’ main character, Sandy Bates. The producer says of Bates, “His insights are shallow and morbid. I’ve seen it all before. They try to document their private suffering and fob it off as art.” The producer, like all the figures in this film, often seems less a distinct individual than a projection of Bates’s personal self-recriminations. This effectively reinforces the charge of solipsism with which Bates, the unstable and demoralized artist, indicts himself. Indeed, the possibility that artists are merely “documenting their private suffering and fobbing it off as art” appears sufficiently often in Allen’s films to seem an unresolved personal issue.
In Manhattan, the ex-wife of a television writer and aspiring novelist offers a denigratory take on the artistic enterprise that is similar to the producer’s in Stardust Memories. Her book documenting the collapse of her marriage punctures her ex-husband’s artistic pretensions by revealing that he “longed to be an artist but balked at the necessary sacrifices. In his most private moments, he spoke of the fear of death, which he elevated to tragic heights when, in fact, it was mere narcissism.”
It is also significant that in Allen’s films, the less artistic the characters, the more likely their narrative is to result in a happy ending. Thus, the filmmaker in Crimes and Misdemeanors, the novelist in Husbands and Wives, and the screenwriter in Celebrity all wind up desolate and solitary, largely because of the egocentric and exploitative attitudes embodied in their art and the effects of those attitudes on those around them. On the other hand, the unpretentious, thoroughly inartistic title character in Zelig dies an untroubled, even happy, death, only slightly compromised by his failure to finish reading Moby-Dick. And the title character and talent agent in Broadway Danny Rose is the beneficiary of the most gratifying resolution Allen has scripted, primarily due to altruistic devotion to his utterly talentless nightclub performers.`;

export const Lesson3_Question8: Lesson = {
      id: "42-3",
      title: "Question 8: Passage Principle",
      content: [
        { type: 'accordion', title: 'Read Passage', content: passageText },
        { type: 'h3', text: "Question Breakdown: PT-128-S-4-P-2-Q-8" },
        { type: 'blockquote', text: "**Question:** Which one of the following principles most likely underlies the author's argument?" },
        { type: 'options', items: [
          "(A) Critics should consider not only an individual film in isolation, but also its relation to the filmmaker’s entire body of work, when attempting to gauge that film’s artistic merit. [33.0%]",
          "(B) People who are not themselves artists should not presume to interpret films that take as their subject the artistic temperament. [1.0%]",
          "(C) The fate that a character in a movie meets can give an indication of the filmmaker’s views concerning his approval or disapproval of that character. [62.0%] (Correct)",
          "(D) The writer of a film’s screenplay should be considered only one of many contributors to the ultimate meaning of that film. [3.0%]",
          "(E) Prior work of a film’s cast members should be taken into account when assessing the artistic merits of a film. [1.0%]"
        ]},
        { type: 'paragraph', text: "This question asks for an unstated \"principle\" that \"underlies the author's argument.\" We must identify a core assumption the author makes to connect their evidence to their conclusions. This is not asking for the thesis itself, but for an interpretive belief that the author relies on to make the argument work." },
        { type: 'paragraph', text: "The clearest example of the author's reasoning is in the final paragraph. There, the author observes a pattern: artistic characters in Allen's films have unhappy endings, while inartistic characters have happy ones. From this observation, the author concludes that this pattern reflects Allen's \"censure\" (disapproval) of the artistic life." },
        { type: 'callout', title: "Prediction", variant: "tip", text: "For this logical leap to be valid, the author must believe that a character's narrative fate in a film is a reliable indicator of the filmmaker's own judgment of that character. In other words: if a filmmaker gives a character a bad ending, the filmmaker disapproves of what that character represents. Look for an answer that captures this bridge between narrative outcome and authorial intent." },
        { type: 'breakdown', labels: { title: 'Option', text: 'Analysis' }, items: [
          { title: "(A) Critics should consider not only an individual film in isolation, but also its relation to the filmmaker’s entire body of work, when attempting to gauge that film’s artistic merit.", text: "This describes the author's *method* of analysis, not the underlying interpretive principle. The author's belief in the principle described above is what *motivates* them to use this method—they are looking for a consistent pattern of judgment across the body of work.", badge: "Incorrect", badgeColor: "red" },
          { title: "(B) People who are not themselves artists should not presume to interpret films that take as their subject the artistic temperament.", text: "The author is clearly an interpreter of such films, so this principle contradicts their entire project.", badge: "Incorrect", badgeColor: "red" },
          { title: "(C) The fate that a character in a movie meets can give an indication of the filmmaker’s views concerning his approval or disapproval of that character.", text: "This is a perfect match for our prediction. The author uses the unhappy \"fate\" of artistic characters and the happy \"fate\" of inartistic ones to infer Allen's \"disapproval\" and \"approval,\" respectively. This principle is the foundation of the argument in the final paragraph.", badge: "Correct", badgeColor: "green" },
          { title: "(D) The writer of a film’s screenplay should be considered only one of many contributors to the ultimate meaning of that film.", text: "The author's analysis does the opposite. It consistently attributes the films' themes and meanings directly to \"Allen,\" treating him as the sole author or \"auteur\" whose vision is being expressed.", badge: "Incorrect", badgeColor: "red" },
          { title: "(E) Prior work of a film’s cast members should be taken into account when assessing the artistic merits of a film.", text: "The passage never mentions actors or their careers; the focus is entirely on Woody Allen as the filmmaker. This is irrelevant to the author's argument.", badge: "Incorrect", badgeColor: "red" }
        ]}
      ]
};
