import { Lesson } from '../../types';

const passageText = `In filmmaker Woody Allen’s Deconstructing Harry, the writer Harry Block is presented as extremely neurotic and narcissistic. Block uses his experiences as fodder for his work, no matter how embarrassing the result may be for the other people in his life. And while Allen exaggerates Block’s narcissism for comic effect, the effect is not simply comic: the film is emblematic of Allen’s career precisely because of its extravagantly exaggerated censure of a life dedicated to and obsessed with art. Deconstructing Harry may be the most unequivocally peevish of Allen’s depictions of artists, but it is less a new direction for Allen than a concentrated reprise of a theme present throughout his career.
For instance, a film producer in Stardust Memories, Allen’s sourest portrait of artists before Harry, articulates a particularly cynical view of cinematic art after a screening of a film-in-progress by Stardust Memories’ main character, Sandy Bates. The producer says of Bates, “His insights are shallow and morbid. I’ve seen it all before. They try to document their private suffering and fob it off as art.” The producer, like all the figures in this film, often seems less a distinct individual than a projection of Bates’s personal self-recriminations. This effectively reinforces the charge of solipsism with which Bates, the unstable and demoralized artist, indicts himself. Indeed, the possibility that artists are merely “documenting their private suffering and fobbing it off as art” appears sufficiently often in Allen’s films to seem an unresolved personal issue.
In Manhattan, the ex-wife of a television writer and aspiring novelist offers a denigratory take on the artistic enterprise that is similar to the producer’s in Stardust Memories. Her book documenting the collapse of her marriage punctures her ex-husband’s artistic pretensions by revealing that he “longed to be an artist but balked at the necessary sacrifices. In his most private moments, he spoke of the fear of death, which he elevated to tragic heights when, in fact, it was mere narcissism.”
It is also significant that in Allen’s films, the less artistic the characters, the more likely their narrative is to result in a happy ending. Thus, the filmmaker in Crimes and Misdemeanors, the novelist in Husbands and Wives, and the screenwriter in Celebrity all wind up desolate and solitary, largely because of the egocentric and exploitative attitudes embodied in their art and the effects of those attitudes on those around them. On the other hand, the unpretentious, thoroughly inartistic title character in Zelig dies an untroubled, even happy, death, only slightly compromised by his failure to finish reading Moby-Dick. And the title character and talent agent in Broadway Danny Rose is the beneficiary of the most gratifying resolution Allen has scripted, primarily due to altruistic devotion to his utterly talentless nightclub performers.`;

export const Lesson1_PassageAnalysis: Lesson = {
      id: "42-1",
      title: "Passage Analysis",
      content: [
        { type: 'accordion', title: 'Read Passage', content: passageText },
        { type: 'h3', text: "Passage Analysis: PT-128-S-4-P-2" },
        { type: 'paragraph', text: "This passage is a piece of film criticism that makes an argument about a pattern across Woody Allen's career. The author is not simply reviewing a single film; they are using one film as a launching pad to identify a recurring thematic preoccupation. Our job is to track the thesis, the evidence, and the logical structure connecting them." },
        { type: 'hr' },
        { type: 'h4', text: "Paragraph 1: The Thesis and the Prime Example" },
        { type: 'paragraph', text: "The first paragraph introduces the film *Deconstructing Harry* and its protagonist, the \"extremely neurotic and narcissistic\" writer Harry Block. Block uses the people in his life as material for his work, regardless of the consequences. The author argues that while Allen exaggerates this narcissism for comedy, the effect is deeper than comedy: the film is an \"extravagantly exaggerated censure\" of a life obsessed with art." },
        { type: 'paragraph', text: "The final sentence of the paragraph delivers the central thesis: *Deconstructing Harry*, while perhaps the most \"unequivocally peevish\" of Allen's portraits of artists, is not a new direction but rather a \"concentrated reprise of a theme present throughout his career.\" This sentence is the roadmap for the rest of the passage. Everything that follows is evidence for this claim of consistency." },
        { type: 'hr' },
        { type: 'h4', text: "Paragraph 2: Supporting Evidence, Part 1 — *Stardust Memories*" },
        { type: 'paragraph', text: "To prove this is a recurring theme, the author turns to an earlier film, *Stardust Memories*, which is described as \"Allen's sourest portrait of artists before Harry.\" A cynical film producer criticizes the artist protagonist Sandy Bates, saying, \"They try to document their private suffering and fob it off as art.\"" },
        { type: 'paragraph', text: "The author then adds a more sophisticated layer of analysis. They suggest that this producer, \"like all the figures in this film,\" may not be a truly independent character but rather a \"projection of Bates's personal self-recriminations.\" This means the critique is coming from *inside* the artist's own mind, reinforcing the charge of \"solipsism.\" The paragraph concludes with a powerful observation: this specific critique appears \"sufficiently often\" in Allen's films to seem an \"unresolved personal issue\" for the filmmaker himself. This bridges the gap from analyzing the art to analyzing the artist." },
        { type: 'hr' },
        { type: 'h4', text: "Paragraph 3: Supporting Evidence, Part 2 — *Manhattan*" },
        { type: 'paragraph', text: "The third paragraph adds another piece of evidence from the film *Manhattan*. The ex-wife of a television writer publishes a book about their collapsed marriage that punctures his artistic pretensions. The key quote reveals that his fear of death, which he treated as something profound and tragic, was in fact \"mere narcissism.\"" },
        { type: 'paragraph', text: "Notice how the author explicitly connects this example back to the previous one, stating it is \"similar to the producer's in *Stardust Memories*.\" This linking language reinforces the claim from paragraph two that the theme recurs \"sufficiently often\" to constitute a pattern." },
        { type: 'hr' },
        { type: 'h4', text: "Paragraph 4: The Final Proof — The Inverse Correlation" },
        { type: 'paragraph', text: "The final paragraph presents the author's most powerful and broadest evidence: a systematic pattern across Allen's entire filmography. The author identifies an inverse correlation between a character's artistic nature and the happiness of their narrative outcome." },
        { type: 'paragraph', text: "On one side, artistic characters in films like *Crimes and Misdemeanors*, *Husbands and Wives*, and *Celebrity* all end up \"desolate and solitary,\" largely due to the \"egocentric and exploitative attitudes embodied in their art.\" On the other side, the \"thoroughly inartistic\" title character in *Zelig* dies happy, and the talent agent in *Broadway Danny Rose* receives \"the most gratifying resolution Allen has scripted,\" primarily due to his \"altruistic devotion\" to talentless performers." },
        { type: 'paragraph', text: "By showing that this is not just a matter of dialogue or quotes, but a structural feature of Allen's storytelling, the author completes their case. The critique of the artistic life is not just something characters *say* in Allen's films; it is embedded in the very way Allen constructs his narratives." },
        { type: 'callout', title: "Summary of the Argument", variant: "summary", text: "• **The Central Thesis:** The passage argues that a sustained critique of the artist's life — portraying artists as narcissistic, solipsistic, and exploitative — is a central, recurring theme in Woody Allen's films. *Deconstructing Harry* is the most intense expression of this career-long preoccupation, not a new direction.\n• **Evidence from Dialogue:** The author supports this claim with direct quotes and character critiques from *Stardust Memories* and *Manhattan*, where characters accuse artists of packaging their private suffering as art and being driven by narcissism. The author notes that the critique in *Stardust Memories* may even be a projection of the artist's own self-doubt.\n• **Evidence from Narrative Outcomes:** The most compelling evidence is a structural pattern: artistic characters consistently end up miserable and alone, while inartistic, altruistic characters are rewarded with happy endings. This shows the critique is embedded in the very fabric of Allen's storytelling, not just in his dialogue." }
      ]
};
