import { Lesson } from '../../types';

const passageText = `In filmmaker Woody Allen’s Deconstructing Harry, the writer Harry Block is presented as extremely neurotic and narcissistic. Block uses his experiences as fodder for his work, no matter how embarrassing the result may be for the other people in his life. And while Allen exaggerates Block’s narcissism for comic effect, the effect is not simply comic: the film is emblematic of Allen’s career precisely because of its extravagantly exaggerated censure of a life dedicated to and obsessed with art. Deconstructing Harry may be the most unequivocally peevish of Allen’s depictions of artists, but it is less a new direction for Allen than a concentrated reprise of a theme present throughout his career.
For instance, a film producer in Stardust Memories, Allen’s sourest portrait of artists before Harry, articulates a particularly cynical view of cinematic art after a screening of a film-in-progress by Stardust Memories’ main character, Sandy Bates. The producer says of Bates, “His insights are shallow and morbid. I’ve seen it all before. They try to document their private suffering and fob it off as art.” The producer, like all the figures in this film, often seems less a distinct individual than a projection of Bates’s personal self-recriminations. This effectively reinforces the charge of solipsism with which Bates, the unstable and demoralized artist, indicts himself. Indeed, the possibility that artists are merely “documenting their private suffering and fobbing it off as art” appears sufficiently often in Allen’s films to seem an unresolved personal issue.
In Manhattan, the ex-wife of a television writer and aspiring novelist offers a denigratory take on the artistic enterprise that is similar to the producer’s in Stardust Memories. Her book documenting the collapse of her marriage punctures her ex-husband’s artistic pretensions by revealing that he “longed to be an artist but balked at the necessary sacrifices. In his most private moments, he spoke of the fear of death, which he elevated to tragic heights when, in fact, it was mere narcissism.”
It is also significant that in Allen’s films, the less artistic the characters, the more likely their narrative is to result in a happy ending. Thus, the filmmaker in Crimes and Misdemeanors, the novelist in Husbands and Wives, and the screenwriter in Celebrity all wind up desolate and solitary, largely because of the egocentric and exploitative attitudes embodied in their art and the effects of those attitudes on those around them. On the other hand, the unpretentious, thoroughly inartistic title character in Zelig dies an untroubled, even happy, death, only slightly compromised by his failure to finish reading Moby-Dick. And the title character and talent agent in Broadway Danny Rose is the beneficiary of the most gratifying resolution Allen has scripted, primarily due to altruistic devotion to his utterly talentless nightclub performers.`;

export const Lesson1_PassageAnalysis: Lesson = {
  id: "42-1",
  title: "Passage Analysis",
  content: [
    { type: 'accordion', title: 'Read Passage (PT-128-S-4-P-2)', content: passageText },
    { type: 'h3', text: "Passage Analysis: Woody Allen and the Artist Figure (PT-128-S-4-P-2)" },
    { type: 'paragraph', text: "The passage argues that Allen repeatedly portrays artistic identity as morally and psychologically corrosive. *Deconstructing Harry* is presented not as an outlier but as the sharpest version of a recurring critique." },
    { type: 'paragraph', text: "Read the structure as cumulative proof. Paragraph 1 states the claim, Paragraphs 2-3 supply textual evidence from earlier films, and Paragraph 4 broadens the case by identifying a cross-film pattern in narrative outcomes." },
    { type: 'hr' },
    { type: 'h4', text: "Paragraph 1: Thesis Framed Through *Deconstructing Harry*" },
    { type: 'paragraph', text: "The opening paragraph introduces Harry Block as emblematic of Allen's artistic self-critique. Comedy is treated as surface; the deeper function is censure of a life organized around self-regarding artistic production." },
    { type: 'paragraph', text: "Its key move is historical framing: the film condenses a theme that, according to the author, has appeared throughout Allen's career." },
    { type: 'h4', text: "Paragraph 2: First Line of Evidence from *Stardust Memories*" },
    { type: 'paragraph', text: "The second paragraph supports the thesis with explicit dialogue that equates art with self-display and private suffering. It then intensifies the claim by suggesting the critic figure may voice the artist's own self-indictment." },
    { type: 'paragraph', text: "This paragraph therefore does more than quote: it uses the quote to argue that Allen repeatedly stages accusations of artistic solipsism from within his narratives." },
    { type: 'h4', text: "Paragraph 3: Reinforcement Through *Manhattan*" },
    { type: 'paragraph', text: "The third paragraph adds parallel evidence. A second film again links artistic aspiration with narcissism, reinforcing consistency across works rather than a one-off rhetorical flourish." },
    { type: 'paragraph', text: "Functionally, this paragraph strengthens reliability by showing the pattern survives a change in character and context." },
    { type: 'h4', text: "Paragraph 4: Macro Pattern in Narrative Outcomes" },
    { type: 'paragraph', text: "The final paragraph shifts from quotation-level evidence to structural evidence. Across multiple films, artistic characters end in isolation, while less artistic and more relational characters receive stable or positive resolutions." },
    { type: 'paragraph', text: "This broad distribution of endings is presented as the passage's strongest proof that Allen's critique is built into narrative design, not just isolated dialogue choices." },
    { type: 'callout', title: "Summary of the Argument", variant: "summary", text: "The passage claims that Allen consistently critiques the artist figure as narcissistic and ethically compromised. It supports that claim first through repeated character judgments in individual films, then through a broader pattern in endings where artistic self-absorption correlates with isolation and inartistic generosity correlates with reward." }
  ]
};
