import { Lesson } from '../../types';

const passageText = `In filmmaker Woody Allen's Deconstructing Harry, the writer Harry Block is presented as extremely neurotic and narcissistic. Block uses his experiences as fodder for his work, no matter how embarrassing the result may be for the other people in his life. And while Allen exaggerates Block's narcissism for comic effect, the effect is not simply comic: the film is emblematic of Allen's career precisely because of its extravagantly exaggerated censure of a life dedicated to and obsessed with art. Deconstructing Harry may be the most unequivocally peevish of Allen's depictions of artists, but it is less a new direction for Allen than a concentrated reprise of a theme present throughout his career.
For instance, a film producer in Stardust Memories, Allen's sourest portrait of artists before Harry, articulates a particularly cynical view of cinematic art after a screening of a film-in-progress by Stardust Memories' main character, Sandy Bates. The producer says of Bates, \u201cHis insights are shallow and morbid. I've seen it all before. They try to document their private suffering and fob it off as art.\u201d The producer, like all the figures in this film, often seems less a distinct individual than a projection of Bates's personal self-recriminations. This effectively reinforces the charge of solipsism with which Bates, the unstable and demoralized artist, indicts himself. Indeed, the possibility that artists are merely \u201cdocumenting their private suffering and fobbing it off as art\u201d appears sufficiently often in Allen's films to seem an unresolved personal issue.
In Manhattan, the ex-wife of a television writer and aspiring novelist offers a denigratory take on the artistic enterprise that is similar to the producer's in Stardust Memories. Her book documenting the collapse of her marriage punctures her ex-husband's artistic pretensions by revealing that he \u201clonged to be an artist but balked at the necessary sacrifices. In his most private moments, he spoke of the fear of death, which he elevated to tragic heights when, in fact, it was mere narcissism.\u201d
It is also significant that in Allen's films, the less artistic the characters, the more likely their narrative is to result in a happy ending. Thus, the filmmaker in Crimes and Misdemeanors, the novelist in Husbands and Wives, and the screenwriter in Celebrity all wind up desolate and solitary, largely because of the egocentric and exploitative attitudes embodied in their art and the effects of those attitudes on those around them. On the other hand, the unpretentious, thoroughly inartistic title character in Zelig dies an untroubled, even happy, death, only slightly compromised by his failure to finish reading Moby-Dick. And the title character and talent agent in Broadway Danny Rose is the beneficiary of the most gratifying resolution Allen has scripted, primarily due to altruistic devotion to his utterly talentless nightclub performers.`;

export const Lesson7_Question12: Lesson = {
      id: "42-7",
      title: "Question 12: Author Viewpoint",
      content: [
        { type: 'accordion', title: 'Read Passage', content: passageText },
        { type: 'h3', text: "Question Breakdown: PT-128-S-4-P-2-Q-12" },
        { type: 'blockquote', text: "**Question:** The author of the passage would be most likely to agree with which one of the following statements?" },
        { type: 'options', items: [
          "(A) Most people who consider themselves to be artists are merely documenting their personal suffering and fobbing it off as art. [4.0%]",
          "(B) The continuing presence of a topic in an artist's work suggests that the topic is likely an issue in the artist's personal life. [87.0%] (Correct)",
          "(C) Allen's film career is unique in that he regularly features unhappy, narcissistic artists as protagonists. [7.0%]",
          "(D) An artist must use his or her own experiences as the source of inspiration for a work in order for that work to be considered truly artistic. [1.0%]",
          "(E) Allen's films accurately reflect real life in depicting inartistic individuals as happier than artists. [1.0%]"
        ]},
        { type: 'paragraph', text: "This question asks for a view that the \"author most likely holds.\" This is an inference question that requires us to identify a belief or assumption that informs the author's own analysis. We are not looking for a claim made *about* Allen's films, but a general principle the author must believe in order to draw their specific conclusions." },
        { type: 'paragraph', text: "The strongest clue to the author's personal interpretive framework comes at the end of the second paragraph. After detailing how the theme of artists \"fobbing it off as art\" appears in *Stardust Memories*, the author makes a crucial leap from analyzing the art to analyzing the artist: \"...[the theme] appears sufficiently often in Allen's films to seem an **unresolved personal issue**.\"" },
        { type: 'callout', title: "Prediction", variant: "tip", text: "The logic here is: a recurring theme in an artist's work points to a personal preoccupation in the artist's own life. The author must believe this general principle to be true in order to draw this specific conclusion about Woody Allen. Look for an answer that captures this inferential rule: recurring topic in art = personal issue for the artist." },
        { type: 'breakdown', labels: { title: 'Option', text: 'Analysis' }, items: [
          { title: "(A) Most people who consider themselves to be artists are merely documenting their personal suffering and fobbing it off as art.", text: "This is a description of a *theme* within Allen's films, not a view held by the author. The author is analyzing this viewpoint as it appears in the films, not endorsing it as a general truth about the real world.", badge: "Incorrect", badgeColor: "red" },
          { title: "(B) The continuing presence of a topic in an artist's work suggests that the topic is likely an issue in the artist's personal life.", text: "This is a perfect generalization of the logic the author uses at the end of the second paragraph. The \"continuing presence\" (\"appears sufficiently often\") of a topic suggests it is a \"personal issue.\" This is the interpretive principle the author demonstrably holds and relies upon to make their argument.", badge: "Correct", badgeColor: "green" },
          { title: "(C) Allen's film career is unique in that he regularly features unhappy, narcissistic artists as protagonists.", text: "The passage never uses words like \"unique\" or compares Allen's career to that of other filmmakers. Without such a comparison, we cannot infer that the author believes his career is unique in this regard. The author identifies a pattern in Allen's work but says nothing about whether other filmmakers share this pattern.", badge: "Incorrect", badgeColor: "red" },
          { title: "(D) An artist must use his or her own experiences as the source of inspiration for a work in order for that work to be considered truly artistic.", text: "The author's analysis is descriptive, not prescriptive. The passage never makes a judgment about what is required for a work to be \"truly artistic.\" It describes what Allen's characters do, not what artists in general must do.", badge: "Incorrect", badgeColor: "red" },
          { title: "(E) Allen's films accurately reflect real life in depicting inartistic individuals as happier than artists.", text: "The author identifies this pattern in Allen's films as a way to understand Allen's *views*, but they never make the additional claim that this pattern is an \"accurate reflection of real life.\" The analysis remains focused on the films as artistic texts, not as sociological documents about the real world.", badge: "Incorrect", badgeColor: "red" }
        ]}
      ]
};
