import { Lesson } from '../../types';

const passageText = `In filmmaker Woody Allen’s Deconstructing Harry, the writer Harry Block is presented as extremely neurotic and narcissistic. Block uses his experiences as fodder for his work, no matter how embarrassing the result may be for the other people in his life. And while Allen exaggerates Block’s narcissism for comic effect, the effect is not simply comic: the film is emblematic of Allen’s career precisely because of its extravagantly exaggerated censure of a life dedicated to and obsessed with art. Deconstructing Harry may be the most unequivocally peevish of Allen’s depictions of artists, but it is less a new direction for Allen than a concentrated reprise of a theme present throughout his career.
For instance, a film producer in Stardust Memories, Allen’s sourest portrait of artists before Harry, articulates a particularly cynical view of cinematic art after a screening of a film-in-progress by Stardust Memories’ main character, Sandy Bates. The producer says of Bates, “His insights are shallow and morbid. I’ve seen it all before. They try to document their private suffering and fob it off as art.” The producer, like all the figures in this film, often seems less a distinct individual than a projection of Bates’s personal self-recriminations. This effectively reinforces the charge of solipsism with which Bates, the unstable and demoralized artist, indicts himself. Indeed, the possibility that artists are merely “documenting their private suffering and fobbing it off as art” appears sufficiently often in Allen’s films to seem an unresolved personal issue.
In Manhattan, the ex-wife of a television writer and aspiring novelist offers a denigratory take on the artistic enterprise that is similar to the producer’s in Stardust Memories. Her book documenting the collapse of her marriage punctures her ex-husband’s artistic pretensions by revealing that he “longed to be an artist but balked at the necessary sacrifices. In his most private moments, he spoke of the fear of death, which he elevated to tragic heights when, in fact, it was mere narcissism.”
It is also significant that in Allen’s films, the less artistic the characters, the more likely their narrative is to result in a happy ending. Thus, the filmmaker in Crimes and Misdemeanors, the novelist in Husbands and Wives, and the screenwriter in Celebrity all wind up desolate and solitary, largely because of the egocentric and exploitative attitudes embodied in their art and the effects of those attitudes on those around them. On the other hand, the unpretentious, thoroughly inartistic title character in Zelig dies an untroubled, even happy, death, only slightly compromised by his failure to finish reading Moby-Dick. And the title character and talent agent in Broadway Danny Rose is the beneficiary of the most gratifying resolution Allen has scripted, primarily due to altruistic devotion to his utterly talentless nightclub performers.`;

export const Lesson1_PassageAnalysis: Lesson = {
      id: "42-1",
      title: "Passage Analysis",
      content: [
        { type: 'accordion', title: 'Read Passage', content: passageText },
        { type: 'h3', text: "Passage Analysis" },
        { type: 'h4', text: "Paragraph 1: The Thesis and the Prime Example" },
        { type: 'paragraph', text: "The first paragraph introduces the film *Deconstructing Harry* and its protagonist, the \"extremely neurotic and narcissistic\" writer Harry Block. This character serves as the author's primary piece of evidence. The author argues that while the film is a comedy, its real significance is how it serves as an \"extravagantly exaggerated censure\" of a life obsessed with art. The author then lays out the central thesis: *Deconstructing Harry*, while perhaps the most \"peevish\" of Allen's portraits of artists, is not a new idea for him but a \"concentrated reprise of a theme present throughout his career.\"" },
        { type: 'h4', text: "Paragraph 2: Supporting Evidence, Part 1 - *Stardust Memories*" },
        { type: 'paragraph', text: "To prove this is a recurring theme, the author cites an earlier film, *Stardust Memories*. A cynical film producer criticizes the artist protagonist, saying, \"They try to document their private suffering and fob it off as art.\" The author adds another layer of analysis, suggesting this producer may be a \"projection of [the artist's] personal self-recriminations,\" reinforcing the charge of solipsism. The author concludes that this specific critique appears so often in Allen's work that it seems to be an \"unresolved personal issue\" for the filmmaker himself." },
        { type: 'h4', text: "Paragraph 3: Supporting Evidence, Part 2 - *Manhattan*" },
        { type: 'paragraph', text: "The third paragraph provides more evidence from the film *Manhattan*. The ex-wife of a writer exposes his artistic pretensions, claiming his supposedly profound fear of death was \"mere narcissism.\" This serves as another clear example of the recurring theme of the artist as a self-centered pretender." },
        { type: 'h4', text: "Paragraph 4: The Final Proof - The Inverse Correlation" },
        { type: 'paragraph', text: "This paragraph presents the author's most powerful evidence by identifying a broad pattern across many of Allen's films: an inverse correlation between being an artist and achieving a happy ending. The author notes that artistic characters in films like *Crimes and Misdemeanors* and *Celebrity* end up \"desolate and solitary\" due to their \"egocentric and exploitative attitudes.\" In contrast, unpretentious, \"thoroughly inartistic\" characters like Zelig and Broadway Danny Rose are rewarded with happy and gratifying resolutions, often due to their altruism. This narrative pattern is presented as the ultimate proof of Allen's deep-seated critique of the artistic life." },
        { type: 'h4', text: "Summary" },
        { type: 'list', items: [
            "**The Central Thesis:** The passage argues that a sustained critique of the artist's life—portraying artists as narcissistic, solipsistic, and exploitative—is a central, recurring theme in Woody Allen's films. *Deconstructing Harry* is the most intense expression of this career-long preoccupation.",
            "**Evidence from Dialogue:** The author supports this claim with direct quotes and character critiques from films like *Stardust Memories* and *Manhattan*, where characters accuse artists of packaging their private suffering as art and being driven by narcissism.",
            "**Evidence from Narrative Outcomes:** The most compelling evidence is a structural pattern across Allen's filmography. Artistic characters consistently end up miserable and alone, while inartistic, altruistic characters are rewarded with happy endings."
        ]}
      ]
};
