import { Lesson } from '../../types';

const passageText = `In filmmaker Woody Allen’s Deconstructing Harry, the writer Harry Block is presented as extremely neurotic and narcissistic. Block uses his experiences as fodder for his work, no matter how embarrassing the result may be for the other people in his life. And while Allen exaggerates Block’s narcissism for comic effect, the effect is not simply comic: the film is emblematic of Allen’s career precisely because of its extravagantly exaggerated censure of a life dedicated to and obsessed with art. Deconstructing Harry may be the most unequivocally peevish of Allen’s depictions of artists, but it is less a new direction for Allen than a concentrated reprise of a theme present throughout his career.
For instance, a film producer in Stardust Memories, Allen’s sourest portrait of artists before Harry, articulates a particularly cynical view of cinematic art after a screening of a film-in-progress by Stardust Memories’ main character, Sandy Bates. The producer says of Bates, “His insights are shallow and morbid. I’ve seen it all before. They try to document their private suffering and fob it off as art.” The producer, like all the figures in this film, often seems less a distinct individual than a projection of Bates’s personal self-recriminations. This effectively reinforces the charge of solipsism with which Bates, the unstable and demoralized artist, indicts himself. Indeed, the possibility that artists are merely “documenting their private suffering and fobbing it off as art” appears sufficiently often in Allen’s films to seem an unresolved personal issue.
In Manhattan, the ex-wife of a television writer and aspiring novelist offers a denigratory take on the artistic enterprise that is similar to the producer’s in Stardust Memories. Her book documenting the collapse of her marriage punctures her ex-husband’s artistic pretensions by revealing that he “longed to be an artist but balked at the necessary sacrifices. In his most private moments, he spoke of the fear of death, which he elevated to tragic heights when, in fact, it was mere narcissism.”
It is also significant that in Allen’s films, the less artistic the characters, the more likely their narrative is to result in a happy ending. Thus, the filmmaker in Crimes and Misdemeanors, the novelist in Husbands and Wives, and the screenwriter in Celebrity all wind up desolate and solitary, largely because of the egocentric and exploitative attitudes embodied in their art and the effects of those attitudes on those around them. On the other hand, the unpretentious, thoroughly inartistic title character in Zelig dies an untroubled, even happy, death, only slightly compromised by his failure to finish reading Moby-Dick. And the title character and talent agent in Broadway Danny Rose is the beneficiary of the most gratifying resolution Allen has scripted, primarily due to altruistic devotion to his utterly talentless nightclub performers.`;

export const Lesson2_Question7: Lesson = {
      id: "42-2",
      title: "Question 7: Main Idea",
      content: [
        { type: 'accordion', title: 'Read Passage (PT-128-S-4-P-2)', content: passageText },
        { type: 'h3', text: "Question 7: Main Idea Breakdown (PT-128-S-4-P-2-Q-7)" },
        { type: 'blockquote', text: "**Question:** Which one of the following most accurately states the main point of the passage?" },
        { type: 'options', items: [
          "(A) The theme of the neurotic and narcissistic nature of artists is, though most intensely presented in Deconstructing Harry, one that Woody Allen has explored throughout his career. (Correct)",
          "(B) Woody Allen’s films suggest, by means of their depictions of artists, that the pursuit of an artistic life leads to unhappiness and that happiness is most often achieved by the inartistic.",
          "(C) Deconstructing Harry, like many of Woody Allen’s films, shows that the creation of art requires sacrifice, though many would-be artists are unable or unwilling to give up their comforts to create enduring works.",
          "(D) Woody Allen’s career indicates that, like most artists, he uses his own experiences and neuroses to create the works for which he has received the greatest acclaim.",
          "(E) Woody Allen’s films show that artists are unavoidably narcissistic and neurotic and that they are, because of this, able to produce works of great beauty and power."
        ]},
        { type: 'h4', text: "Analysis" },
        { type: 'paragraph', text: "Read the first paragraph as the author's main claim: *Deconstructing Harry* is the strongest example of a pattern Allen has used for years, not a brand-new direction. The rest of the passage then backs that up with examples from *Stardust Memories*, *Manhattan*, and the contrast between unhappy artist characters and happier inartistic characters." },
        { type: 'callout', title: "Text Evidence", variant: "tip", text: "Focus on three lines: \"less a new direction ... than a concentrated reprise of a theme present throughout his career,\" \"appears sufficiently often,\" and \"the less artistic the characters, the more likely ... a happy ending.\" The best answer states the first line directly and treats the other two as backup." },
        { type: 'breakdown', labels: { title: 'Option', text: 'Analysis' }, items: [
          { title: "(A) The theme of the neurotic and narcissistic nature of artists is, though most intensely presented in Deconstructing Harry, one that Woody Allen has explored throughout his career.", text: "This is the thesis almost verbatim. It captures both parts the passage insists on: *Deconstructing Harry* is the strongest case, and the theme is longstanding across Allen's body of work.", badge: "Correct", badgeColor: "green" },
          { title: "(B) Woody Allen’s films suggest, by means of their depictions of artists, that the pursuit of an artistic life leads to unhappiness and that happiness is most often achieved by the inartistic.", text: "This point is in the passage, but it appears as one example near the end, not the central claim that guides the whole piece. The passage's main message is that Allen returns to this artist critique across his career.", badge: "Incorrect", badgeColor: "red" },
          { title: "(C) Deconstructing Harry, like many of Woody Allen’s films, shows that the creation of art requires sacrifice, though many would-be artists are unable or unwilling to give up their comforts to create enduring works.", text: "This overweights one quoted detail from *Manhattan* (\"necessary sacrifices\") and promotes it to main point status. It also adds \"enduring works,\" language the passage never endorses, while sidelining the central narcissism/solipsism critique.", badge: "Incorrect", badgeColor: "red" },
          { title: "(D) Woody Allen’s career indicates that, like most artists, he uses his own experiences and neuroses to create the works for which he has received the greatest acclaim.", text: "The passage never claims Allen is like \"most artists,\" and it never discusses which works received his \"greatest acclaim.\" That makes this choice partly speculative biography and partly unsupported comparison.", badge: "Incorrect", badgeColor: "red" },
          { title: "(E) Woody Allen’s films show that artists are unavoidably narcissistic and neurotic and that they are, because of this, able to produce works of great beauty and power.", text: "The second half directly conflicts with the evidence quoted in paragraph two: the art is described as \"shallow and morbid,\" not beautiful or elevating. The wording \"unavoidably\" also overstates what the passage argues.", badge: "Incorrect", badgeColor: "red" }
        ]}
      ]
};
