import { Lesson } from '../../types';

const passageText = `In filmmaker Woody Allen’s Deconstructing Harry, the writer Harry Block is presented as extremely neurotic and narcissistic. Block uses his experiences as fodder for his work, no matter how embarrassing the result may be for the other people in his life. And while Allen exaggerates Block’s narcissism for comic effect, the effect is not simply comic: the film is emblematic of Allen’s career precisely because of its extravagantly exaggerated censure of a life dedicated to and obsessed with art. Deconstructing Harry may be the most unequivocally peevish of Allen’s depictions of artists, but it is less a new direction for Allen than a concentrated reprise of a theme present throughout his career.
For instance, a film producer in Stardust Memories, Allen’s sourest portrait of artists before Harry, articulates a particularly cynical view of cinematic art after a screening of a film-in-progress by Stardust Memories’ main character, Sandy Bates. The producer says of Bates, “His insights are shallow and morbid. I’ve seen it all before. They try to document their private suffering and fob it off as art.” The producer, like all the figures in this film, often seems less a distinct individual than a projection of Bates’s personal self-recriminations. This effectively reinforces the charge of solipsism with which Bates, the unstable and demoralized artist, indicts himself. Indeed, the possibility that artists are merely “documenting their private suffering and fobbing it off as art” appears sufficiently often in Allen’s films to seem an unresolved personal issue.
In Manhattan, the ex-wife of a television writer and aspiring novelist offers a denigratory take on the artistic enterprise that is similar to the producer’s in Stardust Memories. Her book documenting the collapse of her marriage punctures her ex-husband’s artistic pretensions by revealing that he “longed to be an artist but balked at the necessary sacrifices. In his most private moments, he spoke of the fear of death, which he elevated to tragic heights when, in fact, it was mere narcissism.”
It is also significant that in Allen’s films, the less artistic the characters, the more likely their narrative is to result in a happy ending. Thus, the filmmaker in Crimes and Misdemeanors, the novelist in Husbands and Wives, and the screenwriter in Celebrity all wind up desolate and solitary, largely because of the egocentric and exploitative attitudes embodied in their art and the effects of those attitudes on those around them. On the other hand, the unpretentious, thoroughly inartistic title character in Zelig dies an untroubled, even happy, death, only slightly compromised by his failure to finish reading Moby-Dick. And the title character and talent agent in Broadway Danny Rose is the beneficiary of the most gratifying resolution Allen has scripted, primarily due to altruistic devotion to his utterly talentless nightclub performers.`;

export const Lesson7_Question12: Lesson = {
      id: "42-7",
      title: "Question 12: Author Viewpoint",
      content: [
        { type: 'accordion', title: 'Read Passage (PT-128-S-4-P-2)', content: passageText },
        { type: 'h3', text: "Question 12: Author Viewpoint Breakdown (PT-128-S-4-P-2-Q-12)" },
        { type: 'blockquote', text: "**Question:** The author of the passage would be most likely to agree with which one of the following statements?" },
        { type: 'options', items: [
          "(A) Most people who consider themselves to be artists are merely documenting their personal suffering and fobbing it off as art.",
          "(B) The continuing presence of a topic in an artist’s work suggests that the topic is likely an issue in the artist’s personal life. (Correct)",
          "(C) Allen’s film career is unique in that he regularly features unhappy, narcissistic artists as protagonists.",
          "(D) An artist must use his or her own experiences as the source of inspiration for a work in order for that work to be considered truly artistic.",
          "(E) Allen’s films accurately reflect real life in depicting inartistic individuals as happier than artists."
        ]},
        { type: 'h4', text: "Analysis" },
        { type: 'paragraph', text: "Concept focus: author-viewpoint questions ask what belief the author is committed to, not just what details appear in the passage. Here, the key move comes when the author says a recurring theme in Allen's films appears often enough to seem like an \"unresolved personal issue.\" That move shows the author accepts a general idea: repeated patterns in an artist's work can reveal personal concerns." },
        { type: 'callout', title: "Text Evidence", variant: "tip", text: "Center your inference on \"appears sufficiently often ... to seem an unresolved personal issue.\" That is the author's own interpretive step, so the best answer should restate that step in general form without adding stronger claims the passage never makes." },
        { type: 'breakdown', labels: { title: 'Option', text: 'Analysis' }, items: [
          { title: "(A) Most people who consider themselves to be artists are merely documenting their personal suffering and fobbing it off as art.", text: "This turns a passage-specific film critique into a sweeping claim about \"most people.\" The author analyzes recurring themes in Allen's work; the author does not make a universal claim about artists in general.", badge: "Incorrect", badgeColor: "red" },
          { title: "(B) The continuing presence of a topic in an artist’s work suggests that the topic is likely an issue in the artist’s personal life.", text: "This directly captures the author's reasoning. The passage links repeated appearance of a theme to a likely personal issue for Allen, and this choice states that same inference rule in general terms.", badge: "Correct", badgeColor: "green" },
          { title: "(C) Allen’s film career is unique in that he regularly features unhappy, narcissistic artists as protagonists.", text: "The passage says the pattern is frequent in Allen's films, but \"unique\" requires comparison with other filmmakers, and no such comparison is provided.", badge: "Incorrect", badgeColor: "red" },
          { title: "(D) An artist must use his or her own experiences as the source of inspiration for a work in order for that work to be considered truly artistic.", text: "This adds a strict rule about what art \"must\" do and what counts as \"truly artistic.\" The passage offers interpretation, not a prescriptive theory of art.", badge: "Incorrect", badgeColor: "red" },
          { title: "(E) Allen’s films accurately reflect real life in depicting inartistic individuals as happier than artists.", text: "The author uses those endings to interpret Allen's stance inside his films, not to prove those endings are realistic depictions of life outside the films.", badge: "Incorrect", badgeColor: "red" }
        ]}
      ]
};
