import { Lesson } from '../../types';

const passageText = `In filmmaker Woody Allen’s Deconstructing Harry, the writer Harry Block is presented as extremely neurotic and narcissistic. Block uses his experiences as fodder for his work, no matter how embarrassing the result may be for the other people in his life. And while Allen exaggerates Block’s narcissism for comic effect, the effect is not simply comic: the film is emblematic of Allen’s career precisely because of its extravagantly exaggerated censure of a life dedicated to and obsessed with art. Deconstructing Harry may be the most unequivocally peevish of Allen’s depictions of artists, but it is less a new direction for Allen than a concentrated reprise of a theme present throughout his career.
For instance, a film producer in Stardust Memories, Allen’s sourest portrait of artists before Harry, articulates a particularly cynical view of cinematic art after a screening of a film-in-progress by Stardust Memories’ main character, Sandy Bates. The producer says of Bates, “His insights are shallow and morbid. I’ve seen it all before. They try to document their private suffering and fob it off as art.” The producer, like all the figures in this film, often seems less a distinct individual than a projection of Bates’s personal self-recriminations. This effectively reinforces the charge of solipsism with which Bates, the unstable and demoralized artist, indicts himself. Indeed, the possibility that artists are merely “documenting their private suffering and fobbing it off as art” appears sufficiently often in Allen’s films to seem an unresolved personal issue.
In Manhattan, the ex-wife of a television writer and aspiring novelist offers a denigratory take on the artistic enterprise that is similar to the producer’s in Stardust Memories. Her book documenting the collapse of her marriage punctures her ex-husband’s artistic pretensions by revealing that he “longed to be an artist but balked at the necessary sacrifices. In his most private moments, he spoke of the fear of death, which he elevated to tragic heights when, in fact, it was mere narcissism.”
It is also significant that in Allen’s films, the less artistic the characters, the more likely their narrative is to result in a happy ending. Thus, the filmmaker in Crimes and Misdemeanors, the novelist in Husbands and Wives, and the screenwriter in Celebrity all wind up desolate and solitary, largely because of the egocentric and exploitative attitudes embodied in their art and the effects of those attitudes on those around them. On the other hand, the unpretentious, thoroughly inartistic title character in Zelig dies an untroubled, even happy, death, only slightly compromised by his failure to finish reading Moby-Dick. And the title character and talent agent in Broadway Danny Rose is the beneficiary of the most gratifying resolution Allen has scripted, primarily due to altruistic devotion to his utterly talentless nightclub performers.`;

export const Lesson2_Question7: Lesson = {
      id: "42-2",
      title: "Question 7: Main Idea",
      content: [
        { type: 'accordion', title: 'Read Passage', content: passageText },
        { type: 'h3', text: "Question Breakdown: PT-128-S-4-P-2-Q-7" },
        { type: 'blockquote', text: "**Question:** Which one of the following most accurately states the main point of the passage?" },
        { type: 'options', items: [
          "(A) The theme of the neurotic and narcissistic nature of artists is, though most intensely presented in Deconstructing Harry, one that Woody Allen has explored throughout his career. [76.0%] (Correct)",
          "(B) Woody Allen’s films suggest, by means of their depictions of artists, that the pursuit of an artistic life leads to unhappiness and that happiness is most often achieved by the inartistic. [16.0%]",
          "(C) Deconstructing Harry, like many of Woody Allen’s films, shows that the creation of art requires sacrifice, though many would-be artists are unable or unwilling to give up their comforts to create enduring works. [1.0%]",
          "(D) Woody Allen’s career indicates that, like most artists, he uses his own experiences and neuroses to create the works for which he has received the greatest acclaim. [6.0%]",
          "(E) Woody Allen’s films show that artists are unavoidably narcissistic and neurotic and that they are, because of this, able to produce works of great beauty and power. [1.0%]"
        ]},
        { type: 'paragraph', text: "This is a main point question, asking for the author's central thesis. The entire passage is structured to support the claim made at the end of the first paragraph: that the theme of the neurotic, narcissistic artist, exemplified by *Deconstructing Harry*, is not a new direction for Woody Allen but a \"concentrated reprise of a theme present throughout his career.\" The subsequent paragraphs are a collection of evidence from other films (*Stardust Memories*, *Manhattan*, etc.) designed to prove this consistency." },
        { type: 'paragraph', text: "A correct answer must capture this idea: the theme is not new, but a recurring one, with *Deconstructing Harry* being its most intense version." },
        { type: 'breakdown', labels: { title: 'Option', text: 'Analysis' }, items: [
          { title: "(A) The theme of the neurotic and narcissistic nature of artists is, though most intensely presented in Deconstructing Harry, one that Woody Allen has explored throughout his career.", text: "This is a near-perfect paraphrase of the author's thesis statement. It identifies the theme (\"neurotic and narcissistic nature of artists\"), notes the special status of *Deconstructing Harry* (\"most intensely presented\"), and states the core of the argument—that this is a career-long exploration.", badge: "Correct", badgeColor: "green" },
          { title: "(B) Woody Allen’s films suggest, by means of their depictions of artists, that the pursuit of an artistic life leads to unhappiness and that happiness is most often achieved by the inartistic.", text: "This statement is true according to the passage, as it summarizes the final paragraph. However, this is a major piece of *evidence* the author uses to support the main point. The main point is broader; it's about the consistency of the theme of the narcissistic artist across Allen's career. This choice elevates a supporting argument to the main idea.", badge: "Incorrect", badgeColor: "red" },
          { title: "(C) Deconstructing Harry, like many of Woody Allen’s films, shows that the creation of art requires sacrifice, though many would-be artists are unable or unwilling to give up their comforts to create enduring works.", text: "The idea of \"sacrifice\" is mentioned only once, as part of a quote in the *Manhattan* example. This is a minor detail, not the central theme of the passage, which focuses on narcissism and egocentrism.", badge: "Incorrect", badgeColor: "red" },
          { title: "(D) Woody Allen’s career indicates that, like most artists, he uses his own experiences and neuroses to create the works for which he has received the greatest acclaim.", text: "The passage analyzes the *content* of Allen's films, not the biographical details of his creative process. While it suggests the theme may be a \"personal issue\" for Allen, it does not make a broad claim about how he creates his art or compare him to \"most artists.\"", badge: "Incorrect", badgeColor: "red" },
          { title: "(E) Woody Allen’s films show that artists are unavoidably narcissistic and neurotic and that they are, because of this, able to produce works of great beauty and power.", text: "The first part of this statement is consistent with the passage, but the second part is a direct contradiction. The passage describes the art produced by these characters as \"shallow and morbid,\" not as works of \"great beauty and power.\"", badge: "Incorrect", badgeColor: "red" }
        ]}
      ]
};
