import { Lesson } from '../../types';

const passageText = `In filmmaker Woody Allen's Deconstructing Harry, the writer Harry Block is presented as extremely neurotic and narcissistic. Block uses his experiences as fodder for his work, no matter how embarrassing the result may be for the other people in his life. And while Allen exaggerates Block's narcissism for comic effect, the effect is not simply comic: the film is emblematic of Allen's career precisely because of its extravagantly exaggerated censure of a life dedicated to and obsessed with art. Deconstructing Harry may be the most unequivocally peevish of Allen's depictions of artists, but it is less a new direction for Allen than a concentrated reprise of a theme present throughout his career.
For instance, a film producer in Stardust Memories, Allen's sourest portrait of artists before Harry, articulates a particularly cynical view of cinematic art after a screening of a film-in-progress by Stardust Memories' main character, Sandy Bates. The producer says of Bates, \u201cHis insights are shallow and morbid. I've seen it all before. They try to document their private suffering and fob it off as art.\u201d The producer, like all the figures in this film, often seems less a distinct individual than a projection of Bates's personal self-recriminations. This effectively reinforces the charge of solipsism with which Bates, the unstable and demoralized artist, indicts himself. Indeed, the possibility that artists are merely \u201cdocumenting their private suffering and fobbing it off as art\u201d appears sufficiently often in Allen's films to seem an unresolved personal issue.
In Manhattan, the ex-wife of a television writer and aspiring novelist offers a denigratory take on the artistic enterprise that is similar to the producer's in Stardust Memories. Her book documenting the collapse of her marriage punctures her ex-husband's artistic pretensions by revealing that he \u201clonged to be an artist but balked at the necessary sacrifices. In his most private moments, he spoke of the fear of death, which he elevated to tragic heights when, in fact, it was mere narcissism.\u201d
It is also significant that in Allen's films, the less artistic the characters, the more likely their narrative is to result in a happy ending. Thus, the filmmaker in Crimes and Misdemeanors, the novelist in Husbands and Wives, and the screenwriter in Celebrity all wind up desolate and solitary, largely because of the egocentric and exploitative attitudes embodied in their art and the effects of those attitudes on those around them. On the other hand, the unpretentious, thoroughly inartistic title character in Zelig dies an untroubled, even happy, death, only slightly compromised by his failure to finish reading Moby-Dick. And the title character and talent agent in Broadway Danny Rose is the beneficiary of the most gratifying resolution Allen has scripted, primarily due to altruistic devotion to his utterly talentless nightclub performers.`;

export const Lesson5_Question10: Lesson = {
      id: "42-5",
      title: "Question 10: Phrase Meaning",
      content: [
        { type: 'accordion', title: 'Read Passage', content: passageText },
        { type: 'h3', text: "Question Breakdown: PT-128-S-4-P-2-Q-10" },
        { type: 'blockquote', text: "**Question:** The author\u2019s use of the word \u201cpeevish\u201d in the first paragraph is intended to suggest which one of the following?" },
        { type: 'options', items: [
          "(A) offensive [18.0%]",
          "(B) neurotic [18.0%]",
          "(C) stubborn [2.0%]",
          "(D) egocentric [12.0%]",
          "(E) sour [50.0%] (Correct)"
        ]},
        { type: 'paragraph', text: "This question asks for the meaning of the word \"peevish\" as it is used in the first paragraph. This is a vocabulary-in-context question. Even if you know the dictionary definition, the LSAT is asking how the author is using the word *in this specific context*. The best clues come from the surrounding text and any parallel constructions the author uses." },
        { type: 'paragraph', text: "The key sentence states: \"*Deconstructing Harry* may be the most unequivocally **peevish** of Allen's depictions of artists...\" To understand what the author means by \"peevish,\" we should look for related descriptive words. The very next paragraph provides the strongest possible clue when describing a different film: \"*Stardust Memories*, Allen's **sourest** portrait of artists before Harry...\"" },
        { type: 'callout', title: "Prediction", variant: "tip", text: "The author is using \"peevish\" and \"sourest\" in a parallel way: *Deconstructing Harry* is the most intensely critical (\"peevish\"), while *Stardust Memories* was the previous record-holder (\"sourest\"). Since the author is treating these words as near-synonyms to describe the irritable, cynical tone of these films, look for an answer choice that matches the word \"sour.\"" },
        { type: 'breakdown', labels: { title: 'Option', text: 'Analysis' }, items: [
          { title: "(A) offensive", text: "While a critique might be offensive, \"peevish\" describes the irritable and ill-tempered nature of the critique itself, not its effect on the audience. The passage frames the depiction as cranky and cynical, not as something designed to shock or offend.", badge: "Incorrect", badgeColor: "red" },
          { title: "(B) neurotic", text: "\"Neurotic\" is used to describe the characters *in* the films, not the films themselves. \"Peevish\" is used to describe the film's *depiction* or tone, which is a critique *of* the neurotic characters. This confuses the subject of the critique with the tone of the critique.", badge: "Incorrect", badgeColor: "red" },
          { title: "(C) stubborn", text: "While the theme is persistent across Allen's career, \"stubborn\" does not capture the negative, irritable quality implied by \"peevish.\" Stubbornness suggests refusal to change, not a bitter or cynical attitude.", badge: "Incorrect", badgeColor: "red" },
          { title: "(D) egocentric", text: "Like \"neurotic,\" this is a trait of the characters being criticized, not the tone of the critique itself. The passage distinguishes between what the films portray (egocentric artists) and how the films portray them (peevishly, sourly).", badge: "Incorrect", badgeColor: "red" },
          { title: "(E) sour", text: "This is the word the author uses in a parallel construction just one paragraph later, providing a clear contextual synonym. \"Sour\" perfectly captures the sense of a bitter, cynical, and ill-tempered attitude, which aligns with the standard meaning of \"peevish.\"", badge: "Correct", badgeColor: "green" }
        ]}
      ]
};
